<!-- grn lines search results -->
<?php
    $resultsForm = $this->getHelper('SysScreenSearchResult');
    $resultsForm->setTabs($this->tabs)->setFields($this->fields)->setActions($this->actions);
?>

<form id="grn_line_results_form" name="grn_line_results_form" action="<?php echo $this->url(); ?>" method="post">
    <!-- tabs container start -->
    <div id="grn_line_tabs" class="ui-tabs-container">
        <div style="display: none;" class="JSON"><?php echo json_encode(array('errors' => $this->errors));?></div>
        <?php echo $resultsForm->renderTabsList(array()); ?>

        <div class="ui-tabs-panel-header">
            <div class="sys-screen-title" title="<?php echo $this->linesSysScreenName;?>">GRN Lines List<span class="modification_flag <?php echo $this->grnLineSelectionNamespace;?>"></span></div>
            <div class="paginator-container">
                <?php echo $this->formLabel('select_complete_label', 'Select All Rows on all pages', array('disableFor' => true));?>
                <?php echo $this->formCheckbox('select_complete', 0, array('checked' => ($this->totalLines == $this->selectedLinesCount), 'row_id' => 'select_complete', 'class' => 'select_complete ' . $this->grnLineSelectionNamespace));?>
                <label for="results_per_page">View By:</label>
                <?php echo $this->formSelect('show_by', 
                                            $this->navigation['show_by'],
                                            array(),
                                            array(5  => 5,
                                                  10 => 10,
                                                  15 => 15,
                                                  20 => 20,
                                                  30 => 30,
                                                  40 => 40,
                                                  50 => 50,
                                                  100 => 100)) ?>
                <label for="page">Page:</label>
                <?php echo $this->formSelectStrict('pageselector',
                                                $this->navigation['pageselector'],
                                                array(),
                                                $this->pages); ?>
            </div>
         
            <ul class="black-top-border" style="clear: both;">
                <li style="display: inline;">Selected: <span class="selected_count <?php echo $this->grnLineSelectionNamespace;?>"><?php echo $this->selectedLinesCount;?></span></li>
            </ul>
        </div>

        <?php foreach ($resultsForm->getTabs() as $tabId => $tabCaption) {?>
            <?php echo $resultsForm->renderTab($tabId, array(), false);?>
            <?php echo $resultsForm->renderTabContent(
                                    $tabId, 
                                    array(
                                        'select_all_checked'    => (count($this->lines) == count($this->selectedLines)), 
                                        'selection_namespace'   => $this->grnLineSelectionNamespace, 
                                        'switch_selection_mode' => $this->selectMode,
                                        'tab_content_class'     => 'withborder tablesorter grn_line_list'
                                    ), 
                                    $this->lines, 
                                    $this->selectedLines
            );?>
                <!-- totals info start -->
                <table class="withborder" width="100%">
                    <tr>
                        <td>Total <span class="total_count <?php echo $this->grnLineSelectionNamespace;?>"><?php echo $this->numRecords;?></span> records.<?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno); ?></td>
                    </tr>
                </table>
                <!-- totals info end -->

            </div>    
        <?php }?>

        <div style="clear: both; padding-left: 10px;">
            <?php echo $resultsForm->renderButtons($this->grnLineButtons); ?>

            <script type="text/javascript">
                <?php echo $resultsForm->renderButtonActions($this->grnLineButtons); ?>
            </script>
        </div>
    </div>
    <!-- tabs container end -->
</form>
<!-- grn lines search results -->

<!-- product label dialog -->
<div style="display: none;" id="product_label_dialog" title="Print Product Labels" class="flora">
    <form name="product_label_form" id='product_label_form' action="" method="POST">
        <table align="center" style="margin: 5px 0px;" width="100%">
            <tr>
                <td colspan="2">
                    <input type="radio" name="product_label_type" value="PRODUCT_LABEL" checked="checked" /> Item Barcode &nbsp; &nbsp; &nbsp;
                    <input type="radio" name="product_label_type" value="PRODUCT_INNER" /> Inner Pack &nbsp; &nbsp; &nbsp;
                    <input type="radio" name="product_label_type" value="PRODUCT_OUTER" /> Outer Pack
                </td>
            </tr>
            <tr><td colspan="2">&nbsp;</td></tr>
            <tr>
                <td colspan="2" align="center">
                    <div class="disabled" style="padding: 0 10px; text-align: center; border: blue 1px solid;">Product Id: <span class="PROD_ID"><?php echo ((isset($this->firstSelectedLine['PROD_ID'])) ? $this->firstSelectedLine['PROD_ID'] : '&nbsp;');?></span></div>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <div class="disabled" style="padding: 0 10px; text-align: center; border: blue 1px solid;"><span class="PROD_DESCRIPTION"><?php echo ((isset($this->firstSelectedLine['DESCRIPTION'])) ? $this->firstSelectedLine['DESCRIPTION'] : '&nbsp;');?></span></div>
                </td>
            </tr>
            <tr><td colspan="2">&nbsp;</td></tr>
            <tr>
                <td colspan="2">
                    <table width="100%">
                        <tr>
                            <td>Qty of Labels</td>
                            <td><input style="width: 40px;" type="text" name="first_label_qty" value="1" /></td>
                            <td>Total Printed on Label</td>
                            <td><input style="width: 40px;" type="text" name="first_label_total" value="1" /></td>
                        </tr>
                        <tr>
                            <td>Qty of Labels</td>
                            <td><input style="width: 40px;" type="text" name="second_label_qty" value="0" /></td>
                            <td>Total Printed on Label</td>
                            <td><input style="width: 40px;" type="text" name="second_label_total" value="0" /></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr><td colspan="2">&nbsp;</td></tr>
            <tr>
                <td align="center">
                    <button name="PRINT" class="green-button">PRINT</button>
                </td>
                <td align="center">
                    <button name="CANCEL" class="yellow-button">CANCEL</button>
                </td>
            </tr>
        </table>
    </form>
</div>
<!-- product label dialog -->

<script type="text/javascript">
    $(document).ready(function () {
        initProductLabelDialog();
        
        var jsonResponse = $.parseJSON($('#grn_line_tabs .JSON').html());
        if (jsonResponse.errors && jsonResponse.errors.length > 0)
            showErrors(jsonResponse.errors);
        
        $('#grn_line_tabs > ul').tabs();
        $('#grn_line_tabs #pageselector, #grn_line_tabs #show_by').change(function(){
            getGrnLines();
        });
        $('.grn_line_list').tablesorter({headers:{0:{sorter:false}}, widgets: ['zebra']});
        
        $('.row_selector.<?php echo $this->grnLineSelectionNamespace;?>, .select_all_rows.<?php echo $this->grnLineSelectionNamespace;?>, .select_complete.<?php echo $this->grnLineSelectionNamespace;?>').minderRowSelector(
            '<?php echo $this->url(array('module' => $this->grnLineSelectionModule, 'controller' => $this->grnLineSelectionController, 'action' => $this->grnLineSelectionAction), null, true);?>',
            {
                'scopeSelector'       : '#grn_line_tabs',
                'selectionNamespace'  : '<?php echo $this->grnLineSelectionNamespace?>',
                'selectionAction'     : '<?php echo $this->grnLineSelectionAction;?>',
                'selectionController' : '<?php echo $this->grnLineSelectionController;?>'
            },
            {
                'onSuccess': function(response) {
                    if(response.warnings && response.warnings.length > 0)
                        showWarnings(response.warnings);
                    
                    if(response.messages && response.messages.length > 0)
                        showMessage(response.messages);

                    getChangeLines();
                    
                    if (response.selected == 1)
                        $('#grn_line_tabs #print_product').removeAttr('disabled');
                    else 
                        $('#grn_line_tabs #print_product').attr('disabled', true);
                    
                    if (response.selected > 0) {
                        $('#grn_line_tabs #product_details').removeAttr('disabled');
                        $('#grn_line_tabs #issn_details').removeAttr('disabled');
                        $('#grn_line_tabs #ssn_details').removeAttr('disabled');
                        $('#grn_line_tabs #print_issn').removeAttr('disabled');
                    }
                    else {
                        $('#grn_line_tabs #product_details').attr('disabled', true);
                        $('#grn_line_tabs #issn_details').attr('disabled', true);
                        $('#grn_line_tabs #ssn_details').attr('disabled', true);
                        $('#grn_line_tabs #print_issn').attr('disabled', true);
                    }
                    
                    if (response.firstSelectedRow) {
                        if (typeof response.firstSelectedRow['PROD_ID'] !== 'undefined')
                            $('#product_label_dialog .PROD_ID').html(response.firstSelectedRow['PROD_ID']);

                        if (typeof response.firstSelectedRow['DESCRIPTION'] !== 'undefined')
                            $('#product_label_dialog .PROD_DESCRIPTION').html(response.firstSelectedRow['DESCRIPTION']);
                    }
                    
                    if ($('#GRN_PRODUCT_DETAILS_CONTAINER').html() !== '') {
                        //product details was loaded, so after selection has changed, should reload product details
                        getGrnProductDetails();
                    }
                }
            }
        );
        
        $('#grn_line_tabs #issn_details').unbind('click.grn-line-search-results-form').bind('click.grn-line-search-results-form', issnDetailsOnClick);
        $('#grn_line_tabs #ssn_details').unbind('click.grn-line-search-results-form').bind('click.grn-line-search-results-form', ssnDetailsOnClick);
    });

    function issnDetailsOnClick(evt) {
        evt.preventDefault();
        
        if ($('#GRN_ISSN_DETAILS_CONTAINER').html() === '') {
            //ISSN details not loaded, loading
            getGrnIssnDetails();
        } else {
            //ISSN details loaded, removing
            $('#GRN_ISSN_DETAILS_CONTAINER').html('');
        }
    }
    
    function ssnDetailsOnClick(evt) {
        evt.preventDefault();
        
        if ($('#GRN_SSN_DETAILS_CONTAINER').html() === '') {
            //SSN details not loaded, loading
            getGrnSsnDetails();
        } else {
            //SSN details loaded, removing
            $('#GRN_SSN_DETAILS_CONTAINER').html('');
        }
    }
    
    function showProductDetails() {
        if ($('#GRN_PRODUCT_DETAILS_CONTAINER').html() === '') {
            //product details not loaded, loading
            getGrnProductDetails();
        } else {
            //product details loaded, removing
            $('#GRN_PRODUCT_DETAILS_CONTAINER').html('');
        }
    }
    
    function getGrnIssnDetails() {
        showErrors(['Screen not available']);
    }
    
    function getGrnSsnDetails() {
        showErrors(['Screen not available']);
    }
    
    function getGrnProductDetails() {
        var data = {};
        var showBy = parseInt($('#GRN_PRODUCT_DETAILS_CONTAINER #show_by').val());
        var pageselector = parseInt($('#GRN_PRODUCT_DETAILS_CONTAINER #pageselector').val());
        if (!(isNaN(showBy) || showBy === 0)) {
            data.show_by = showBy;
        }
        
        if (!isNaN(pageselector)) {
            data.pageselector = pageselector;
        }
        
        $('#GRN_PRODUCT_DETAILS_CONTAINER').html('');
        $('#GRN_PRODUCT_DETAILS_CONTAINER').load(
            '<?php echo $this->url(array('module' => 'receipts', 'controller' => 'grn', 'action' => 'get-grn-product-details'), null, true);?>',
            data,
            function(){
                
            }
        );
    }
    
    function initProductLabelDialog() {
        $('#product_label_dialog').dialog(
            { 
                autoOpen  : false,
                width     : 360,
                height    : 255,
                resizable : false
            }
        ).unbind('dialogopen.grn-line-search-results-form').bind('dialogopen.grn-line-search-results-form', function(event, ui) {
            $(this).show();
            $(this).find('input[name=qty1]').focus();
        });
        
        $('#product_label_dialog button[name=CANCEL]').unbind('click.grn-line-search-results-form').bind('click.grn-line-search-results-form', function(evt){
            evt.preventDefault();
            $('#product_label_dialog').dialog('close');
        });
        
        $('#product_label_dialog button[name=PRINT]').unbind('click.grn-line-search-results-form').bind('click.grn-line-search-results-form', productLabelDialogPrintOnClick);
    }
    
    function destroyProductLabelDialog() {
        $('#product_label_dialog').dialog('destroy').remove();
    }
    
    function productLabelDialogPrintOnClick(evt) {
        evt.preventDefault();
        
        var dataToSubmit = {
            'selection_namespace'  : '<?php echo $this->grnLineSelectionNamespace?>',
            'selection_action'     : '<?php echo $this->grnLineSelectionAction;?>',
            'selection_controller' : '<?php echo $this->grnLineSelectionController;?>'
        };
        $.map($('#product_label_form').serializeArray(), function(elementOfArray, indexInArray){
            dataToSubmit[elementOfArray.name] = elementOfArray.value;
            return null;
        });
        
        if (dataToSubmit.first_label_qty > 100) {
            if (!confirm('You try to print ' + dataToSubmit.first_label_qty + ' labels. Are you sure?'))
                return;
        }

        if (dataToSubmit.second_label_qty > 100) {
            if (!confirm('You try to print ' + dataToSubmit.second_label_qty + ' labels. Are you sure?'))
                return;
        }

        $.getJSON(
            '<?php echo $this->url(array('module' => 'receipts', 'controller' => 'grn', 'action' => 'print-product-label'), null, true);?>',
            dataToSubmit,
            function(response) {
                if (response.errors && response.errors.length > 0) {
                    showErrors(response.errors);
                }

                if (response.warnings && response.warnings.length > 0) {
                    showWarnings(response.warnings);
                }

                if (response.messages && response.messages.length > 0) {
                    showMessage(response.messages);
                }
            }
        );
    }

function printProduct() {
    $('#product_label_dialog').dialog("open");
}

</script>