<form action="<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'despatched-orders'), null, true); ?>" method="post" id="lines_form">
<?php echo $this->formHidden('from', 'issn-despatch') ?>  
<div id="json" style="display: none;"><?php echo json_encode($this->counters) ?></div>
    <div>
        <div style="float: left; font-weight: bold; text-transform: uppercase;">ISSNs LIST</div>
        <div style="position: relative; left:10px;">
            <label for="results_per_page">View By:</label>
            <?php echo $this->formSelect('show_by',
                                        $this->navigation['show_by'],
                                        array('onchange' => 'frmSubmitPaging()'),
                                        array(5  => 5,
                                              10 => 10,
                                              15 => 15,
                                              20 => 20,
                                              30 => 30,
                                              40 => 40,
                                              50 => 50,
                                              100 => 100)) ?>
            <label for="page">Page:</label>
            <?php echo $this->formSelectStrict('pageselector',
                                               $this->navigation['pageselector'],
                                               array('onchange' => 'frmSubmitPaging()'),
                                               $this->pages); ?>
        </div>
    </div>
    <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999;">
        <li style="display: inline;">Selected: <span class="pack_lines_selected">0</span></li>
    </ul>
    <table id=line_list class="withborder tablesorter">
        <thead>
        <tr>
            <th><input type="checkbox" id="select_all_lines" onclick="selectAllLines(this)" /></th>
<?php
    foreach ($this->headers as $header) {
        echo '<th>'. $this->escape($header) . '</th>';
    }
?>
        </tr>
        </thead>
        <tbody>

<?php
        foreach ($this->issnList as $issn) { ?>
        <tr>
            <th><?php echo $this->formCheckbox($issn['SSN_ID'], $issn['SSN_ID'], array('checked' => array_key_exists($issn['SSN_ID'], (array) $this->conditions) ? 'checked' : '', 'class' => 'line-selector', 'onclick' => 'checkLine(this)')) ?></th>
<?php     foreach ($this->headers as $key => $val) { ?>
            <td>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'edit-issn', 'edit_issn_ssn_id' => $issn['SSN_ID']), null, true); ?>"><?php echo $this->escape($issn[$key]) ?></a>
            </td>

<?php     } ?>
        </tr>
<?php }  ?>
<?php if (!count($this->issnList)) : ?>
        <tr>
            <th/>
<?php foreach ($this->headers as $v) : ?>
            <td/>
<?php endforeach; ?>
        </tr>
<?php endif ?>
        </tbody>
    </table>
     <table class="withborder" id="lines-info">
        <tr>
            <td width="20%">Total <?php echo $this->numRecords . ($this->numRecords > 1 ? ' records' : ' record') ?></td>
            <td width="20%">Show from <?php echo ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1) . ' to ' . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno); ?></td>
            <td width="20%">&nbsp;<td>
            <td width="20%">&nbsp;</td>
            <td width="20%">&nbsp;</td>
        </tr>
    </table>
     <ul class="toolbar" style="margin-top: 3px;" id="edit_field_buttons">
        <li>
            <input type="button" class="order-button" name="action" id="returned" value="RETURNED" onclick="return goReturn();" />
        </li>
        <li>
            <input type="button" class="order-button" name="action" id="return_all" value="RETURN ALL" onclick="return goReturnAll();" />
        </li>
        <li>
            <input type="submit" class="order-button" name="action" id="report: csv" value="REPORT: CSV" onclick="return frmSubmitLines(this)" />
        </li>
        <li>
            <input type="submit" class="order-button" name="action" id="report: xls" value="REPORT: XLS" onclick="return frmSubmitLines(this)" />
        </li>
    </ul>
</form>
<br />
<div id="returned_form" style="display: none;"></div>


<script type="text/javascript">
$(document).ready(function(){

	  $("#line_list").tablesorter({headers: {0: {sorter:false}},sortList:[[1,0]], widgets: ['zebra']});
      
      disableReturnsButton();
    
});


function checkLine(target) {
    
    var linesSelected = parseInt($('.pack_lines_selected').text());
    if(target.checked) {
        linesSelected++;        
    } else {
        linesSelected--;
    }
    
    $('.pack_lines_selected').text(linesSelected);
    
    disableReturnsButton();

}

function selectAllLines(target) {
    
    var condition = target.checked;
    
    var chkBoxes        =   $('#line_list :checkbox');
    var count           =   $('#line_list :checkbox').size();  
    
    $.each(chkBoxes, function(){
        this.checked =   condition; 
    })
    
    if(condition) {
        $('.pack_lines_selected').text(count-1);    
    } else {
        $('.pack_lines_selected').text(0);    
    }
    
    disableReturnsButton();
}

function frmSubmitLines(){
	$('#lines_form').attr('action', "<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'issn-despatch'), null, true); ?>").submit();	
}

function frmSubmitPaging() {
	$('#lines_form').attr('action', "<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'despatched-orders'), null, true); ?>").submit();	
}

function goReturn(){
    
    var selectedId  =   new Array();
    
    $.each($('#line_list tbody :checked'), function(){
        selectedId.push($(this).val());    
    })
    
    $('#returned_form').load('<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'returned'), null, true); ?>',
    {
        selected_id:    selectedId.join('|'),
        first_select:   true        
    }, function(){
         $('#returned_form').show();
    });
    
    return false;    
}

function goReturnAll(){
    
    var selectedId  =   new Array();
    
    $.each($('#line_list tbody :checked'), function(){
        selectedId.push($(this).val());    
    })
    
    $('#returned_form').load('<?php echo $this->url(array('module' => 'default', 'controller' => 'despatch', 'action' => 'returned'), null, true); ?>',
    {
        action:         'LOAD_FORM',
        selected_id:    selectedId.join('|'),
    }, function(){
         $('#returned_form').show();
    });
    
    return false;    
}

function disableReturnsButton(){
    
    var selectedCount   =   $('#line_list tbody :checked').size();
  
    if(selectedCount > 0){
        $('#returned').css("background-color", "#00FF00");
        $('#returned').removeAttr('disabled').removeClass('disabled');
        
        $('#return_all').css("background-color", "#00FF00");
        $('#return_all').removeAttr('disabled').removeClass('disabled');    
    } else {
        $('#returned').css("background-color", "#FF0000");
        $('#returned').attr('disabled', 'disabled').addClass('disabled');
        
        $('#return_all').css("background-color", "#FF0000");
        $('#return_all').attr('disabled', 'disabled').addClass('disabled');    
    }
}


</script>
