<?php echo $this->render('header.phtml'); ?>

<h2>EDIT : <?php echo $this->escape($this->ssnObj->id); ?></h2>
<?php
echo $this->messenger()->all();

if (!isset($this->action)) {
    if (!$this->wasErrors) {
        echo $this->render('/ssn/ssn-issn.phtml');
    }
} else {
?>
<h2><?php echo $this->pageTitle; ?></h2>
<?php
}
?>
<div style="float: left;">
<form name="main" action="" method="post" enctype="multipart/form-data">
<ul class="toolbar">
    <li><?php echo $this->formSubmit('action', 'SAVE & RETURN', array('onclick' => 'return goDelete();')); ?></li>
    <li><?php echo $this->formSubmit('action', 'SAVE & PRINT ALL'); ?></li>
    <li><?php echo $this->formSubmit('action', 'CANCEL CHANGES'); ?></li>
</ul>

<?php
    switch ($this->formStyle) {
        case 'simplified':
            echo $this->render('/ssn/edit/simplified.phtml');
            break;
        default:
            echo $this->render('/ssn/edit/default.phtml');
    }
?>

<ul class="toolbar">
    <li><?php echo $this->formSubmit('action', 'SAVE & RETURN', array('onclick' => 'return goDelete();')); ?></li>
    <li><?php echo $this->formSubmit('action', 'SAVE & PRINT ALL'); ?></li>
    <li><?php echo $this->formSubmit('action', 'CANCEL CHANGES'); ?></li>
</ul>
<br />
<h2>History List</h2>
<div id="history_list">

</div>
</form>
</div>
<script type="text/javascript">
    $(function(){
        loadHistoryLines();
    });

    function loadHistoryLines() {
        $('#history_list').load('<?php echo $this->url(array('action' => 'history', 'controller' => 'ssn', 'module' => 'warehouse')); ?>');
    }
</script>
<?php echo $this->render('footer.phtml');