<?php
echo $this->render('header.phtml');
?>

<h2>Demo - Update new Purchase Order #906</h2>
<?php
/*
if ($this->updated) {

} else {
?>
<form action="" method="post">
<ul class="toolbar">
    <li>
<?php echo $this->formNote('qty', 'Enter Qty:');?>
    </li>
    <li>
<?php echo $this->formText('qty', 0, array());?>
    </li>
    <li>
<?php echo $this->formSubmit('action', 'UPDATE', array());?>
    </li>
</ul>
</form>
<?php
}
*/
?>



<?php
echo $this->render('footer.phtml');
?>