<html>
    <head>
        <title>Main Menu</title>
        <style>
ul {
    border: 0;
    padding: 0;
    margin: 0;
}
li {
    border: 0;
    padding: 0;
    margin: 0;
    display: inline;
}
img {
    border: 0;
}
        </style>
    </head>
    <body>
        <ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/description.gif"></li>
                <li><img src="/minder/www/icons/50x100/despatch.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/transfer.gif"></li>
                <li><img src="/minder/www/icons/50x100/stocktake.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/test.gif"></li>
                <li><img src="/minder/www/icons/50x100/putawaytest.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/putawayssn.gif"></li>
                <li><img src="/minder/www/icons/50x100/pick2trolley.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/pick2despatch.gif"></li>
                <li><img src="/minder/www/icons/50x100/pickproduct.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/pickssn.gif"></li>
                <li><img src="/minder/www/icons/50x100/pick.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/query.gif"></li>
                <li><img src="/minder/www/icons/50x100/logout.gif"></li>
            </ul>
            <ul>
                <li><img src="/minder/www/icons/50x100/receive.gif"></li>
                <li><img src="/minder/www/icons/50x100/reprint.gif"></li>
            </ul>
        </ul>
    </body>
</html>
