<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->pageTitle; ?></title>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.tablesorter.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.datepicker.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/minder.js" type="text/javascript"></script>

<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.base.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.dialog.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.resizable.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/ui.draggable.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/ui/jquery.dimensions.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/jquery.blockUI.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/warehouse.js" type="text/javascript"></script>


<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>scripts/ui/themes/flora/flora.all.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>style/pc.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>style/12-inch.css" type="text/css" />
</head>
<body>
<div id="header">
    <ul id="top-nav">
<?php if ($this->minder->userId != null) { ?>
        <li>Welcome <?php echo $this->escape($this->minder->userId); ?></li>
        <li>Connected to <?php echo $this->minderVariant('MUSEUM*Minder'); ?></li>
        <li>WH:&nbsp;<?php echo $this->minder->whId ?></li>
        <li>DEV:&nbsp;<?php echo $this->minder->deviceId ?></li>
        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), '', true); ?>">Logout</a></li>
<?php } else { ?>
        <li>Not logged in <?php echo $this->minderVariant('MUSEUM*Minder'); ?></li>
        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'login'), '', true); ?>">Login</a></li>
<?php } ?>
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'about'), '', true); ?>">About</a></li>
    </ul>
    <img src="<?php echo $this->baseUrl; ?>icons/MDR_30x29.jpg" id="minder-logo" />
    <img height="40" src="<?php echo $this->baseUrl; ?>user/logo" id="logo" />
    <ul id="modules">
       <li class="selected"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), '', true); ?>">Home</a></li>
       <li><a href="<?php echo $this->url(array('module' => 'warehouse', 'controller' => 'index', 'action' => 'index'), '', true); ?>">Warehouse</a></li>
       <li><a href="<?php echo $this->url(array('controller' => 'orders', 'action' => 'index'), '', true); ?>">Orders</a></li>
       <li><a href="<?php echo $this->url(array('controller' => 'receipts', 'action' => 'index'), '', true); ?>">Receipts</a></li>
       <li><a href="<?php echo $this->url(array('controller' => 'despatches', 'action' => 'index'), '', true); ?>">Despatches</a></li>
       <li><a href="<?php echo $this->url(array('controller' => 'reports', 'action' => 'index'), '', true); ?>">Reports</a></li>
<?php if ($this->minder->isAdmin) { ?>
        <li><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), '', true); ?>">Administration</a></li>
<?php } ?>
    </ul>
</div>

<?php if ($this->shortcuts !== null) { ?>
<div style="float: left"><a href="#" onclick="showHideLeft();">X</a></div>

<div id="left">
    <h2>Shortcuts</h2>
    <div class="glossymenu">
<?php foreach ($this->shortcuts as $name => $url) {
          if (!is_array($url)) { ?>
        <a class="menuitem" href="<?php echo $this->escape($url); ?>"><?php echo $this->escape($name); ?></a>
<?php     } else { ?>
        <a class="menuitem submenuheader" href="#"><?php echo $this->escape($name); ?></a>
        <div class="submenu">
            <ul>
<?php       foreach ($url as $subname => $suburl) { ?>
                <li><a href="<?php echo $this->escape($suburl); ?>"><?php echo $this->escape($subname); ?></a></li>
<?php       } ?>
            </ul>
        </div>
<?php     } ?>
<?php } ?>
    </div>

<?php } ?>
<?php if ($this->minder->userId !== null && !$this->notShowLimit) { ?>
    <h2>Limit</h2>
    <form>
        <ul>
<?php
    $companies = array('all' => 'All');
    foreach ($this->minder->getCompanyList() as $key => $val) {
        $companies[$key] = $val;
    }
    $warehouses = array('all' => 'All');
    foreach ($this->minder->getWarehouseList(true) as $key => $val) {
        $warehouses[$key] = $val;
    }
    $printers = array();
    foreach ($this->minder->getPrinterList() as $key => $val) {
        $printers[$key] = $val;
    }
?>
            <li>Company<br /><?php echo $this->formSelect('limit_company', $this->minder->limitCompany, array(), $companies); ?></li>
            <li>Warehouse<br /><?php echo $this->formSelect('limit_warehouse', $this->minder->limitWarehouse, array(), $warehouses); ?></li>
            <li>Printer<br /><?php echo $this->formSelect('limit_printer', $this->minder->limitPrinter, array(), $printers); ?></li>
        </ul>
    </form>
</div>
<?php } ?>

<div id="page"<?php echo $this->shortcuts ? '' : ' style="margin-left: 0;"' ?>>
