<?php echo $this->render('header.phtml'); ?>

<form action="<?php echo $this->url(); ?>" method="post" onsubmit="return formSubmitted()">
    <h1>Sales Order: <?php echo $this->escape($this->pickOrder); ?></h1>

    <ul class="toolbar">
        <li><input type="submit" name="action" value="Save" /></li>
        <li><input type="submit" name="action" value="Save & New Line" /></li>
        <li><input type="submit" name="action" value="Discard Changes" /></li>
    </ul>

    <div class="section">
        <h2>New Line</h2>

        <table>
            <tr>
                <th>Product ID</th>
                <td><?php echo $this->formText('product_id', $this->line->productId, array('autocomplete' => 'off', 'tabindex' => '1')); ?></td>
                <th>Available Qty</th>
                <td><input type="text" id="available_qty" class="number" name="available_qty" value="<?php echo $this->escape($this->availableQty); ?>" disabled="true" /> <span id="uom"><?php echo $this->escape($this->availableUnit); ?></uom></td>
            </tr>
            <tr>
                <th>Product Description</th>
                <td><?php echo $this->formText('product_description', $this->line->productDescription, array('disabled' => 'disabled')); ?></td>
                <th>ISSN Sizes</th>
                <td><input type="text" name="issnSize0" id="issnSize0" class="number" disabled="true" value="<?php echo $this->escape($this->issnSizes[0]); ?>" /></td>
            </tr>
            <tr>
                <th>ISSN</th>
                <td><?php echo $this->formText('issn', $this->line->issn, array('autocomplete' => 'off', 'tabindex' => '2')); ?></td>
                <th></th>
                <td><input type="text" name="issnSize1" id="issnSize1" class="number" disabled="true" value="<?php echo $this->escape($this->issnSizes[1]); ?>" /></td>
            </tr>
            <tr>
                <th>ISSN Description</th>
                <td><?php echo $this->formTextarea('issn_description', $this->line->issnDescription, array('tabindex' => '', 'disabled' => 'disabled', 'rows' => 2, 'style' => 'width: 30ex')); ?></td>
                <th></th>
                <td><input type="text" name="issnSize2" id="issnSize2" class="number" disabled="true" value="<?php echo $this->escape($this->issnSizes[2]); ?>" /></td>
            </tr>
            <tr>
                <th>Contact</th>
                <td><?php echo $this->formText('contact', $this->line->contact, array('autocomplete' => 'off', 'tabindex' => '3')); ?></td>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <th>Unit Price</th>
                <td><?php echo $this->formText('price', $this->line->price, array('autocomplete' => 'off', 'onchange' => 'updateTotal()', 'class' => 'number', 'tabindex' => '4')); ?></td>
                <th rowspan="8" style="vertical-align: top;">Warehouse Totals</th>
                <td rowspan="8" style="vertical-align: top;">
                    <table id="warehouse_totals">
<?php foreach ($this->line->warehouseTotals as $whId => $qty): ?>
                        <tr>
                            <td><?php echo $this->escape($qty); ?></td>
                            <th><?php echo $this->escape($whId); ?></th>
                        </tr>
<?php endforeach; ?>
                    </table>
                </td>
            </tr>
            <tr>
                <th>GST %</th>
                <td><?php echo $this->formText('gst_text', $this->line->gst, array('autocomplete' => 'off', 'onchange' => 'updateTotal()', 'disabled' => 'true', 'class' => 'number')); ?><input type="hidden" name="gst" id="gst" value="<?php echo $this->line->gst; ?>" /></td>
            </tr>
            <tr>
                <th>Order Qty</th>
                <td><?php echo $this->formText('qty', $this->line->qty, array('autocomplete' => 'off', 'onchange' => 'updateTotal()', 'class' => 'number', 'tabindex' => 5)); ?></td>
            </tr>
            <tr>
                <th>Disc %</th>
                <td><?php echo $this->formText('discount_rate', $this->line->discountRate, array('autocomplete' => 'off', 'onchange' => 'updateTotal()', 'class' => 'number', 'tabindex' => '6')); ?></td>
            </tr>
            <tr>
                <th>Line Total $</th>
                <td><?php echo $this->formText('total', $this->line->total, array('autocomplete' => 'off', 'class' => 'number', 'disabled' => 'true')); ?></td>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <th>External Note</th>
                <td colspan="3"><?php echo $this->formTextarea('external_note', $this->line->externalNote, array('autocomplete' => 'off', 'tabindex' => '7')); ?></td>
            </tr>
            <tr>
                <th>Internal Note</th>
                <td colspan="3"><?php echo $this->formTextarea('internal_note', $this->line->internalNote, array('autocomplete' => 'off', 'tabindex' => '8')); ?></td>
            </tr>
        </table>
    </div>

    <ul class="toolbar">
        <li><input type="submit" name="action" value="Save" /></li>
        <li><input type="submit" name="action" value="Save & New Line" /></li>
        <li><input type="submit" name="action" value="Discard Changes" /></li>
    </ul>

</form>

<script type="text/javascript">
$(document).ready(function(){
    var productId = $('#product_id');
    productId.autocomplete('<?php echo $this->url(array('controller' => 'pick-order', 'action' => 'search'), '', false); ?>', {matchSubset: 1, matchContains: 1, cacheLength: 10, formatItem: formatItem, selectFirst: 1, extraParams: {field: 'product_id'}, onItemSelect: updateProductId, maxItemsToShow: 10});
    productId.focus();
    productId.change(toggleProductIdISSN);

    var issn = $('#issn');
    issn.autocomplete('<?php echo $this->url(array('controller' => 'pick-order', 'action' => 'search'), '', false); ?>', {matchSubset: 1, matchContains: 1, cacheLength: 10, formatItem: formatItem, selectFirst: 1, extraParams: {field: 'issn'}, onItemSelect: updateISSN, maxItemsToShow: 10});
    issn.change(toggleProductIdISSN);
});

function formatItem(row) {
    return row[0] + "<br><i>" + row[1] + "</i>";
}

function toggleProductIdISSN()
{
    var productId = $('#product_id')[0];
    var issn = $('#issn')[0];
    $('#product_description')[0].value = '';
    $('#issn_description')[0].value = '';
    if (productId.value == '') {
        issn.disabled = false;
    }
    if (issn.value == '') {
        productId.disabled = false;
    }
}

function updateProductId(li)
{
    $.getJSON('<?php echo $this->url(array('controller' => 'pick-order', 'action' => 'lookup'), '', false); ?>',
        { prod_id: $('#product_id')[0].value, pick_order: '<?php echo $this->escape($this->pickOrder); ?>' },
        function(p) {
            $('#product_description')[0].value = p.shortDesc;
            $('#uom')[0].innerHTML = p.uom;
            $('#price')[0].value = p.salePrice;
            $('#gst_text')[0].value = p.gst;
            $('#gst')[0].value = p.gst;
            $('#available_qty')[0].value = p.availableQty;
            $('#issnSize0')[0].value = p.issnSizes[0];
            $('#issnSize1')[0].value = p.issnSizes[1];
            $('#issnSize2')[0].value = p.issnSizes[2];
            var warehouseTotals = $('#warehouse_totals')[0];
            while (warehouseTotals.rows.length > 0) {
                warehouseTotals.deleteRow(0);
            }
            for (var i = 0; i < p.warehouseTotals.length; i = i + 1) {
                var row = warehouseTotals.insertRow(-1);
                var cell = row.insertCell(-1);
                cell.innerHTML = '<input type="text" name="wh_' + p.warehouseTotals[i].key + '" value="' + p.warehouseTotals[i].val + '" class="number" disabled="true" /> ' + p.warehouseTotals[i].key + '<br />';
            }
            $('#issn')[0].disabled = true;
            updateTotal();
        });
}

function updateISSN(li)
{
    $.getJSON('<?php echo $this->url(array('controller' => 'pick-order', 'action' => 'lookup'), '', false); ?>?issn=' + escape($('#issn')[0].value),
        function(p) {
            $('#issn_description')[0].value = p.ssnDescription;
            $('#uom')[0].innerHTML = p.uom;
            $('#price')[0].value = p.salePrice;
            $('#gst_text')[0].value = p.gst;
            $('#gst')[0].value = p.gst;
            $('#available_qty')[0].value = p.availableQty;
            $('#issnSize0')[0].value = p.issnSizes[0];
            $('#issnSize1')[0].value = p.issnSizes[1];
            $('#issnSize2')[0].value = p.issnSizes[2];
            var warehouseTotals = $('#warehouse_totals')[0];
            while (warehouseTotals.rows.length > 0) {
                warehouseTotals.deleteRow(0);
            }
            for (var i = 0; i < p.warehouseTotals.length; i = i + 1) {
                var row = warehouseTotals.insertRow(-1);
                var cell = row.insertCell(-1);
                cell.innerHTML = '<input type="text" name="wh_' + p.warehouseTotals[i].key + '" value="' + p.warehouseTotals[i].val + '" class="number" disabled="true" /> ' + p.warehouseTotals[i].key + '<br />';
            }
            $('#product_id')[0].disabled = true;
            updateTotal();
        });
}

function updateTotal()
{
    var price = parseFloat($('#price')[0].value);
    var qty = parseFloat($('#qty')[0].value);
    var discountRate = parseFloat($('#discount_rate')[0].value);
    if (isNaN(price)) {
        price = 0;
    }
    if (isNaN(qty)) {
        qty = 0;
    }
    if (isNaN(discountRate)) {
        discountRate = 0;
    }
    $('#price')[0].value = price.toFixed(2);
    var total = Math.round(price * qty * (1 - discountRate/100) * 100) / 100;
    $('#total')[0].value = total.toFixed(2);
}

function formSubmitted()
{
    updateTotal();
    return true;
}
</script>

<?php echo $this->render('footer.phtml'); ?>
