<style type="text/css">
    .with_border {
        border-top: solid 1px #999;
        border-bottom: solid 1px #999;
    }
    .without_border, .with_border {
        padding: .5em 0;
    }

    .form_item {
        margin: .5em 0;
    }
    .button {
        background: #a0df82;
        color: #000;
        font-weight: bold;
        padding: .6em !important;
        width: 10em !important;
        font-size: 1.1em !important;
        text-transform: uppercase;
    }

    table.with_border {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        border-top: none;
        border-bottom: solid 1px #999;
    }
    table.with_border td, table.with_border th {
        padding: .5em;
        margin: 0;
    }
    table.with_border th {
        width: 10%;
        text-align: right;
        white-space: nowrap;
    }
    table.with_border td {
        text-align: left;
    }

    #print_labels td, #print_labels th {
        border-top: none;
        border-bottom: solid 1px #999;
    }

    .info_bar {
        background: #a0df82;
        font-weight: bold;
        padding-left: .5em;
        padding-right: .5em;
    }
    .info_bar li, #info_bar ul {
        list-style: none;
    }
    .info_bar li {
        display: inline;
        padding-left: 2em;
    }

    #variety, #print_labels, #third_party, #grn_details, #hire {
        margin: 0;
        padding: 0;
    }

    #action_buttons input {
        margin-top: .5em;
        padding: .6em;
        width: 10em !important;
        font-size: 1.1em !important;
        text-transform: uppercase;
    }
</style>

<div id='grn-details' style="display: none;">

    <div id='grn-details-page1'>
        <div class="with_border info_bar">
            <ul>
                <li>Purchase Order: <span data-field-name = "PURCHASE_ORDER"></span></li>
                <li>GRN: <span data-field-name = "GRN"></span></li>
            </ul>
        </div>

    </div>

    <div id='grn-details-page2' style="display: none">
        <div class="with_border info_bar">
            <ul>
                <li>Purchase Order: <span data-field-name = "PURCHASE_ORDER"></span></li>
                <li>Line: <span data-field-name = "PO_LINE"></span>   </li>
            </ul>
        </div>
        <div style="font-weight: bold; border-top: medium none;" class="with_border">
        Product: <span data-field-name = "PROD_ID"></span> <span data-field-name = "SHORT_DESC"></span><br>
        Quantity required: <span data-field-name = "PO_LINE_QTY"></span></div>
        <table id="grn_details" class="with_border">
            <tbody><tr>
                <th><label for="carrier">Carrier *:</label></th>
                <td> <?php echo $this->formSelect('carrier', '', array(), $this->carriers);?></td>
                <th><label for="shipped_date">Shipped Date:</label></th>
                <td><input type="text" value="" id="shipped_date" name="shipped_date" class="hasDatepicker"></td>
            </tr>
            <tr>
                <th><label for="vehicle_id">Vehicle Reg.:</label></th>
                <td><input type="text" value="" id="vehicle_id" name="vehicle_id"></td>
                <th><label for="container_no">Shipping Cont. #:</label></th>
                <td><input type="text" value="" id="container_no" name="container_no"></td>
            </tr>
            <tr>
                <th><label for="awb_consignment_no">Connote/AWB #:</label></th>
                <td><input type="text" value="" id="awb_consignment_no" name="awb_consignment_no"></td>
                <th><label for="receipt_flag">Visible Damages:</label></th>
                <td><input type="checkbox" value="Y" id="receipt_flag" name="receipt_flag"></td>
            </tr>
        </tbody></table>
        <table style="display: none;" id="hire" class="with_border">
            <tbody><tr>
                <th><label for="pallets_yn">Hire Pallets:</label></th>
                <td><select id="pallets_yn" name="pallets_yn">
            <option selected="selected" label="CHEP (C)" value="C">CHEP (C)</option>
            <option label="Loscam (L)" value="L">Loscam (L)</option>
            <option label="None (N)" value="N">None (N)</option>
            <option label="Own Pallets (O)" value="O">Own Pallets (O)</option>
            <option label="Unknown (U)" value="U">Unknown (U)</option>
        </select></td>
                <th><label for="grn_pallet_qty">Total Pallets:</label></th>
                <td><input type="text" value="0" id="grn_pallet_qty" name="grn_pallet_qty"></td>
            </tr>
            <tr>
                <th><label for="pack_crate_owner">Hire Packaging:</label></th>
                <td><select id="pack_crate_owner" name="pack_crate_owner">
            <option selected="selected" label="CHEP (C)" value="C">CHEP (C)</option>
            <option label="Loscam (L)" value="L">Loscam (L)</option>
            <option label="None (N)" value="N">None (N)</option>
            <option label="Own (O)" value="O">Own (O)</option>
            <option label="Unknown (U)" value="U">Unknown (U)</option>
        </select></td>
                <th><label for="pack_crate_qty">Total Packaging:</label></th>
                <td><input type="text" value="0" id="pack_crate_qty" name="pack_crate_qty"></td>
            </tr>
            <tr>
                <th><label for="pack_crate_type">Packaging Type:</label></th>
                <td><select id="pack_crate_type" name="pack_crate_type">
            <option label="Carton, Corrugated Card Board (CC)" value="CC">Carton, Corrugated Card Board (CC)</option>
            <option label="Fold-down Crate - Size #1 (F1)" value="F1">Fold-down Crate - Size #1 (F1)</option>
            <option label="Fold-down Crate - Size #2 (F2)" value="F2">Fold-down Crate - Size #2 (F2)</option>
            <option label="Fold-down Crate - Size #3 (F3)" value="F3">Fold-down Crate - Size #3 (F3)</option>
            <option label="None (NO)" value="NO">None (NO)</option>
            <option label="Unknown (UN)" value="UN">Unknown (UN)</option>
        </select></td>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
            </tr>
        </tbody></table>

        <div id="action_buttons">
            <input type="submit" class="button" value="Accept" name="accept"><br>
            <input type="submit" class="button" value="Previous" name="previous"><br>
            <input type="submit" class="button" value="Cancel" name="cancel"><br>
        </div>
    </div>

    <div id='grn-details-page3' style="display: none">
        <div class="with_border info_bar">
            <ul>
                <li>Purchase Order: <span data-field-name = "PURCHASE_ORDER"></span></li>
                <li>Line: <span data-field-name = "PO_LINE"></span>   </li>
                <li>Product Code: <span data-field-name = "PROD_ID"></span>   </li>
                <li>Description: <span data-field-name = "SHORT_DESC"></span>   </li>
                <li>Inwards Consignment No: <span data-field-name = "GRN"></span></li>
            </ul>
        </div>
        
        <table id="grn_details" class="with_border">
            <tbody><tr>
                <th><label for="total_received_units">Total Received Units:</label></th>
                <td><input type="text" id="total_received_units" data-field-name = "PO_LINE_QTY" /></td>
                <th>Receive UoM:</th>
                <td>EA</td>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
    (function($){
        $.fn.minderGrnDetailsController = function(method) {
            if (typeof _methods[method] == 'function') {
                return _methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
            } else if (typeof method == 'object'){
                return _methods.init.apply(this, [method]);
            } else {
                $.error( 'Unsupported minderGrnDetailsController method "' +  method + '".' );
            }
        };

        var _fillData = function(data) {
            for (var i in data) {

                if (data[i])
                    this.find('[data-field-name="' + i + '"]').html(data[i]).val(data[i]);
                else
                    this.find('[data-field-name="' + i + '"]').html('&mdash;').val('');
            }

        };

        var _methods = {
            init: function() {
                var _this = this;
                this.find('input[name="previous"]').bind('click', function(evt) {
                    evt.preventDefault();
                    _this.trigger('previous-button-click');
                });

                this.find('input[name="cancel"]').bind('click', function(evt) {
                    evt.preventDefault();
                    _this.trigger('cancel-button-click');
                });

                this.find('input[name="accept"]').bind('click', function(evt) {
                    evt.preventDefault();

                    var event = $.Event('accept-button-click');
                    event.acceptDetails = _methods.getAcceptDetails.call(_this);

                    _this.trigger(event);
                });

                this.find('#total_received_units').change(function(evt){
                    evt.preventDefault();

                    var event = $.Event('total-received-change');
                    event.totalReceived = _methods.getTotalReceived.call(_this);

                    _this.trigger(event);
                });

                return this;
            },

            getTotalReceived: function() {
                return this.find('#total_received_units').val();
            },

            getAcceptDetails: function() {
                return {
                    'carrierId': this.find('[name="carrier"]').val(),
                    'vehicleRegistration': this.find('[name="vehicle_id"]').val(),
                    'conNoteNo': this.find('[name="awb_consignment_no"]').val(),
                    'shipDate': this.find('[name="shipped_date"]').val(),
                    'containerNo': this.find('[name="container_no"]').val(),
                    'receiptFlag': (this.find('[name="receipt_flag"]').attr('checked') ? 1 : 0)
                };
            },

            show: function(pageNo) {
                this.show();

                if (typeof pageNo != 'undefined')
                    _methods.showPage(pageNo);

                return this;
            },

            hide: function() {
                this.hide();
                return this;
            },

            fill: function(data) {
                if (data)
                    _fillData.call(this, data);
                this.find('#total_received_units').change();
                return this;
            },

            fillGrn: function(val) {
                if (!val) {
                    _methods.fill.call(this, {'GRN': '--'});
                } else {
                    _methods.fill.call(this, {'GRN': val});
                }
            },

            clear: function() {
                this.find('[data-field-name]').html('&mdash;');
                return this;
            },

            hideAllPages: function() {
                $('#grn-details-page1, #grn-details-page2, #grn-details-page3').hide();
            },

            showPage: function(pageNo) {
                _methods.hideAllPages();
                $('#grn-details-page' + pageNo).show();
                return this;
            }
        };
    })(jQuery);

    $('#grn-details').minderGrnDetailsController('init');
</script>
