<!-- confirm carriers dialog -->
<div style="display: none;" id="confirm_data_identifier_dialog" title="Select Data Identifier" class="flora">
    <form action="#">
        <table align="center" style="margin: 5px 0px;" width="100%">
            <tr><th>
                Select Data Identifier type:
            </th></tr>
        </table>
        <table align="center" style="margin: 5px 0px;" width="100%" class="data-identifier-list">
        </table>
    </form>
</div>
<!-- confirm carriers dialog -->
