<!-- confirm carriers dialog -->
<div style="display: none;" id="confirm_data_identifier_dialog" title="Select Data Identifier" class="flora">
    <form action="#">
        <h3>Select Data Identifier type:</h3>

        <div class="data-identifier-list-container">
            <table align="center" style="margin: 5px 0px;" width="100%" class="data-identifier-list tablesorter"></table>
        </div>
    </form>
</div>
<!-- confirm carriers dialog -->
