<?php echo $this->render('header.phtml'); ?>
<?php
    $attributes = array('autocomplete' => 'off', 'onkeyup' => 'checkKeys(event)');
    //$attributesForSelect = array('onchange'=>'seek_changed(this.name)');
    $attributesForSelect = array();
?>
<form name="main" id="main" action="<?php echo $this->url(array('module'     => 'warehouse',
                                          'controller' => 'issn',
                                          'action'     => 'index'))?>" method="post">
    <h2><?php echo $this->pageTitle; ?></h2>
    <ul class="toolbar">
        <li>
            <table>
                <tr>
                    <th class="rightalign"><label for='product_id_srch'>Product #&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formText('product_id',
                                                 selectFilterValue('product_id', $this->conditions),
                                                 $attributes);
                        ?>
                    </td>
                    <th class="rightalign"><label for='location_id'>Location ID&nbsp;</label></th>
                    <td>
                        <?php
                             echo $this->formText('location_id',
                                                  selectFilterValue('location_id', $this->conditions),
                                                  $attributes);
                        ?>
                    </td>
                <th class="rightalign"><label for='status'>Status&nbsp;</label></th>
                <td><?php echo $this->formSelectStrict('status', selectFilterValue('status', $this->conditions), $attributesForSelect, $this->statusList);?></td>
            </tr>
            <tr>
                <th class="rightalign"><label for='company_id'>Company ID&nbsp;</label></th>
                <td><?php echo $this->formText('company_id', selectFilterValue('company_id', $this->conditions), $attributes);?></td>
                <th class="rightalign"><label for='issn_no'>ISSN #&nbsp;</label></th>
                <td><?php echo $this->formText('issn_no', selectFilterValue('issn_no', $this->conditions), $attributes);?></td>
                <th class="rightalign"><label for='original_ssn'>Original SSN&nbsp;</label></th>
                <td><?php echo $this->formText('original_ssn', selectFilterValue('original_ssn', $this->conditions), $attributes);?></td>
            </tr>
            <tr>
                <th class="rightalign"><label for='supplier_id'>Supplier ID&nbsp;</label></th>
                <td><?php echo $this->formSelectStrict('supplier_id', selectFilterValue('supplier_id', $this->conditions), $attributesForSelect, $this->supplierIdList);?></td>
                <th class="rightalign"><label for='other_1'><?php echo $this->other1Name; ?>&nbsp;</label></th>
                <td><?php echo $this->formText('other_1', selectFilterValue('other_1', $this->conditions), $attributes);?></td>
                <th class="rightalign"><label for='other_2'><?php echo $this->other2Name; ?>&nbsp;</label></th>
                <td><?php echo $this->formText('other_2', selectFilterValue('other_2', $this->conditions), $attributes);?></td>
            </tr>
            <tr>
                <th class="rightalign"><label for='ssn_type'><?php echo $this->minder->getLabelName('ISSN', 'SSN_TYPE'); ?>&nbsp;</label></th>
                <td><?php echo $this->formSelectStrict('ssn_type', selectFilterValue('ssn_type', $this->conditions), array('onchange' => 'updateSsnTypeII()'), $this->ssnTypeList);?></td>
                <th class="rightalign"><label for='variety'><?php echo $this->minder->getLabelName('ISSN', 'GENERIC'); ?>&nbsp;</label></th>
                <td><?php echo $this->formSelectStrict('variety', selectFilterValue('variety', $this->conditions), $attributesForSelect, $this->varietyList);?></td>
                <th class="rightalign"><label for='brand'><?php echo $this->minder->getLabelName('ISSN', 'BRAND'); ?>&nbsp;</label></th>
                <td><?php echo $this->formSelectStrict('brand', selectFilterValue('brand', $this->conditions), $attributesForSelect, $this->brandList);?></td>
            </tr>
            <tr>
                <th class="rightalign"><label for='pick_label_no'>Pick Label #&nbsp;</label></th>
                <td colspan="5"><?php echo $this->formText('pick_label_no', selectFilterValue('pick_label_no', $this->conditions)) ?></td>
            </tr>
            </table>
        </li>
        </ul>
        <?php echo $this->formSubmit('action', 'SEARCH', array('onclick' => 'goSearch()')); ?> <?php echo $this->formSubmit('action', 'CLEAR', array('onclick' => 'return frmClear()')) ?>
        <hr />
        <ul class="toolbar">
        <li><input name="action" id="action" type="submit" value="MASS UPDATE"/></li>
        <li>Product ID: <?php echo $this->formText('mass_product_id', '', array()); ?></li>
        <li>Company ID: <?php echo $this->formText('mass_company_id', '', array()); ?></li>
        </ul>
        <hr />
    <div id="tabs">
        <div style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <table style="width:99%">
                <tr>
                    <td>
                        <div style="float:left;">
                            <b>
                                Selected: <span  id="selected_num">0</span>
                            </b>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div style="display:inline">
            <label for='show_by'>View By : </label>
            <?php echo $this->formSelect('show_by',
                                         $this->navigation['show_by'],
                                         array('onchange' => 'frmSubmit()'),
                                         array(  5 => 5,
                                                10 => 10,
                                                15 => 15,
                                                20 => 20,
                                                30 => 30,
                                                40 => 40,
                                                50 => 50,
                                               100 => 100));?>
            <label for='page'>Page : </label>
            <?php echo $this->formSelectStrict('pageselector',
                                               $this->navigation['pageselector'],
                                               array('onchange' => 'frmSubmit()'),
                                               $this->pages); ?>
        </div>
        <table id="<?php echo $this->escape($this->tableId) ?>" class="withborder tablesorter" style="width:99%">
            <thead>
            <tr>
            <th>
            <?php echo $this->formCheckbox('select_all',
                                           'any_value',
                                           array('onclick' => 'selectAll(this)'));?>
            </th>
<?php
    foreach ($this->headers as $key => $header) {
        echo '<th abbr="' . $this->escape($key) . '">' . $this->escape($header) . '</th>';
    }
?>
            </tr>
            </thead>
            <tbody>
<?php
    if (count($this->issns) > 0) {
        for ($i = 0; $i < count($this->issns); $i++) {
            $line = $this->issns[$i];
            echo '<tr>';
            echo '<th>';
            echo $this->formCheckbox($this->escape($line->id),
                                     $this->escape($line->id),
                                     array('class' => 'issn_checkbox',
                                           'id' => $this->escape($line->id),
                                           'checked' => selectFilterValue($this->escape($line->id), $this->conditions),
                                           "onclick" => "showSelected(this, '" . $this->escape($line->id) . "')"));
            echo '</th>';
            foreach($this->headers as $propertyName => $v) {
                    $val = $line->items[$propertyName];
                    $urlEdit = $this->url(array('module'      => 'warehouse',
                                                'controller'  => 'issn',
                                                'action'      => 'edit'),
                                                '',
                                                true);
                    echo '<td><a href="'. $urlEdit .'/edit_issn_ssn_id/'.$line->id.'" >'. $this->escape($val) . '</a></td>'."\n";
            }
            echo "</tr>\n";
        }
    } else {
        // for tablesorter JavaScript plugin (if no row & cols in table - error occurs).
        echo "<tr><th/>";
        foreach($this->headers as $propertyName => $v) {
            echo '<td/>';
        }
        echo "</tr>\n";
    }
?>
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <li id='rec_counter' style="display: inline;">
                <div id='num_rec'>Total
                    <?php echo $this->numRecords . " records. "; ?>
                    <?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); ?>
                    <?php echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno); ?>
                </div>
            </li>
        </ul>
    </div>
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: TXT', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: CSV', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XML', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XLS', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'RE-PACK', array('onclick' => 'return frmSubmit();'))?>
        </li>
<?php if (false) { ?>
        <li>
            <?php echo $this->formSubmit('action', 'RE-SORT', array('onclick' => 'return frmSubmit();'))?>
        </li>
<?php } ?>
        <li>
            <?php echo $this->formSubmit('action', 'PRINT LABEL', array('onclick' => 'return printIssn();'))?>
        </li>
    </ul>
    <div id="filter" style="display:none">
        <input type="checkbox" name="mass_action" id="mass_action">
        <input type="checkbox" name="search_action" id="search_action">
        <input type="text" value="" name="edit_issn_ssn_id" id="edit_issn_ssn_id">
    </div>
</form>

<script type="text/javascript">
var checkOnOff;
var formUrl='';
var cacheValue = 50;
$(document).ready(function () {
        $.ajaxSetup({async:false,
                     complete: onAjaxSuccess,
                     error: onAjaxError,
                     beforeSend: onAjaxBeforeSend});
    $('#table').tablesorter({headers: {0: {sorter:false}},sortList:[[1,1]], widgets: ['zebra']});
    $('#table').dragCols({
        'drop': savePosition,
        'params': ['<?php echo $this->url(array('module'    => 'warehouse',
                                               'controller' => 'settings',
                                               'action'     => 'save-position')) ?>', 'issn', 'index']
    });
    $("#tabs #select_complete").bind("click", selectWholeTable);
    showSelected($("#table #select_all").get(0), "init");

    $('#product_id').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                    'controller' => 'issn',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'product_id'},
                                     onItemSelect: productIdUpdate});
    $('#mass_product_id').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                    'controller' => 'issn',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'product_id'}});
    $('#issn_no').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                 'controller' => 'issn',
                                                                 'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'issn_no'},
                                     onItemSelect: issnNoUpdate});
    $('#original_ssn').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                 'controller' => 'issn',
                                                                 'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'original_ssn'},
                                     onItemSelect: originalSsnUpdate});
    $('#other_1').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                 'controller' => 'issn',
                                                                 'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'other_1'},
                                     onItemSelect: other1Update});
    $('#other_2').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                 'controller' => 'issn',
                                                                 'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'other_2'},
                                     onItemSelect: other2Update});
    $('#company_id').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                    'controller' => 'issn',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'company_id'},
                                     onItemSelect: companyIdUpdate});
    $('#mass_company_id').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                    'controller' => 'issn',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'mass_company_id'}});
    $('#location_id').autocomplete('<?php echo $this->url(array('module'     => 'warehouse',
                                                                    'controller' => 'issn',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'location_id'},
                                     onItemSelect: locationIdUpdate});

});

function formatItemWithoutDesc(ele)
{
    return ele[1];
}
function formatItemWithDesc(ele)
{
    return '<b>'+ele[0]+'</b><br/><i>'+ele[1]+'</i>';
}
function locationIdUpdate(item) {
}
function productIdUpdate(item) {
}
function issnNoUpdate(item) {
}
function companyIdUpdate(item) {
}
function originalSsnUpdate(item) {
}
function other1Update(item) {
}
function other2Update(item) {
}

function printIssn()
{
    $.getJSON('<?php echo $this->url(array('action' => 'issn-print', 'controller' => 'printer', 'module' => 'default')); ?>/',
           {cnt: 'issn',
           act: 'index',
           prn: $('#limit_printer')[0].value},
           function (result)
           {
               var answer = eval(result);
               alert(answer.message);
           });
    return false;
}

function frmClear()
{
    $('input:text').each(function() {
        this.value = '';
        });
    $('form select').each(function() {
        if (this.id != 'show_by' && this.id != 'pageselector') {
            this.selectedIndex = 0;
        }
        });
    return false;
}
function seek_changed()
{
    //frmSubmit();
}

function selectWholeTable()
{
    var chk = $('table input:checkbox', '#' + $(this).parent().parent()[0].id);
    var checkOnOff = this.checked;
    for (i=0; i < chk.length; i++) {
        chk[i].checked = checkOnOff;
    }
    calcOther(this, $($(this).parent().parent()[0]));
    return true;
}

function calcOther(element, method)
{
    var countEl = 0;
    if ('auto' == method) {
        var container_id = '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = element.checked;
    } else if ('init' == method) {
        var container_id =  '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = 'init';
    } else {
        var container_id = '#' + $('#' + method)[0].id;
        var method = element.checked;
    }
    $.getJSON('<?php echo $this->url(array('action' => 'calc', 'controller' => 'issn', 'module' => 'warehouse')); ?>',
             { field: 'QTY',
               inAction: '<?php echo 'index'; ?>',
               activeTab: container_id,
               method: method,
               id: element.id,
               value: element.value }, function(json) {
                   var answer = eval(json);
                   $("#selected_num", container_id).text(answer.selected_num);
               });
}

function limitChanged()
{
    frmSubmit();
    return true;
}

function checkKeys(e)
{
    if (e.keyCode == 13) {
        frmSubmit();
    }
    return true;
}
/*function goMassUpdate()
{
    document.getElementById('mass_action').checked = true;
    frmSubmit();
    return true;
}*/
function goSearch()
{
    document.getElementById('search_action').checked = true;
    frmSubmit();
    return true;
}
function goEdit(name)
{
    document.getElementById('edit_issn_ssn_id').value = name;
    frmSubmit();
    return false;
}
<?php
$url = $this->url(array('module'     => 'warehouse',
                        'controller' => 'issn',
                        'action'     => 'seek'));
?>
function updateSsnTypeII()
{
    $.ajax(
           {
            type: "GET",
            url: "<?php echo $url; ?>",
            cache: false,
            data: {
                   field:     "variety",
                   ssn_type: $("#ssn_type").get(0).value
            },
            success: function (data) {
                $("#variety").get(0).length = 0;
                var options = eval('(' + data + ')');
                var i = 0;
                $("#variety").get(0).options[i] = new Option('', '');
                for (var key in options) {
                    i++;
                    var newOpt = new Option(options[key], key);
                    $("#variety").get(0).options[i] = newOpt;
                }
            },
            error: function () {
                alert("Try again");
            }
           }
          );
}
</script>
<?php echo $this->render('footer.phtml');
