<?php

class PDF extends FPDF
{
    
var $B;
var $I;
var $U;
var $HREF;
var $pheader = '';
var $theader = array();
var $pfooter = '';
var $cellwidth;
var $currentRow = 0;
var $currentRowInTable = 0;

function PDF($orientation='P', $unit='mm', $format='A4')
{
    //Call parent constructor
    $this->FPDF($orientation, $unit, $format);
    //Initialization
    $this->B=0;
    $this->I=0;
    $this->U=0;
    $this->HREF='';
}

function Header()
{
    if ($this->pheader != '') {
        $this->WriteHTML($this->pheader);
        $this->WriteHTML("<BR>");
    }
    //Colors, line width and bold font
    $this->SetFillColor(177,219,135);
    $this->SetTextColor(255);
    $this->SetDrawColor(128,0,0);
    $this->SetLineWidth(.1);
    $this->SetFont('','B');
    //Header

    for($i=0;$i<count($this->theader);$i++)
        $this->Cell($this->cellwidth[$i],7,$this->theader[$i],1,0,'C',1);
    $this->Ln();
}

function Footer()
{
    //Colors, line width and bold font
    $this->SetFillColor(177,219,135);
    $this->SetTextColor(255);
    $this->SetDrawColor(128,0,0);
    $this->SetLineWidth(.1);
    $this->SetFont('','B');
    //Header

    for($i=0;$i<count($this->theader);$i++)
        $this->Cell($this->cellwidth[$i],7,$this->theader[$i],1,0,'C',1);
    $this->Ln();
    $this->SetFillColor(224,235,255);
    $this->SetTextColor(0);
    $this->SetLineWidth(.1);
    $this->SetFont('');
    
    $f = "from " . ($this->currentRowInTable - $this->currentRow + 1) .  " to " . $this->currentRowInTable;
    //$this->Cell(0, 0, $f, 0, 0, "L", false );
    $this->WriteHTML($f);
    $this->Ln();
    if ($this->pfooter != '') {
        $this->WriteHTML($this->pfooter);
        $this->Ln();
    }
    $this->currentRow = 0;
}

function WriteHTML($html)
{
    //HTML parser
    $html=str_replace("\n",' ',$html);
    $a=preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
    foreach($a as $i=>$e)
    {
        if($i%2==0)
        {
            //Text
            if($this->HREF)
                $this->PutLink($this->HREF,$e);
            else
                $this->Write(5,$e);
        }
        else
        {
            //Tag
            if($e{0}=='/')
                $this->CloseTag(strtoupper(substr($e,1)));
            else
            {
                //Extract attributes
                $a2=explode(' ',$e);
                $tag=strtoupper(array_shift($a2));
                $attr=array();
                foreach($a2 as $v)
                    if(ereg('^([^=]*)=["\']?([^"\']*)["\']?$',$v,$a3))
                        $attr[strtoupper($a3[1])]=$a3[2];
                $this->OpenTag($tag,$attr);
            }
        }
    }
}

function OpenTag($tag,$attr)
{
    //Opening tag
    if($tag=='B' or $tag=='I' or $tag=='U')
        $this->SetStyle($tag,true);
    if($tag=='A')
        $this->HREF=$attr['HREF'];
    if($tag=='BR')
        $this->Ln(5);
}

function CloseTag($tag)
{
    //Closing tag
    if($tag=='B' or $tag=='I' or $tag=='U')
        $this->SetStyle($tag,false);
    if($tag=='A')
        $this->HREF='';
}

function SetStyle($tag,$enable)
{
    //Modify style and select corresponding font
    $this->$tag+=($enable ? 1 : -1);
    $style='';
    foreach(array('B','I','U') as $s)
        if($this->$s>0)
            $style.=$s;
    $this->SetFont('',$style);
}    

//Colored table
function FancyTable($header,$data, $w)
{
    //Color and font restoration
    $this->SetFillColor(224,235,255);
    $this->SetTextColor(0);
    $this->SetLineWidth(.1);
    $this->SetFont('');
    //Data
    $fill=0;
    foreach($data as $row)
    {
        foreach ($row as $k => $v) {
            $this->Cell($w[$k], 6, $v, 1, 0, 'L', $fill);
        }
        $this->Ln();
        $fill=!$fill;
        $this->currentRow++;
        $this->currentRowInTable++;
    }
    $this->Cell(array_sum($w),0,'','T');
}
}
$header = $this->headers;
$data = array();
$width = array();

$pdf=new PDF('P', 'mm', array(297, 210));
$pdf->pheader = $this->reportHeader;
$pdf->theader = $this->headers;
$pdf->pfooter = $this->reportFooter;

$fontSize = 12;
$pdf->SetFont('Arial','',$fontSize);
$pdf->SetMargins(5,5,5);

$i = 0;
foreach ($header as $cell) {
    $w[$i] = $pdf->GetStringWidth($cell);
    $i++;
}

$wn = array();
foreach ($this->data as $row) {
    $newrow = array();
    $i = 0;
    foreach($row as $cell) {
        $newrow[] = $cell;
        if (isset($w[$i])) {
            if ($w[$i] < $pdf->GetStringWidth($cell)) {
                $w[$i] = $pdf->GetStringWidth($cell);
            }
        } else {
            $w[$i] = $pdf->GetStringWidth($cell);
        }
        $i++;
    }
    $data[] = $newrow;
}

$sumW = array_sum($w);
$ratio = $sumW / 287; // width - marginLeft - marginRight

foreach ($w as $k => $v) {
    $w[$k] = $v / $ratio;
     
}
$pdf->cellwidth = $w;
$fontratio = ($sumW + count($w) * 6) / 200;
$pdf->SetFont('Arial','',$fontSize / $fontratio);

$pdf->AddPage();
$pdf->FancyTable($header,$data, $w);
$pdf->Output();
