<form action="<?php echo $this->url(array('module' => 'default', 'controller' => 'connote'), null, true); ?>" method="post" id="despatch_form">
<input type="hidden" id="entered_pack_qty" value='0' />
<input type="hidden" id="entered_cartons_qty" value="0" />
<input type="hidden" id="entered_pallets_qty" value="0" />
<input type="hidden" id="entered_satchels_qty" value="0" />
<div>
 <table >
          <tr>
            <td>
            <table border=1>
                <tr>
                    <td>
                        <b>DESPATCH TO:</b> 
                    </td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('firstName', $this->firstName, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('lastName', $this->lastName, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                 <tr>
                    <td><?php echo $this->formText('addresLine1', $this->addresLine1, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('addresLine2', $this->addresLine2, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('dCity', $this->dCity, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('dState', $this->dState, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('dCountry', $this->dCountry, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('contactName', $this->contactName, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('dPhone', $this->dPhone, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formText('customerPoWo', $this->customerPoWo, array('disabled' => 'disabled', 'style' => 'width:56ex')); ?></td>
                </tr>
            </table>
            </td>
            <td>
                <table border=1>
                    <tr>
                        <td>
                            <b>INSTRUCTIONS:</b> 
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"><textarea name="specialInstructions1" cols="48" rows="10" disabled="disabled"><?php echo $this->specialInstructions1;  ?></textarea></td>
                    </tr>
                    <tr>
                        <td colspan="2"><textarea name="specialInstructions2" cols="48" rows="10" disabled="disabled"><?php echo $this->specialInstructions2;  ?></textarea></td>
                    </tr>
                    <tr>
                        <td>Despatch Type:</td>
                        <td><?php echo $this->formText('despatchType', $this->despatchType, array('disabled' => 'disabled', 'style' => 'width:41ex')); ?></td>
                    </tr>
                    <tr>
                        <td>Inclusions w/Order:</td>
                        <td><?php echo $this->formText('inclusionsOrder', $this->inclusionsOrder, array('disabled' => 'disabled', 'style' => 'width:41ex')); ?></td>
                    </tr>
                    <tr>
                        <td>Partial Pick:</td>
                        <td><?php echo $this->formText('partialPick', $this->partialPick, array('disabled' => 'disabled', 'style' => 'width:41ex')); ?></td>
                    </tr>
                    <tr>
                        <td>Invoice w/Order:</td>
                        <td><?php echo $this->formText('invoiceOrder', $this->invoiceOrder, array('disabled' => 'disabled', 'style' => 'width:41ex')); ?></td>
                    </tr>
                    
                </table> 
            </td>
          </tr>
          <tr>
              <table >
                <tr>
                    <td>
                        <b>SHIP VIA:</b> 
                    </td>
                </tr>
                <tr align="left">
                    <th>Consignment #:</th>
                    <td><?php echo $this->formText('consignment', $this->consignment, array('style' => 'width:36ex')); ?></td>
                    <th></th>
                    <td></td>
                </tr>
                <tr align="left">
                    <th>Carrier:</th>
                    <td><?php echo $this->formSelect('carrier', $this->carrier, array('style' => 'width:36ex'), $this->carrierList); ?></td>
                    <th>Carrier Service:</th>
                    <?php 
                        //should have at least empty option in select
                        $this->carrierServiceList = (empty($this->carrierServiceList)) ? array('' => '') : $this->carrierServiceList;
                    ?>
                    <td><?php echo $this->formSelect('carrierService', $this->carrierService, array('style' => 'width:38ex'), $this->carrierServiceList); ?></td>
                </tr>
                <tr>
                    <th>Payer:</th>
                    <td><?php echo $this->formSelect('payer', $this->payer, array('style' => 'width:36ex'), $this->payerList); ?></td>
                    <th>Account No:</th>
                    <td><?php echo $this->formText('accountNo', $this->accountNo, array('disabled' => 'disabled', 'style' => 'width:38ex')); ?></td>
                </tr>
                 <tr>
                    <th>Pallet Owner:</th>
                    <td><?php echo $this->formSelect('palletOwner', $this->palletOwner, array('style' => 'width:36ex'), $this->palletOwnerList); ?></td>
                    <th>Pallet Qty:</th>
                    <td><?php echo $this->formText('palletQty', $this->palletQty, array('disabled' => 'disabled', 'style' => 'width:38ex')); ?></td>
                </tr>
                <tr>
                    <th>Total Cartons:</th>
                    <td><?php echo $this->formText('totalCartons', $this->totalCartons, array('style' => 'width:36ex')); ?></td>
                    <th>Total Satchels:</th>
                    <td><?php echo $this->formText('totalSatchels', $this->totalSatchels, array('style' => 'width:38ex')); ?></td>
                </tr>
                <tr>
                    <th>Total Weight (kgs):</th>
                    <td><?php echo $this->formText('totalWeight', $this->totalWeight, array('style' => 'width:36ex', 'readonly' => 'readonly')); ?></td>
                    <th>Total Volume (cu m):</th>
                    <td><?php echo $this->formText('totalVolume', $this->totalVolume, array('style' => 'width:38ex', 'readonly' => 'readonly')); ?></td>
                </tr>
                <tr>
                    <th>Qty Address Labels:</th>
                    <td><?php echo $this->formText('qtyAddressLabels',  $this->qtyAddressLabels, array('style' => 'width:36ex')); ?></td>
                    <th>Print Address:</th>
                    <td><?php echo $this->formSelect('print_address_label', $this->printAddress, array('style' => 'width:38ex', 'onchange' => 'printAddressChange(this)'), $this->printAddressList); ?></td>
                </tr>
                <tr>
                    <th>Label Comment 1:</th>
                    <td><?php echo $this->formText('label_comment1', $this->remarks1, array('style' => 'width:36ex')); ?></td>
                    <th>Label Comment 2:</th>
                    <td><?php echo $this->formText('label_comment2', $this->remarks2, array('style' => 'width:38ex')); ?></td>
                </tr>
              </table>
          <tr>
       </table>
       <br /><br />
       
       <div id="PACK_DIMENSIONS_CONTROLLER">    
            <?php echo $this->render('/connote/pack-dimensions.phtml');?>
       </div>
       <br />
       <br />
       
       <ul class="toolbar" style="margin-top: 0; border-top: solid 1px #999;" id="edit_field_buttons">
        <li>
            <input type="button" class="order-button" name="action1" id="accept" value="ACCEPT" action_name="accept" />
        </li>
        <li>
            <input type="button" class="order-button" name="action1" id="connote_report_csv" value="REPORT: CSV" />
        </li>
        <li>
            <input type="button" class="order-button" name="action1" id="connote_report_xls" value="REPORT: XLS" />
        </li>
         <?php if(!is_null($this->minder->defaultControlValues['LEGACY_URL']) && !empty($this->minder->defaultControlValues['LEGACY_URL'])){ ?>
        <li>
            <input type="button" class="order-button" name="action1" id="get_address" value="GET ADDRESS" onclick="return openAddressDialog();" />
        </li>
        <?php } else { ?>
        <li>
            <input type="button" class="order-button" name="action1" id="report: xls" value="GET ADDRESS" onclick="return openAddressDialog();" disabled="disabled" />
        </li>
        <?php } ?>
        <li>
            <input type="button" class="order-button" name="action1" value="CANCEL" />
        </li>
        <li>
             <input type="button" class="order-button" name="action1" value="PRINT INVOICE" disabled="disabled" />
        </li>
        <li>
             <input type="button" class="order-button" name="action1" value="PRINT PACKING SLIP" disabled="disabled" />
        </li>
        <li>
             <input type="button" class="order-button" name="action1" value="PRINT ADDRESS" onclick="return printSelectedAddress();" />
        </li>
    </ul>
<div>
</form>

<div id="CARRIER_DESCRIPTION" style="display: none;">
    <!--static description for eampty CARRIER-->
    <select id="CR_DESC_" trn_type="" account="">
            <option value="" selected="selected"></option>
    </select>

    <?php foreach ($this->carrierDescription as $carrier) {?>
    <select id="CR_DESC_<?php echo strtoupper($carrier['CARRIER_ID']);?>" trn_type="<?php echo $carrier['TRN_TYPE'];?>" account="<?php echo $carrier['ACCOUNT'];?>">
        <?php foreach ($carrier['SEVICE_LIST'] as $serviceType => $serviceDesc) {?>
            <option value="<?php echo $serviceType;?>" <?php echo ((strtoupper($serviceType) == 'GEN')? 'selected="selected"' : ''); ?>><?php echo $serviceDesc; ?></option>
        <?php }?>
        
        <?php if (count($carrier['SEVICE_LIST']) < 1) { //should have at least one option?>
            <option value="" selected="selected"></option>
        <?php }?>
    </select>
    <?php }?>
</div>

<div id="get_address" class="flora" title="Get Contact Address" style="display: none;">
    <form id="" name="prompt" method="post" action="" enctype="multipart/form-data">
    <table class="summary" style="width:99%">
            <tr>
                <th>
                    ContactInstanceID:
                </th>
                <td>
                    <?php echo $this->formText('contact_instance_id', '', array()); ?>
                </td>
            </tr>
    </table>
    </form>
</div>

<div id="print_address" class="flora" title="Address data" style="display: none;">
    <form id="" name="prompt" method="post" action="" enctype="multipart/form-data">
    <table class="summary" style="width:99%">
            <tr>
                <th>
                    PERSON_ID:
                </th>
                <td>
                    <?php echo $this->formText('person_id', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    PERSON_TYPE:
                </th>
                <td>
                    <?php echo $this->formText('person_type', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    FIRST_NAME:
                </th>
                <td>
                    <?php echo $this->formText('first_name', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    LAST_NAME:
                </th>
                <td>
                    <?php echo $this->formText('last_name', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    CITY:
                </th>
                <td>
                    <?php echo $this->formText('city', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    STATE:
                </th>
                <td>
                    <?php echo $this->formText('state', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    POST_CODE:
                </th>
                <td>
                    <?php echo $this->formText('post_code', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    COUNTRY:
                </th>
                <td>
                    <?php echo $this->formText('country', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    PHONE:
                </th>
                <td>
                    <?php echo $this->formText('phone', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    ADDRESS_LINE1:
                </th>
                <td>
                    <?php echo $this->formText('address_line1', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    ADDRESS_LINE2:
                </th>
                <td>
                    <?php echo $this->formText('address_line2', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    ADDRESS_LINE3:
                </th>
                <td>
                    <?php echo $this->formText('address_line3', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    ADDRESS_LINE4:
                </th>
                <td>
                    <?php echo $this->formText('address_line4', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    ADDRESS_LINE5:
                </th>
                <td>
                    <?php echo $this->formText('address_line5', '', array()); ?>
                </td>
            </tr>
            <tr>
                <th>
                    TITLE:
                </th>
                <td>
                    <?php echo $this->formText('title', '', array()); ?>
                </td>
            </tr>
    </table>
    </form>
</div>

<div style="display: none;" id="CONNOTE_RESPONSE_CONTAINER"></div>                        
                                                                  
<script type="text/javascript">
    
    $(function() {
        initConnote();
    });
    
    function initConnote() {
        $.ajaxSetup({type: 'POST'});
        
        $('#PACK_DIMENSIONS_CONTROLLER').unbind('.connote').bind('totals-updated.connote', function(evt, data){
            $('#entered_pack_qty').val(data.totalPackages);
            $('#entered_cartons_qty').val(data.totalCartons);
            $('#entered_pallets_qty').val(data.totalPallets);
            $('#entered_satchels_qty').val(data.totalSatchels);
//            $('#qtyAddressLabels').val(data.totalLabels);

            $('#totalWeight').val(parseFloat(data.totalWeight).toFixed(3));
            $('#totalVolume').val(parseFloat(data.TotalVolume).toFixed(3));
        });
        updateTotals();
        
        $('#connote_report_csv, #connote_report_xls').unbind('.connote').bind('click.connote', printLinesAction);
    
        $('#payer').unbind('.connote').bind('change.connote', accountNoActivate).bind('change.connote', {update: 'account'}, onCarrierChange);
        $('#palletOwner').unbind('.connote').bind('change.connote', palletQtyActivate);
        $('#carrier').unbind('.connote').bind('change.connote', {update: 'all'}, onCarrierChange);
        
        $('#payer').trigger('change');
        $('#palletOwner').trigger('change');
        
        $('input[value=ACCEPT]').unbind('.connote').bind('click.connote', function(event){
            checkMandatoryFields(this);
        });
        
        $('#despatch_form').unbind('.connote').bind('submit.connote', function(event){
            checkMandatoryFields(this);
            event.preventDefault();
            return false;
        });
        
        
        $('#get_address').dialog({buttons: {Accept: getAddress, Cancel: closeAddressDialog},
             width: '60ex',
             height: '10em',
             autoOpen: false,
        
        }).unbind('.connote').bind('dialogopen.connote', function(event, ui) {
            $(this).show();
            
            var orderNo = $('#consignment').val()
                          $('#contact_instance_id').val(orderNo).focus();     
        });
        
        <?php if($this->minder->isAdmin) { ?>
            $('#print_address').dialog({buttons: {Save: savePrintAddressData, Close: closePrintAddressDialog},
                 width: '60ex',
                 height: '34em',
                 autoOpen: false
            
            }).unbind('.connote').bind('dialogopen.connote', function(event, ui) {
                $(this).show();     
            });
        <?php } else {?>
            $('#print_address').dialog({buttons: {Close: closePrintAddressDialog},
                 width: '60ex',
                 height: '34em',
                 autoOpen: false,
                 
            }).unbind('.connote').bind('dialogopen.connote', function(event, ui) {
                $(this).show();     
            });
        <?php } ?>
         
        $('#despatch_form input[value=CANCEL]').click(function(evt){
            evt.preventDefault();
            $('#despatch_form').trigger('cancel');
        });
        
        $('#despatch_form').undelegate('input, select', '.connote'); 
        $('#despatch_form').delegate('input, select', 'change.connote', function(){
            $(this).attr('old_value', $(this).val());
        });
        $('#despatch_form').delegate('input, select', 'keypress.connote', {fieldsScopeSel: ('#despatch_form input, #despatch_form select')}, moveNextOnEnter);
        $('#despatch_form').delegate('input, select', 'focus.connote', function(){
            $(this).attr('old_value', $(this).val());
        }).delegate('input, select', 'blur.connote', function(){
            if ($(this).attr('old_value') != $(this).val())
                $(this).trigger('change');
        });
        $('#consignment').focus();
         
    }
    
    function onCarrierChange(evt){
        var updateWhat = 'all';
        
        if (evt.data && evt.data.update) 
            updateWhat = evt.data.update;
            
        switch (updateWhat.toLowerCase()) {
            case 'account':
                $('#accountNo').val('');
                if ($('#payer').val().toUpperCase() == 'R') {
                    $('#accountNo').val($('#CARRIER_DESCRIPTION #CR_DESC_' + $('#carrier').val().toUpperCase()).attr('account'));
                }
                break;
            default:
                var carrierDesc = $('#CARRIER_DESCRIPTION #CR_DESC_' + $('#carrier').val().toUpperCase());

                $('#accountNo').val('');
                if ($('#payer').val().toUpperCase() == 'R') {
                    $('#accountNo').val(carrierDesc.attr('account'));
                }
                
                $('#despatchType').val('');
                $('#despatchType').val(carrierDesc.attr('trn_type'));
                $('#carrierService').html('');
                $('#carrierService').html(carrierDesc.html());
        }
    }
    
    function accountNoActivate() {
        var payer = $('#payer option:selected').val();
        
        if(payer == 'R') {
            $('#accountNo').removeAttr('disabled').removeAttr('style').css("width", "38ex");    
        } else {
            $('#accountNo').attr("disabled","disabled").css("background-color", "#EEEEEE").css("width", "38ex");
        }
    }
    
    function palletQtyActivate() {
        var palletOwner = $('#palletOwner option:selected').val();
        
        if(palletOwner != 'NONE') {
            $('#palletQty').removeAttr('disabled').removeAttr('style');
        } else {
            $('#palletQty').attr('disabled', 'disabled').css("background-color", "#EEEEEE");    
        } 
    }
    
    function checkMandatoryFields(target) {
        
        if (typeof(beforeConnoteAccept) == 'function') {
            if (!beforeConnoteAccept()) {
                return;
            }
        }
        
        var palletOwner     = $('#palletOwner').val();
        var totalPallets    = parseInt($('#palletQty').val());
        totalPallets        = (isNaN(totalPallets)) ? 0 : totalPallets;
        var totalCartons    = parseInt($('#totalCartons').val());
        totalCartons        = (isNaN(totalCartons)) ? 0 : totalCartons;
        var totalSatchels   = parseInt($('#totalSatchels').val());
        totalSatchels       = (isNaN(totalSatchels)) ? 0 : totalSatchels;

        var enteredPallets  = parseInt($('#entered_pallets_qty').val());
        enteredPallets      = (isNaN(enteredPallets)) ? 0 : enteredPallets;
        var enteredCartons  = parseInt($('#entered_cartons_qty').val());
        enteredCartons      = (isNaN(enteredCartons)) ? 0 : enteredCartons;
        var enteredSatchels = parseInt($('#entered_satchels_qty').val());
        enteredSatchels     = (isNaN(enteredSatchels)) ? 0 : enteredSatchels;
        var enteredPacksQty = parseInt($('#entered_pack_qty').val());
        enteredPacksQty     = (isNaN(enteredPacksQty)) ? 0 : enteredPacksQty;

        var totalWeight     = parseFloat($('#totalWeight').val());
        totalWeight         = (isNaN(totalWeight)) ? 0 : totalWeight;
        var totalVolume     = parseFloat($('#totalVolume').val());
        totalVolume         = (isNaN(totalVolume)) ? 0 : totalVolume;
        
        var consigmentNo    = $('#consignment').val();
        
        var errors = [];
        
        if (!consigmentNo) {
            errors.push('Enter "Consignment #'); 
        }
        
        if (palletOwner != 'NONE') {
            switch (true) {
                case (totalPallets < 1):
                    errors.push('Enter "Pallet Qty"');
                    break;
                case (totalPallets != enteredPallets):
                    errors.push('"Pallet Qty" (' + totalPallets  + ') does not match "Total Entered Pallets" (' + enteredPallets + ') ');
                    break;
            }
        }
        
        if (totalCartons != enteredCartons) {
            errors.push('"Total Cartons" (' + totalCartons  + ') does not match "Total Entered Cartons" (' + enteredCartons + ') ');
        }
        
        if (totalSatchels != enteredSatchels) {
            errors.push('"Total Satchels" (' + totalSatchels + ') does not match "Total Entered Satchels" (' + enteredSatchels + ') ');
        }
        
        if (enteredPacksQty < 1) {
            errors.push('"Overall Total Packages" shuld be greater then 0.');
        }
        
        if (enteredPacksQty != totalCartons + totalSatchels + totalPallets) {
            errors.push('"Overall Total Packages" (' + enteredPacksQty + ') does not match "Pallet Qty" + "Total Cartons" + "Total Satchels" (' + (totalCartons + totalSatchels + totalPallets) + ') .');
        }
        
        if (totalWeight === 0 && totalVolume === 0) {
            errors.push('Enter "Weight" or "Volume" information.');
        }
        
        if (errors.length > 0) {
            showErrors(errors, 10000, '#despatch_form');
        } else {
            submitAcceptRequest();
        }
        
//        if(consigmentNo != '') {
//            if((!isNaN(totalWeight) && !isNaN(totalVolume)) ||
//               (!isNaN(totalWeight) && isNaN(totalVolume)) ||
//               (isNaN(totalWeight) && !isNaN(totalVolume))) {
//                
//                if((!isNaN(totalCartons) && !isNaN(totalSatchels)) ||
//                   (!isNaN(totalCartons) && isNaN(totalSatchels)) ||
//                   (isNaN(totalCartons) && !isNaN(totalSatchels))) {
//                       
//                        submitAcceptRequest();
//                                          
//                } else {
//                    alert('Enter "Total Cartons" or "Total Satchels", "Total Weight" or "Total Vaolume" and "Qty Address Labels"');
//                }
//                          
//            } else {
//                alert('Enter "Total Cartons" or "Total Satchels", "Total Weight" or "Total Vaolume" and "Qty Address Labels"'); 
//            }
//        } else {
//            alert('Enter "Consignment #');
//        }
        
        return false;
    }
    
    function openAddressDialog(){
        $("#get_address").dialog("open");

        return false;      
    }
    
    function closeAddressDialog(){
        $('#get_address').dialog("close");
        
        return false;  
    }
    
    function getAddress(){
        
        var orderNo =   $('#contact_instance_id').val();
        
        if(orderNo != ''){
            
            $.getJSON('<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'get-address'), '', false); ?>', 
            {
               action1: 'GET ADDRESS', 
               contact_instance_id: orderNo
            }
            , function(json){
                           
               }
            );
            closeAddressDialog();        
        
        } else {
            $('#contact_instance_id').focus();    
        }   
    }
    
    
    function savePrintAddressData(){
        
        var data = {
           instance_id:     '<?php echo $this->instanceId;?>', 
           action1:         'SAVE_ADDRESS_DATA',
           field_name:      $('#print_address_label :selected').val(),
   
           person_id:       $('#person_id').val(),
           person_type:     $('#person_type').val(),
           first_name:      $('#first_name').val(),
           last_name:       $('#last_name').val(),
           city:            $('#city').val(),
           state:           $('#state').val(), 
           post_code:       $('#post_code').val(),
           country:         $('#country').val(),
           phone:           $('#phone').val(),
           address_line1:   $('#address_line1').val(),
           address_line2:   $('#address_line2').val(),
           address_line3:   $('#address_line3').val(),
           address_line4:   $('#address_line4').val(),
           address_line5:   $('#address_line5').val(),
           title:           $('#title').val()
           
        };
        
        $.getJSON(
            '<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'save-address-data'), '', false); ?>', 
            data, 
            function(json){
                $("#print_address").dialog("close");
                
                if(json.result){
                    showMessage(['Order data updated successfully.']);    

                    $('#firstName').val( (data.title) ? (data.title + ' '+ data.first_name + ' ' + data.last_name) : data.first_name );
                    $('#lastName').val( (data.title) ? '' : data.last_name );
                    $('#addresLine1').val(data.address_line1);
                    $('#addresLine2').val(data.address_line2);
                    $('#dCity').val(data.city);
                    $('#dState').val(data.state);
                    $('#dCountry').val( (data.country == 'AU') ? 'AUSTRALIA' : data.country );
                    $('#dPhone').val(data.phone);
                
                } else {
                    showErrors(['Error while update order data.']);    
                }           
           }
        );      
        
    }
    
    function closePrintAddressDialog(){
        $('#print_address').dialog("close");
        
        return false;     
    }
    
    function printAddressChange(target){
        
        var address =   $('#print_address_label :selected').val().toString().split('|');
        address = address[0];
        
        switch (address.toUpperCase()) {
            case 'DT':
            case 'MT':
            case 'OF':
            case 'OA':
                $.getJSON(
                    '<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'load-address-data', 'instance_id' => $this->instanceId), '', false); ?>', 
                    {
                        action1: 'LOAD_ADDRESS_DATA', 
                        field_name: $('#print_address_label :selected').val()
                    }, function(json){
                        $('#person_id').val(json.PERSON_ID);
                        if(json.type == 'DT'){
                            $('#person_type').attr("disabled","disabled");
                            $('#person_type').attr("style","background-color:#EEEEEE");
                        } else {
                            $('#person_type').removeAttr('disabled'); 
                            $('#person_type').removeAttr('style');
                        }
                        $('#first_name').val(json.FIRST_NAME);
                        $('#last_name').val(json.LAST_NAME);
                        $('#city').val(json.CITY);
                        $('#state').val(json.STATE);
                        $('#post_code').val(json.POST_CODE);
                        $('#country').val(json.COUNTRY);
                        $('#phone').val(json.PHONE);
                        $('#address_line1').val(json.ADDRESS_LINE1);
                        $('#address_line2').val(json.ADDRESS_LINE2);
                        $('#address_line3').val(json.ADDRESS_LINE3);
                        $('#address_line4').val(json.ADDRESS_LINE4);
                        $('#address_line5').val(json.ADDRESS_LINE5);
                        $('#title').val(json.TITLE);
                        
                        $('#firstName').val( (json.TITLE) ? (json.TITLE + ' '+ json.FIRST_NAME + ' ' + json.LAST_NAME) : json.FIRST_NAME );
                        $('#lastName').val( (json.TITLE) ? '' : json.LAST_NAME );
                        $('#addresLine1').val(json.ADDRESS_LINE1);
                        $('#addresLine2').val(json.ADDRESS_LINE2);
                        $('#dCity').val(json.CITY);
                        $('#dState').val(json.STATE);
                        $('#dCountry').val( (json.COUNTRY == 'AU') ? 'AUSTRALIA' : json.COUNTRY );
                        $('#contactName').val(json.CONTACT_NAME);
                        $('#dPhone').val(json.PHONE);
                        $('#customerPoWo').val(json.CUSTOMER_PO_WO);
                    
                        $("#print_address").dialog("open");           
                    }
                );
                break;
        } 
    }
    
    function clearFields(){
        $.each($('#print_address :input[type=text]'), function(){
            $(this).val('');
        })
    }
    
    function printSelectedAddress(){
        
        
        var address_data =  $('#print_address_label :selected').val();
        
        if (address_data == '') {
            showErrors(['Select "Print Address" first.']);
            return;
        }
        
        address_data =  address_data.split('|');
        address_type =  address_data[0];   
        label_name   =  address_data[1];
         
        
        $.getJSON('<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'print-address', 'instance_id' => $this->instanceId), '', false); ?>', 
        {
           action1:         'PRINT_ADDRESS', 
           address_type:    address_type, 
           label_name:      label_name
           
        }, function(json){
        
                if(json.result){
                    showMessage(['1 label printed successfully']);    
                } else {
                    showErrors([json.message]);    
                }
              
           }
        );
       
       return false; 
    }                                                
    
    function submitAcceptRequest() {
        var data = {
            //data for  DSOT / DSST transaction
            consignment      : $('#consignment').val(),       //ConNoteNo
            accountNo        : $('#accountNo').val(),         //AccountNo
            // orderId stored in session
            carrier          : $('#carrier').val(),           //carrierId
            palletQty        : $('#palletQty').val(),         //palletQty
            palletOwner      : $('#palletOwner').val(),       //palletOwnerId
            totalCartons     : $('#totalCartons').val(),      //cartonQty
            totalSatchels    : $('#totalSatchels').val(),     //satchelQty
            totalWeight      : $('#totalWeight').val(),       //totalWaight
            totalVolume      : $('#totalVolume').val(),       //totalVolume
            payer            : $('#payer').val(),             //payerFlag
            //TODO: labelType - need to find where it comes from?
            carrierService   : $('#carrierService').val(),    //serviceType
            //packType - not uses at present, setted to CONTROL.DEFAULT_CONNOTE_PACK at server side
            //printerId stored on server side
            qtyAddressLabels : $('#qtyAddressLabels').val(),  //labelQty
            label_comment1   : $('#label_comment1').val(),
            label_comment2   : $('#label_comment2').val()
        };
        
        if (typeof(getPakIdDimensions) == 'function') {
            data.dimentions = getPakIdDimensions();
        }
        
//        $.getJSON(
        $('#CONNOTE_RESPONSE_CONTAINER').load(
            '<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'accept', 'instance_id' => $this->instanceId), '', false);?>',
            data,
            function(text) {
                var response = $.parseJSON(text);
                $('#CONNOTE_RESPONSE_CONTAINER').html('');
                
                if (response.errors && response.errors.length > 0) {
                    showErrors(response.errors);
                    return;
                }
                
                if (response.messages && response.messages.length > 0) {
                    showMessage(response.messages);
                }
                
                if (response.success) {
                    location.href = '<?php echo $this->url(array('module' => 'default', 'controller' => 'connote', 'action' => 'success', 'instance_id' => $this->instanceId), '', false);?>';
                }
            }
        );
    }
    
    function destroyConnote() {
        $('#print_address').dialog('destroy').remove();
        $('#get_address').dialog('destroy').remove();
    }
    
</script>

