<form name="input" id="input" action="<?php echo $this->url(array('action' => 'show', 'controller' => 'reports', 'module' => 'default', 'report_id' => $this->report_id)); ?>" method="post">
    <input type="hidden" name="first_run" value="true" />
    <input type="hidden" name="report_id" value="<?php echo $this->report_id?>" />
    <table class="summary">
<?php
$javascript = array();
if (count($this->prompts) == 0) {
    echo "<h2>No input required. Press 'Go' to run Report</h2>";
} else {
    foreach($this->prompts as $obj) {
        echo "<tr>";
        switch ($obj->items['QUERY_PROMPT_TYPE']) {
            case 'D':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formText('id' . $obj->id);
                echo "</td>";
                $javascript[] = " $('#id" . $obj->id . "').datepicker({dateFormat: 'yy/mm/dd', beforeShow: function(){
                    var
                        \$datePicker = $('#datepicker_div'),
                        zIndex = getTopMostDialogZIndex() || parseInt(\$datePicker.css('z-index')) || 1000;

                    \$datePicker.css('z-index', zIndex + 2);
                    return {};
                }});";
                break;
            case 'A':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formText('id' . $obj->id);
                echo "</td>";
                $javascript[] = " $('#id" . $obj->id . "').datepicker({dateFormat: 'mm/dd/yy', beforeShow: function(){
                    var
                        \$datePicker = $('#datepicker_div'),
                        zIndex = getTopMostDialogZIndex() || parseInt(\$datePicker.css('z-index')) || 1000;

                    \$datePicker.css('z-index', zIndex + 2);
                    return {};
                }});";
                break;
            case 'L':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formCheckbox('id' . $obj->id);
                echo "</td>";
                break;
            case 'I':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formText('id' . $obj->id);
                echo "</td>";
                break;
            case 'C':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formText('id' . $obj->id);
                echo "</td>";
                break;
            case 'F':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formSelect('id' . $obj->id, '', array(), minder_array_merge(array('%' => 'All'),
                                                                                        $this->minder->getListByField($obj->items['QUERY_DB_FIELD'])));
                echo "</td>";
                break;
            case 'S':
                echo "<th>";
                echo $this->escape($obj->items['QUERY_PROMPT']);
                echo "</th>";
                echo "<td>";
                echo $this->formSelect('id' . $obj->id, '', array(), $this->minder->getDropDownList($obj->items['QUERY_DB_FIELD']));
                echo "</td>";
                break;
            default:
                break;
        }
        echo "</tr>";
    }
}
?>
    </table>
</form>
<script type="text/javascript">
<?php
    foreach ($javascript as $line) {
        echo $line;
    }
?>
</script>
