<!-- confirm carriers dialog -->
<div style="display: none;" id="confirm_despatch_dialog" title="Confirm Despatch" class="flora">
    <form action="#">
        <table align="center" style="margin: 5px 0px;" width="100%">
            <tr class="carrier-not-in-list"><td colspan="2">
                    Item(s) are not despatched.
                </td></tr>
            <tr><td colspan="2">
                    Scan 'ACCEPT' to complete despatch. Scan 'CANCEL' to continue search without despatching selected items.
                </td></tr>
        </table>
    </form>
</div>
<!-- confirm carriers dialog -->
