<!-- confirm carriers dialog -->
<div style="display: none;" id="confirm_carriers_dialog" title="Confirm Carrier" class="flora">
    <form action="#">
        <table align="center" style="margin: 5px 0px;" width="100%">
            <tr class="carrier-not-in-list"><td colspan="2">
                Selected Carrier ID = '<span class="selected-carrier-id"></span>' and not <span class="device-carriers-list"></span>.
            </td></tr>
            <tr class="carrier-not-same-as-order"><td colspan="2">
                This Order has Carrier ID = '<span class="order-carrier-id"></span>' but Selected Carrier ID = '<span class="selected-carrier-id"></span>'.
            </td></tr>
            <tr><td colspan="2">
                Scan 'CONTINUE' to continue...
            </td></tr>
        </table>
    </form>
</div>
<!-- confirm carriers dialog -->
