#!/bin/bash
#
# chkconfig: - 91 35
# description: Starts and stops bdcsprint. \
#	       used to provide label printing to known printers.

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:/opt/firebird/bin

prog=$"BDCS Print server"

start() {
    echo -n $"Starting $prog: "
    ulimit -S -c 0 >/dev/null 2>&1
    RETVAL=0
    NOSERV=1
	export USER="bdcs"
        myprog="/data/asset.rf/python/script/printSendFile.py"
        myopts="db=minder"
        runuser -l ${USER} -c "cd /tmp && python $myprog $myopts >printsendfl.log  2>&1 & "
        #cd /tmp && python $myprog > /tmp/printsendfl.log  2>&1 & 
        RETVAL=$?
        [ "$RETVAL" -ne 0 ] && break
        myprog2="/data/asset.rf/python/script/printCreateFile.py"
        runuser -l ${USER} -c "cd /tmp && python $myprog2 $myopts >printcreatefl.log  2>&1 & "
        #cd /tmp && python $myprog2 > /tmp/printcreatefl.log  2>&1 & 
        RETVAL=$?
    [ "$RETVAL" -eq 0 ] && touch /var/lock/subsys/bdcsprint
}

stop() {
    echo -n $"Shutting down $prog: "
    isql -u sysdba -p masterkey minder << EOF
execute procedure PRN_REQUEST_CP_STOP;
commit;
exit;
EOF
    isql -u sysdba -p masterkey minder << EOF
execute procedure PRN_REQUEST_NP_STOP;
commit;
exit;
EOF
    rm -f /var/lock/subsys/bdcsprint
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 3
	start
	;;
  status)
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

