<!-- change sent from dialog -->
<div style="display: none;" id="change-sent-from-dialog" title="Sent From Depot" class="flora">
    <form action="#" autocomplete="off">
        <table align="center" style="margin: 5px 0px;" width="100%">
            <tr>
                <th>
                    Carrier Service:
                </th>
                <td>
                    <select name="carrier-service"></select>
                </td>
            </tr>
        </table>
    </form>
</div>
<!-- change sent from dialog -->
