<?php
$invoiceToList = array('' => '');
$shipToList = array('' => '');

$costCentreList = array('' => '');
foreach ($this->minder->getCostCentreList() as $k => $v) {
    $costCentreList[$k] = $v;
}
?>
<form action="<?php echo $this->url(); ?>" method="post">
    <h1>New Transfer Order<?php echo $this->withLines ? ' (with lines)' : '' ?></h1>
    <input type="hidden" name="pick_order_type" value="<?php echo $this->escape($this->pickOrder->pickOrderType); ?>" />
    <div class="section" style="border-top: none;">
        <h2>General</h2>
        <table>
            <tr>
                <th>Status</th>
<?php if ($this->minder->isAdmin || $this->minder->isCreditManagerT()) : ?>
                <td><?php echo $this->formSelect('pick_status', $this->pickOrder->pickStatus, null, $this->minder->getPickOrderStatusList()) ?></td>
<?php else :  ?>
                <td><?php $l = $this->minder->getPickOrderStatusList(); echo $this->escape(isset($l[$this->pickOrder->pickStatus]) ? $l[$this->pickOrder->pickStatus] : $this->pickOrder->pickStatus); ?></td>
<?php endif; ?>
<?php if ($this->action == 'new') { ?>
                <th>Priority</th>
                <td><?php echo $this->formText('pick_priority', $this->pickOrder->pickPriority, array('class' => 'number', 'autocomplete' => 'off', 'tabindex' => '1', 'id' => 'edit_pick_priority')); ?></td>
<?php } else { ?>
                <th>&nbsp;</th>
                <td>&nbsp;</td>
<?php } ?>
            </tr>
        </table>
    </div>
    <div class="section">
        <h2>Transfer From</h2>
        <table>
            <tr>
                <th><label>Company</label></th>
                <td><?php echo $this->formSelect('company_id', $this->pickOrder->companyId, array('onchange' => 'suppliedFromSoldFromAddress()', 'tabindex' => '2', 'id' => 'edit_company_id'), $this->minder->getProductOwnerList()); ?></td>
                <th><label>Cost Centre</label></th>
                <td><?php echo $this->formSelect('cost_center', $this->pickOrder->costCenter, array('tabindex' => '4'), $costCentreList); ?></td>
            </tr>
            <tr>
                <th><label>Warehouse</label></th>
                <td><?php echo $this->formSelect('wh_id', $this->pickOrder->whId, array('tabindex' => '3'), $this->minder->getWarehouseList()); ?></td>
                <th></th>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="floats cl" style="padding-bottom: 1em;">
        <input type="submit" name="action" value="Save" class="fl" onclick="return dateCompare();" />
        <input type="submit" name="action" value="Cancel" class="fl" style="margin-left: 10px;" />
        <input type="button" value="Return -&gt; Top" class="fr" onclick="window.scrollTo(0, 0);" />
    </div>
<?php if (false) { ?>
    <div class="section">
        <h2>Supplied By</h2>
        <p><?php echo $this->formCheckbox('s_same_as_sold_from', $this->pickOrder->sSameAsSoldFrom, array('onclick' => 'suppliedFromSoldFromAddress()', 'tabindex' => '5')); ?> Same as sold from</p>
        <table>
            <tr>
                <th><label>Supplied By</label></th>
                <td><?php echo $this->formText('s_person_id', $this->pickOrder->sPersonId, array('autocomplete' => 'off', 'tabindex' => '6')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>First Name</label></th>
                <td><?php echo $this->formText('s_first_name', $this->pickOrder->sFirstName, array('autocomplete' => 'off', 'tabindex' => '7')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>Last Name</label></th>
                <td><?php echo $this->formText('s_last_name', $this->pickOrder->sLastName, array('autocomplete' => 'off', 'tabindex' => '8')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><h3>Supplied By Address</h3></th>
                <td><?php echo $this->formText('s_address_line1', $this->pickOrder->sAddressLine1, array('autocomplete' => 'off', 'tabindex' => '9')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <td><?php echo $this->formText('s_address_line2', $this->pickOrder->sAddressLine2, array('autocomplete' => 'off', 'tabindex' => '10')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>City</label></th>
                <td><?php echo $this->formText('s_city', $this->pickOrder->sCity, array('autocomplete' => 'off', 'tabindex' => '11')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>State</label></th>
                <td><?php echo $this->formText('s_state', $this->pickOrder->sState, array('autocomplete' => 'off', 'tabindex' => '12')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>Postcode</label></th>
                <td><?php echo $this->formText('s_post_code', $this->pickOrder->sPostCode, array('autocomplete' => 'off', 'tabindex' => '13')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>Country</label></th>
                <td><?php echo $this->formText('s_country', $this->pickOrder->sCountry, array('autocomplete' => 'off', 'tabindex' => '14')); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><label>Telephone</label></th>
                <td><?php echo $this->formText('s_phone', $this->pickOrder->sPhone, array('autocomplete' => 'off', 'tabindex' => '15')); ?></td>
                <th></th>
                <td></td>
            </tr>
        </table>
    </div>
<?php } ?>
    <div class="section">
        <table>
            <tr>
                <th colspan="2"><h2>Transfer To</h2></th>
                <th colspan="2"><h2>Deliver To</h2></th>
            </tr>
            <tr>
                <th><label>Invoice To</label></th>
                <td><?php echo $this->formText('person_id', $this->pickOrder->personId, array('autocomplete' => 'off', 'tabindex' => '16', 'id' => 'edit_person_id', 'class' => 'mandatory')); ?></td>
                <th><label>Order Reference</label></th>
                <td><?php echo $this->formText('customer_po_wo', $this->pickOrder->customerPoWo, array('autocomplete' => 'off', 'tabindex' => '18', 'id' => 'edit_customer_po_wo')); ?></td>
            </tr>
            <tr>
                <th><label>Contact</label></th>
                <td><?php echo $this->formText('contact_name', $this->pickOrder->contactName, array('autocomplete' => 'off', 'tabindex' => '17', 'id' => 'edit_contact_name')); ?></td>
                <th><label>Due Date:</label></th>
                <td><?php echo $this->formText('pick_due_date', $this->pickOrder->pickDueDate, array('autocomplete' => 'off', 'tabindex' => '19', 'id' => 'edit_pick_due_date')); ?></td>
            </tr>
            <tr>
                <th><label>Return After</label></th>
                <td>
                    <?php echo $this->formText('days', '', array('onchange' => 'return calcDate();', 'style' => 'width:6em;')) ?>
                    <?php echo $this->formSelect('loan_period', '', array('onchange' => 'return calcDate();', 'style' => 'width:9em;', 'id' => 'edit_loan_period'), $this->loanPeriodList); ?>
                </td>
                <th><label>Return Date:</label></th>
                <td><?php echo $this->formText('return_date', $this->pickOrder->returnDate, array('autocomplete' => 'off', 'id' => 'edit_return_date')); ?></td>
            </tr>
            <tr>
                <th><h3>Invoice Address</h3></th>
                <td></td>
                <th><h3>Shipping Address</h3></th>
                <td><?php echo $this->formCheckbox('p_same_as_invoice_to', $this->pickOrder->pSameAsInvoiceTo, array('onclick' => 'shipToInvoice()', 'tabindex' => '30')); ?> Same as invoice</td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->formSelect('invoice_to', '', array('onchange' => 'invoiceToSelected()', 'style' => 'width: 50ex', 'tabindex' => '20'), $invoiceToList); ?></td>
                <td colspan="2"><?php echo $this->formSelect('ship_to', '', array('onchange' => 'shipToSelected()', 'style' => 'width: 50ex', 'tabindex' => '31'), $shipToList); ?></td>
            </tr>
            <tr>
                <th><label>First Name</label></th>
                <td><?php echo $this->formText('p_first_name', $this->pickOrder->pFirstName, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '21', 'id' => 'edit_p_first_name')); ?></td>
                <th><label>First Name</label></th>
                <td><?php echo $this->formText('d_first_name', $this->pickOrder->dFirstName, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '32')); ?></td>
            </tr>
            <tr>
                <th><label>Last Name</label></th>
                <td><?php echo $this->formText('p_last_name', $this->pickOrder->pLastName, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '22')); ?></td>
                <th><label>Last Name</label></th>
                <td><?php echo $this->formText('d_last_name', $this->pickOrder->dLastName, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '33')); ?></td>
            </tr>
            <tr>
                <th><label>Address</label></th>
                <td><?php echo $this->formText('p_address_line1', $this->pickOrder->pAddressLine1, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '23')); ?></td>
                <th><label>Address</label></th>
                <td><?php echo $this->formText('d_address_line1', $this->pickOrder->dAddressLine1, array('autocomplete' => 'off', 'tabindex' => '34')); ?></td>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <td><?php echo $this->formText('p_address_line2', $this->pickOrder->pAddressLine2, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '24')); ?></td>
                <th>&nbsp;</th>
                <td><?php echo $this->formText('d_address_line2', $this->pickOrder->dAddressLine2, array('autocomplete' => 'off', 'tabindex' => '35')); ?></td>
            </tr>
            <tr>
                <th><label>City</label></th>
                <td><?php echo $this->formText('p_city', $this->pickOrder->pCity, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '25')); ?></td>
                <th><label>City</label></th>
                <td><?php echo $this->formText('d_city', $this->pickOrder->dCity, array('autocomplete' => 'off', 'tabindex' => '36', 'id' => 'edit_d_city')); ?></td>
            </tr>
            <tr>
                <th><label>State</label></th>
                <td><?php echo $this->formText('p_state', $this->pickOrder->pState, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '26')); ?></td>
                <th><label>State</label></th>
                <td><?php echo $this->formText('d_state', $this->pickOrder->dState, array('autocomplete' => 'off', 'tabindex' => '37', 'id' => 'edit_d_state')); ?></td>
            </tr>
            <tr>
                <th><label>Postcode</label></th>
                <td><?php echo $this->formText('p_post_code', $this->pickOrder->pPostCode, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '27')); ?></td>
                <th><label>Postcode</label></th>
                <td><?php echo $this->formText('d_post_code', $this->pickOrder->dPostCode, array('autocomplete' => 'off', 'tabindex' => '38')); ?></td>
            </tr>
            <tr>
                <th><label>Country</label></th>
                <td><?php echo $this->formText('p_country', $this->pickOrder->pCountry, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '28')); ?></td>
                <th><label>Country</label></th>
                <td><?php echo $this->formText('d_country', $this->pickOrder->dCountry, array('autocomplete' => 'off', 'tabindex' => '39', 'id' => 'edit_d_country')); ?></td>
            </tr>
            <tr>
                <th><label>Telephone</label></th>
                <td><?php echo $this->formText('p_phone', $this->pickOrder->pPhone, array('autocomplete' => 'off', 'onchange' => 'shipToInvoice()', 'tabindex' => '29')); ?></td>
                <th><label>Telephone</label></th>
                <td><?php echo $this->formText('d_phone', $this->pickOrder->dPhone, array('autocomplete' => 'off', 'tabindex' => '40')); ?></td>
            </tr>
        </table>
    </div>
    <div class="floats cl" style="padding-bottom: 1em;">
        <input type="submit" name="action" value="Save" class="fl" onclick="return dateCompare();" />
        <input type="submit" name="action" value="Cancel" class="fl" style="margin-left: 10px;" />
        <input type="button" value="Return -&gt; Top" class="fr" onclick="window.scrollTo(0, 0);" />
    </div>
    <div class="section cl">
        <h2>Shipping Information</h2>
        <table>
            <tr>
                <th><label>Ship Via</label></th>
                <td><?php echo $this->formSelect('ship_via', $this->pickOrder->shipVia, array('onchange' => 'shipViaChanged()', 'tabindex' => '41', 'id' => 'edit_ship_via'), $this->minder->getShipViaList()); ?></td>
                <th><label>Other Documents &amp; Inclusions</label></th>
                <td><?php echo $this->formCheckbox('supplier_list', $this->pickOrder->supplierList, array('tabindex' => '48')); ?></td>
            </tr>
            <tr>
                <th><label>Service</label></th>
                <td><?php echo $this->formSelect('ship_service', $this->pickOrder->shipService, array('tabindex' => '42'), $this->minder->getShipServiceList($this->pickOrder->shipVia)); ?></td>
                <th><label>Send Invoice with Goods</label></th>
                <td><?php echo $this->formCheckbox('inv_with_goods', $this->pickOrder->invWithGoods, array('tabindex' => '49')); ?></td>
            </tr>
            <tr>
                <th><label>Run #</label></th>
                <td><?php echo $this->formText('delivery_run_no', $this->pickOrder->deliveryRunNo, array('autocomplete' => 'off', 'tabindex' => '43')); ?></td>
                <th><label>Allow partial pick</label></th>
                <td><?php echo $this->formCheckbox('partial_pick_allowed', $this->pickOrder->partialPickAllowed, array('tabindex' => '50')); ?></td>
            </tr>
            <tr>
                <th><label>Despatch Location</label></th>
                <td><?php echo $this->formSelect('despatch_location', $this->pickOrder->despatchLocation, array('tabindex' => '44', 'id' => 'new_despatch_location'), $this->minder->getDespatchLocationList($this->pickOrder->whId)); ?></td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th><?php echo $this->formLabel('msds', 'Material Safety Data Sheet required', array('style' => 'border: 2px solid red;')); ?>
                </th>
                <td>
                    <?php echo $this->formCheckbox('po_material_safety_data', 'T', array()); ?>
                </td>
            </tr>
<?php if (false) { ?>
            <tr>
                <th><label>Despatch Location</label></th>
                <td><?php echo $this->formSelect('despatch_location', $this->pickOrder->despatchLocation, array('tabindex' => '44', 'id' => 'edit_despatch_location'), $this->minder->getDespatchLocationList($this->pickOrder->whId)); ?></td>
                <th><label>Export Category</label></th>
                <td><?php echo $this->formSelect('export_category', $this->pickOrder->exportCategory, array('tabindex' => '51'), $this->minder->getExportCategoryList()); ?></td>
            </tr>
            <tr>
                <th><label>Aust 4-State Barcode No</label></th>
                <td><?php echo $this->formText('p_aust_post_4state_id', $this->pickOrder->pAustPost4stateId, array('autocomplete' => 'off', 'tabindex' => '45')); ?></td>
                <th><label>Net Weight</label></th>
                <td><?php echo $this->formText('net_weight', $this->pickOrder->netWeight, array('autocomplete' => 'off', 'tabindex' => '52')); ?></td>
            </tr>
            <tr>
                <th><label>Oversize</label></th>
                <td><?php echo $this->formCheckbox('over_sized', $this->pickOrder->overSized,  array('tabindex' => '46')); ?></td>
                <th>Package Base</th>
                <td><?php echo $this->formSelect('pallet_base', $this->pickOrder->palletBase,  array('tabindex' => '53'), $this->minder->getPackageBaseList()); ?></td>
            </tr>
            <tr>
                <th>Oversize Reason</th>
                <td><?php echo $this->formText('over_sized_reason', $this->pickOrder->overSizedReason, array('autocomplete' => 'off', 'tabindex' => '47')); ?></td>
                <th></th>
                <td></td>
            </tr>
<?php } ?>
        </table>
    </div>
    <div class="section">
        <h2>Billing Information</h2>
        <table>
            <tr>
                <th></th>
                <td></td>
                <th>Sub Total</th>
                <td><?php echo $this->formText('sub_total_amount', $this->pickOrder->subTotalAmount, array('autocomplete' => 'off', 'readonly' => 'true', 'class' => 'number', 'tabindex' => '54')); ?><?php echo $this->formHidden('tax_sub_total', $this->pickOrder->taxSubTotal); ?></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <th>Freight</th>
                <td><?php echo $this->formText('freight', $this->pickOrder->freight, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '55')); ?></td>
            </tr>
            <tr>
                <th>Administration Fee (%)</th>
                <td><?php echo $this->formText('admin_fee_rate', $this->pickOrder->adminFeeRate, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '56')); ?></td>
                <th>Administration Fee ($)</th>
                <td><?php echo $this->formText('admin_fee_amount', $this->pickOrder->adminFeeAmount, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '57')); ?></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <th>Other Cost 1</th>
                <td><?php echo $this->formText('other_num1', $this->pickOrder->otherNum1, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '58')); ?></td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <th>Other Cost 2</th>
                <td><?php echo $this->formText('other_num2', $this->pickOrder->otherNum2, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '59')); ?></td>
            </tr>
            <tr>
                <th>Tax (%)</th>
                <td><?php echo $this->formText('tax_rate', $this->pickOrder->taxRate, array('autocomplete' => 'off', 'readonly' => 'true', 'class' => 'number', 'tabindex' => '60')); ?></td>
                <th>Tax ($)</th>
                <td><?php echo $this->formText('tax_amount', $this->pickOrder->taxAmount, array('autocomplete' => 'off', 'readonly' => 'true', 'class' => 'number', 'tabindex' => '61')); ?></td>
            </tr>
            <tr>
                <th><label>Payment Method</label></th>
                <td><?php echo $this->formSelect('payment_method', $this->pickOrder->paymentMethod, array('tabindex' => '62'), $this->paymentMethodList); ?></td>
                <th>Deposit Received</th>
                <td><?php echo $this->formText('amount_paid', $this->pickOrder->amountPaid, array('autocomplete' => 'off', 'class' => 'number', 'onchange' => 'recalculateTotal()', 'tabindex' => '63')); ?></td>
            </tr>
            <tr>
                <th><label>Terms</label></th>
                <td><?php echo $this->formSelect('terms', $this->pickOrder->terms, array('tabindex' => '64'), $this->paymentTermsList); ?></td>
                <th>Amount Due</th>
                <td><?php echo $this->formText('due_amount', $this->pickOrder->dueAmount, array('autocomplete' => 'off', 'readonly' => 'true', 'class' => 'number', 'tabindex' => '65')); ?></td>
            </tr>
        </table>
    </div>
    <div class="floats cl" style="padding-bottom: 1em;">
        <input type="submit" name="action" value="Save" class="fl" onclick="return dateCompare();" />
        <input type="submit" name="action" value="Cancel" class="fl" style="margin-left: 10px;" />
        <input type="button" value="Return -&gt; Top" class="fr" onclick="window.scrollTo(0, 0);" />
    </div>
    <div class="section cl">
        <h2>Notes</h2>
<?php
if (isset($this->notes['Instructions'])):
?>
        <h3>Instructions</h3>
        <div id="instructions">
            <ul>
<?php
if (in_array('External', $this->notes['Instructions'])) {
?>
                <li><a href="#special_instructions1_page"><span>External</span></a></li>
<?php
}
if (in_array('Internal', $this->notes['Instructions'])) {
?>
                <li><a href="#special_instructions2_page"><span>Internal</span></a></li>
<?php
}
?>
            </ul>
<?php
if (in_array('External', $this->notes['Instructions'])) {
?>
            <div id="special_instructions1_page">
                <?php echo $this->formTextarea('special_instructions1', $this->pickOrder->specialInstructions1, array('tabindex' => '66', 'id' => 'edit_special_instructions1_page')); ?>
            </div>
<?php
}
if (in_array('Internal', $this->notes['Instructions'])) {
?>
            <div id="special_instructions2_page">
                <?php echo $this->formTextarea('special_instructions2', $this->pickOrder->specialInstructions2, array('tabindex' => '67', 'id' => 'edit_special_instructions2_page')); ?>
            </div>
<?php
}
?>
        </div>
<?php
endif;
if (isset($this->notes['Other Notes'])):
?>
        <h3>Other Notes</h3>
        <div id="other_notes">
            <ul>
<?php foreach ($this->notes['Other Notes'] as $v) { ?>
                <li><a href="#other<?php echo $v; ?>_page"><span><?php echo $v; ?></span></a></li>
<?php } ?>
            </ul>
<?php foreach ($this->notes['Other Notes'] as $v) { $propName = 'other' . $v; ?>
            <div id="other<?php echo $v; ?>_page">
                <?php echo $this->formTextarea('other' . $v, $this->pickOrder->$propName, array('tabindex' => '67')); ?>
            </div>
<?php } ?>
        </div>
<?php
endif;
if (isset($this->notes['Remarks'])):
?>
        <h3>Remarks</h3>
        <div id="remarks">
            <ul>
<?php foreach ($this->notes['Remarks'] as $v) { ?>
                <li><a href="#remarks<?php echo $v; ?>_page"><span><?php echo $v; ?></span></a></li>
<?php } ?>
            </ul>
<?php foreach ($this->notes['Remarks'] as $v) { $propName = 'remarks' . $v; ?>
            <div id="remarks<?php echo $v; ?>_page">
                <?php echo $this->formTextarea('remarks' . $v, $this->pickOrder->$propName, array('tabindex' => '68')); ?>
            </div>
<?php } ?>
        </div>
<?php
endif;
if (isset($this->notes['Footer'])):
?>
        <h3>Footer</h3>
        <div id="footerctrl">
            <ul>
<?php foreach ($this->notes['Footer'] as $v) { ?>
                <li><a href="#footerctrl-<?php echo $v; ?>"><span><?php echo $v; ?></span></a></li>
<?php } ?>
            </ul>
<?php foreach ($this->notes['Footer'] as $v) { $propName = 'footer' . $v; ?>
            <div id="footerctrl-<?php echo $v; ?>">
                <?php echo $this->formTextarea('footer' . $v, $this->pickOrder->$propName, array('tabindex' => '69')); ?>
            </div>
<?php } ?>
        </div>
<?php
endif;
?>
    </div>
    <div class="floats cl" style="padding-bottom: 1em;">
        <input type="submit" name="action" value="Save" class="fl" onclick="return dateCompare();" />
        <input type="submit" name="action" value="Cancel" class="fl" style="margin-left: 10px;" />
        <input type="button" value="Return -&gt; Top" class="fr" onclick="window.scrollTo(0, 0);" />
    </div>
</form>
<script type="text/javascript">
$(document).ready(function(){
    $('#edit_pick_due_date').datepicker({dateFormat: 'yy-mm-dd'});
    $('#edit_return_date').datepicker({dateFormat: 'yy-mm-dd'});
    $('#edit_person_id').autocomplete('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'search'), '', false); ?>', {matchSubset: 1, matchContains: 1, cacheLength: 10, formatItem: formatItem, selectFirst: 1, extraParams: {field: 'person_id'}});
    //$('#d_person_id').autocomplete('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'search'), '', false); ?>', {matchSubset: 1, matchContains: 1, cacheLength: 10, formatItem: formatItem, selectFirst: 1, extraParams: {field: 'person_id'}, onItemSelect: deliverToChanged});
    $('#s_person_id').autocomplete('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'search'), '', false); ?>', {matchSubset: 1, matchContains: 1, cacheLength: 10, formatItem: formatItem, selectFirst: 1, extraParams: {field: 's_person_id'}, onItemSelect: updateSoldByPersonId});

    $('#edit_person_id').result(function(event, data, formatted) {
        loadPersonName();
        soldToChanged();
        deliverToChanged();    
    });
    
    
    
<?php
if (isset($this->notes['Instructions'])) {
?>
    $('#instructions > ul').tabs();
<?php
}
if (isset($this->notes['Other Notes'])) {
?>
    $('#other_notes > ul').tabs();
<?php
}
if (isset($this->notes['Remarks'])) {
?>
    $('#remarks > ul').tabs();
<?php
}
if (isset($this->notes['Footer'])) {
?>
    $('#footerctrl > ul').tabs();
<?php
}
?>
    shipToInvoice();
    suppliedFromSoldFromAddress();
});

function formatItem(row) {
    return row[0] + "<br><i>" + row[1] + "</i>";
}

function updateSoldByPersonId(li)
{
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'lookup'), '', false); ?>?s_person_id=' + escape($('#s_person_id')[0].value),
        function(c) {
            $('#s_first_name')[0].value = c.firstName;
            $('#s_last_name')[0].value = c.lastName;
            $('#s_address_line1')[0].value = c.addressLine1;
            $('#s_address_line2')[0].value = c.addressLine2;
            $('#s_city')[0].value = c.city;
            $('#s_state')[0].value = c.state;
            $('#s_post_code')[0].value = c.postcode;
            $('#s_country')[0].value = c.country;
            $('#s_phone')[0].value = c.telephone;
            shipToInvoice();
        });
}

function updateSoldBySoldFrom()
{
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'lookup'), '', false); ?>?s_person_id=' + escape($('#edit_company_id')[0].value),
        function(c) {
            $('#s_person_id')[0].value = $('#edit_company_id')[0].value;
            $('#s_first_name')[0].value = c.firstName;
            $('#s_last_name')[0].value = c.lastName;
            $('#s_address_line1')[0].value = c.addressLine1;
            $('#s_address_line2')[0].value = c.addressLine2;
            $('#s_city')[0].value = c.city;
            $('#s_state')[0].value = c.state;
            $('#s_post_code')[0].value = c.postcode;
            $('#s_country')[0].value = c.country;
            $('#s_phone')[0].value = c.telephone;
        });
}

function shipToInvoice()
{
    var readonly = $('#p_same_as_invoice_to')[0].checked;

    $('#d_first_name')[0].readOnly = readonly;
    $('#d_last_name')[0].readOnly = readonly;
    $('#d_address_line1')[0].readOnly = readonly;
    $('#d_address_line2')[0].readOnly = readonly;
    $('#edit_d_city')[0].readOnly = readonly;
    $('#edit_d_state')[0].readOnly = readonly;
    $('#d_post_code')[0].readOnly = readonly;
    $('#edit_d_country')[0].readOnly = readonly;
    $('#d_phone')[0].readOnly = readonly;
    $('#ship_to')[0].disabled = readonly;
    //$('#d_person_id')[0].readOnly = readonly;

    if (readonly) {
        $('#d_first_name')[0].value = $('#edit_p_first_name')[0].value;
        $('#d_last_name')[0].value = $('#p_last_name')[0].value;
        $('#d_address_line1')[0].value = $('#p_address_line1')[0].value;
        $('#d_address_line2')[0].value = $('#p_address_line2')[0].value;
        $('#edit_d_city')[0].value = $('#p_city')[0].value;
        $('#edit_d_state')[0].value = $('#p_state')[0].value;
        $('#d_post_code')[0].value = $('#p_post_code')[0].value;
        $('#edit_d_country')[0].value = $('#p_country')[0].value;
        $('#d_phone')[0].value = $('#p_phone')[0].value;
    }
}

function suppliedFromSoldFromAddress()
{
    var personId = $('#edit_person_id')[0].autocompleter;
    personId.setExtraParams({field: 'person_id', company_id: $('#edit_company_id')[0].value, nolimit: true});

    //var deliverTo = $('#d_person_id')[0].autocompleter;
    //deliverTo.setExtraParams({field: 'person_id', company_id: $('#edit_company_id')[0].value, nolimit: true});

    var readonly = $('#s_same_as_sold_from')[0].checked;

    $('#s_person_id')[0].readOnly = readonly;
    $('#s_first_name')[0].readOnly = readonly;
    $('#s_last_name')[0].readOnly = readonly;
    $('#s_address_line1')[0].readOnly = readonly;
    $('#s_address_line2')[0].readOnly = readonly;
    $('#s_city')[0].readOnly = readonly;
    $('#s_state')[0].readOnly = readonly;
    $('#s_post_code')[0].readOnly = readonly;
    $('#s_country')[0].readOnly = readonly;
    $('#s_phone')[0].readOnly = readonly;

    if (readonly) {
        updateSoldBySoldFrom();
    }
}

function soldToChanged()
{
    var personId = $('#edit_person_id')[0];
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'address'), '', false); ?>', {person_id: personId.value, type: 'MT'}, function(json){
        if (json.length >= 1) {
            // Fill "Invoice To" combobox (dropdown list).
            var invoiceTo = $('#invoice_to')[0];
            invoiceTo.options.length = 0;
            invoiceTo.options[0] = new Option('', 'none');
            var t = 1;
            for (var i in json) {
                var key = 'r' + json[i].recordId;
                var val = [];
                if (json[i].firstName) {
                    val.push(json[i].firstName);
                }
                if (json[i].line1) {
                    val.push(json[i].line1);
                }
                if (json[i].line2) {
                    val.push(json[i].line2);
                }
                if (json[i].city) {
                    val.push(json[i].city);
                }
                if (json[i].state) {
                    val.push(json[i].state);
                }
                if (json[i].postcode) {
                    val.push(json[i].postcode);
                }
                if (json[i].country) {
                    val.push(json[i].country);
                }
                invoiceTo.options[t] = new Option(val.join(', '), key);
                t = t + 1;
            }
            if (invoiceTo.options.length == 1) {
                invoiceTo.options.length = 0;
            }
            clearSoldToItems();
        } else if (json.length == 1) {
            // Paste data in input fields.
            $('#edit_p_first_name')[0].value = json[0].firstName;
            $('#p_last_name')[0].value = json[0].lastName;
            $('#p_address_line1')[0].value = json[0].line1;
            $('#p_address_line2')[0].value = json[0].line2;
            $('#p_city')[0].value = json[0].city;
            $('#p_state')[0].value = json[0].state;
            $('#p_post_code')[0].value = json[0].postcode;
            $('#p_country')[0].value = json[0].country;
            $('#p_phone')[0].value = json[0].phone;
            //$('#invoice_to')[0].options.length = 0;
        } else {
           clearSoldToItems();
           $('#invoice_to')[0].options.length = 0;
        }
        shipToInvoice();
    });
}

function clearSoldToItems()
{
    $('#edit_p_first_name').val('');
    $('#p_last_name').val('');
    $('#p_address_line1').val('');
    $('#p_address_line2').val('');
    $('#p_city').val('');
    $('#p_state').val('');
    $('#p_post_code').val('');
    $('#p_country').val('');
    $('#p_phone').val('');
}

function shipToSelected()
{
    var shipTo = $('#ship_to')[0];
    $.getJSON('<?php echo $this->url(array('controller' => 'address', 'action' => 'show'), '', false); ?>/id/' + escape(shipTo.value.substring(1)), function(json) {
        if (json) {
            $('#d_first_name')[0].value = json.firstName;
            $('#d_last_name')[0].value = json.lastName;
            $('#d_address_line1')[0].value = json.line1;
            $('#d_address_line2')[0].value = json.line2;
            $('#edit_d_city')[0].value = json.city;
            $('#edit_d_state')[0].value = json.state;
            $('#d_post_code')[0].value = json.postcode;
            $('#edit_d_country')[0].value = json.country;
            $('#d_phone')[0].value = json.phone;
        } else {
            clearDeliverToItems();
        }
    });
}

<?php
    //commented out because referenced field removed by Glen request. Look at pick-order/edit.phtml what removed.
?>

function deliverToChanged()
{
    var personId = $('#edit_person_id')[0];

    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'address'), '', false); ?>', {person_id: personId.value, type: 'DT'}, function(json){
        if (json.length >= 1) {
            // Fill "Invoice To" combobox (dropdown list).
            var shipTo = $('#ship_to')[0];
            shipTo.options.length = 0;
            shipTo.options[0] = new Option('', 'none');
            var t = 1;
            for (var i in json) {
                var key = 'r' + json[i].recordId;
                var val = []
                if (json[i].firstName) {
                    val.push(json[i].firstName);
                }
                if (json[i].line1) {
                    val.push(json[i].line1);
                }
                if (json[i].line2) {
                    val.push(json[i].line2);
                }
                if (json[i].city) {
                    val.push(json[i].city);
                }
                if (json[i].state) {
                    val.push(json[i].state);
                }
                if (json[i].postcode) {
                    val.push(json[i].postcode);
                }
                if (json[i].country) {
                    val.push(json[i].country);
                }
                shipTo.options[t] = new Option(val.join(', '), key);
                t = t + 1;
            }
            if (shipTo.options.length == 1) {
                shipTo.options.length = 0;
            }
            clearDeliverToItems();
        } else if (json.length == 1) {
            // Paste data in input fields.
            $('#d_first_name')[0].value = json[0].firstName;
            $('#d_last_name')[0].value = json[0].lastName;
            $('#d_address_line1')[0].value = json[0].line1;
            $('#d_address_line2')[0].value = json[0].line2;
            $('#edit_d_city')[0].value = json[0].city;
            $('#edit_d_state')[0].value = json[0].state;
            $('#d_post_code')[0].value = json[0].postcode;
            $('#edit_d_country')[0].value = json[0].country;
            $('#d_phone')[0].value = json[0].phone;
            $('#ship_to')[0].options.length = 0;
        } else {
           clearDeliverToItems();
           $('#ship_to')[0].options.length = 0;
        }
        shipToInvoice();
    });
}

function clearDeliverToItems()
{
    $('#d_first_name').val('');
    $('#d_last_name').val('');
    $('#d_address_line1').val('');
    $('#d_address_line2').val('');
    $('#edit_d_city').val('');
    $('#edit_d_state').val('');
    $('#d_post_code').val('');
    $('#edit_d_country').val('');
    $('#d_phone').val('');
}

function invoiceToSelected()
{
    var invoiceTo = $('#invoice_to')[0];
    $.getJSON('<?php echo $this->url(array('controller' => 'address', 'action' => 'show'), '', false); ?>/id/' + escape(invoiceTo.value.substring(1)), function(json) {
        if (json) {
            $('#edit_p_first_name')[0].value = json.firstName;
            $('#p_last_name')[0].value = json.lastName;
            $('#p_address_line1')[0].value = json.line1;
            $('#p_address_line2')[0].value = json.line2;
            $('#p_city')[0].value = json.city;
            $('#p_state')[0].value = json.state;
            $('#p_post_code')[0].value = json.postcode;
            $('#p_country')[0].value = json.country;
            $('#p_phone')[0].value = json.phone;
        } else {
            clearSoldToItems();
        }
        shipToInvoice();
    });
}

function shipViaChanged()
{
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'shipping-service'), '', false); ?>?ship_via=' + escape($('#edit_ship_via')[0].value),
        function(d) {
            var shipService = $('#ship_service')[0];
            shipService.options.length = 0;
            for (var i = 0; i < d.length; i++) {
                shipService.options[i] = new Option(d[i].val, d[i].key)
            }
        });
}

function warehouseChanged()
{
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'despatch-location'), '', false); ?>?wh_id=' + escape($('#wh_id')[0].value),
        function(d) {
            var despatchLocation = $('#edit_despatch_location')[0];
            despatchLocation.options.length = 0;
            for (var i = 0; i < d.length; i++) {
                despatchLocation.options[i] = new Option(d[i].val, d[i].key)
            }
        });
}

function recalculateTotal()
{
    var subTotalAmount = Number($('#sub_total_amount')[0].value);
    if (isNaN(subTotalAmount)) {
        subtTotal = 0;
    }
    var taxSubTotal = Number($('#tax_sub_total')[0].value);
    if (isNaN(taxSubTotal)) {
        taxSubTotal = 0;
    }
    var freight = Number($('#freight')[0].value);
    if (isNaN(freight)) {
        freight = 0;
    }
    var taxRate = Number($('#tax_rate')[0].value);
    if (isNaN(taxRate)) {
        taxRate = 0;
    }
    var adminFeeRate = Number($('#admin_fee_rate')[0].value);
    if (isNaN(adminFeeRate)) {
        adminFeeRate = 0;
    }
    var adminFeeAmount = Number($('#admin_fee_amount')[0].value);
    if (isNaN(adminFeeAmount)) {
        adminFeeAmount = 0;
    }
    var otherNum1 = Number($('#other_num1')[0].value);
    if (isNaN(otherNum1)) {
        otherNum1 = 0;
    }
    var otherNum2 = Number($('#other_num2')[0].value);
    if (isNaN(otherNum2)) {
        otherNum2 = 0;
    }
    var amountPaid = Number($('#amount_paid')[0].value);
    if (isNaN(amountPaid)) {
        amountPaid = 0;
    }
    var taxableAmount = (freight + ((subTotalAmount + freight) * adminFeeRate/100) + adminFeeAmount + otherNum1 + otherNum2);
    var taxAmount = taxSubTotal + taxableAmount * taxRate / 100;
    var total = subTotalAmount + taxableAmount + taxAmount;
    var dueAmount = total - amountPaid;

    $('#tax_amount')[0].value = taxAmount.toFixed(2);
    $('#due_amount')[0].value = dueAmount.toFixed(2);
}
function calcDate()
{
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'calc-date'), '', false); ?>',
        {modifier: $('#days')[0].value,
         first_date: $('#edit_pick_due_date')[0].value,
         period: $('#edit_loan_period')[0].value},
        function(d) {
            $('#edit_return_date')[0].value = d.date;
            $('#days')[0].value = d.days;
        });
}

function dateCompare() {
    var fromDueDateField    = $('#edit_pick_due_date')[0].value.split('-');
    var fromReturnDateField = $('#edit_return_date')[0].value.split('-');
    
    yearDiff    = parseFloat(fromReturnDateField[0]) - parseFloat(fromDueDateField[0]);
    monthDiff   = parseFloat(fromReturnDateField[1]) - parseFloat(fromDueDateField[1]);
    dayDiff     = parseFloat(fromReturnDateField[2]) - parseFloat(fromDueDateField[2]);
    
    
    if(dayDiff < 0) {
        if(monthDiff <= 0) {
            if(yearDiff <= 0) {
                  alert('PICK_LINE_DUE_DATE must be < RETURN_DATE');
                  $('#return_date').focus();
                  return false;
            }
        }
    } else {
        if(monthDiff < 0) {
            if(yearDiff <= 0) {
                  alert('PICK_LINE_DUE_DATE must be < RETURN_DATE');
                  $('#return_date').focus();
                  return false;
            }
        } else {
            if(yearDiff < 0) {
                  alert('PICK_LINE_DUE_DATE must be < RETURN_DATE');
                  $('#return_date').focus();
                  return false;
            }
        }
    }
    
    var personId = $('#edit_person_id').val();
    
    if(personId == '' || personId == undefined){
        alert('Please fill mandatory fields.');
        return false;
    }

}
function loadPersonName() {
    var personId    = $('#edit_person_id')[0];
    
    $.getJSON('<?php echo $this->url(array('controller' => 'transfer-order', 'action' => 'search'), '', false); ?>', {q: personId.value, type: 'RP', field: 'person_name'}, function(json){
        $('#edit_contact_name')[0].value = json.contact_name;     
    });
}
var deliveryAddresses = <?php echo json_encode($this->minder->getAddresses()); ?>;
</script>

