<?php echo $this->render('header.phtml'); ?>
<script src="<?php echo $this->baseUrl; ?>scripts/ajaxfileupload.js" type="text/javascript"></script>
<!-- <form name="main" action="" method="post"> -->
    <ul class="toolbar">
        <li><label for="table_list">Select table to import </label><?php echo $this->formSelect('table_list', '', array(), $this->tableList); ?></li>
    </ul>

    <div id="container" style="height:100%">
        <div id="headers">
        </div>
        <div style="width:100%;float:left">
        <label for="data"><b>Data to Import</b></label><br>
        <?php echo $this->formTextarea('data','', array('style' => 'width:600px;')); ?>
        <ul class="toolbar">
            <li>
<form
    name="fileform"
    action="<?php echo $this->url(array('controller'=> 'admin', 'action' => 'import-clipboard-file-upload', 'module' => 'default')); ?>"
    method="POST"
    enctype="multipart/form-data">
                <label for="csvfile"><b>CSV file to Import</b></label>  <?php echo $this->formFile('csvfile', '', array()); ?>
</form>
            </li>
            <li><?php echo $this->formSubmit('action', 'Import', array('onclick' => 'return submitData();')); ?></li>
        </ul>
        </div>

        <div id="sample_table">
        </div>
    </div>

<script type="text/javascript">
<!--
$().ready(function() {
    getFields();
    $('#table_list').change(function() {getFields();});
    $('#csvfile').change(function() {
                if ($('#csvfile')[0].value) {
                    $('#action').removeClass('disabled')[0].disabled = false;
                } else {
                    $('#action').addClass('disabled')[0].disabled = true;
                }
            });
});

function getFields()
{
    $('#headers').load('<?php echo $this->url(array('controller'=> 'admin', 'action' => 'import-clipboard', 'module' => 'default')); ?>',
                       {refresh: true, table: $('#table_list').get(0).value},
                       function() {});
}

function submitData() {
    if ($('#data').get(0).value != '') {
        sendDataOrHeaders();
    } else {
        $.ajaxFileUpload(
            {
            url:'<?php echo $this->url(array('controller'=> 'admin', 'action' => 'import-clipboard-file-upload', 'module' => 'default')); ?>',
            secureuri:false,
            fileElementId:'csvfile',
            dataType: 'json',
            success: function (data, status)
            {
                if(typeof(data.error) != 'undefined') {
                    if(data.error != '') {
                        alert(data.error);
                    } else {
                        alert(data.msg);
                        sendDataOrHeaders();
                    }
                }
            },
            error: function (data, status, e) {
                    alert(e);
                }
            }
        )
    }
    return false;
}

function sendDataOrHeaders()
{
        $.ajax(
           {
            type: "POST",
            url: "<?php echo $this->url(array('controller'=> 'admin', 'action' => 'import-clipboard', 'module' => 'default')); ?>",
            cache: false,
            data: {
                   value: $('#data').get(0).value,
                   table: $('#table_list').get(0).value,
                   list:  $('#importlist form').serialize()
            },
            success: function (response) {
                var answer = eval('(' + response + ')');
                if (answer.status == true) {
                    alert(answer.message);
                    $('#sample_table').load('<?php echo $this->url(array('controller'=> 'admin', 'action' => 'import-clipboard', 'module' => 'default', 'sample' => 'true')); ?>');
                } else {
                    alert(answer.message);
                }
            },
            error: function () {
                alert('Try again');
            }
           }
          );
}
//-->
</script>
<?php echo $this->render('footer.phtml'); ?>
