<?php

$view = new Zend_View();

global $shortcuts;
/** @noinspection PhpUndefinedMethodInspection */
$shortcuts = array(

    'Audit'					=>	array(
                                        'AUDIT_CODE'		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'audit_code'), '', true),
                                        'AUDIT PROCESSING'	=>  $view->url(array('controller' => 'audit-proccessing', 'action' => 'index', 'module'     => 'default'), '', true),
                                        'LEGACY_ADJUSTMENT'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'legacy_adjustment'), '', true),
                                        'STOCKTAKE'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'stocktake'), '', true),
                                        'AUDIT SSCC'	    =>	$view->url(array('module' => 'admin2', 'controller' => 'audit-sscc', 'action' => 'index'), '', true),

    ),
    'Import Data'			=>	array(
                                        'IMPORTING DATA'    =>    $view->url(array('controller' => 'admin', 'action' => 'import-clipboard'), '', true),
                                        'CREATE IMPORT MAP'	=>	  $view->url(array('module' => 'admin2', 'controller' => 'import-map', 'action' => 'index'), '', true),
                                        'IMPORT_RULES'	    =>	  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'import_rules'), '', true),
                                        'IMPORT_MAP'	    =>	  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'import_map'), '', true),
    ),
    'Master Data'			=>	array(
                                        'BRAND'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'brand'), '', true),
                                        'CARRIER'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'carrier'), '', true),
                                        'CARRIER_SERVICE'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'carrier_service'), '', true),
                                        'CARRIER_DEPOT'			    =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'carrier_depot'), '', true),
                                        'CARRIER_WAREHOUSE'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'carrier_warehouse'), '', true),
                                        'POSTCODE_DEPOT'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'postcode_depot'), '', true),
                                        'COST_CENTRE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'cost_centre'), '', true),
                                        'COMPANY'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'company'), '', true),
                                        'DEPARTMENT'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'department'), '', true),
                                        'DIVISION'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'division'), '', true),
                                        'GROUP_COPY'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'group_copy'), '', true),
                                        'LABEL_LOCATION'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'label_location'), '', true),
                                        'LOAN_RATE'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'loan_rate'), '', true),
                                        'MODEL'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'model'), '', true),
                                        'GLOBAL_CONDITIONS'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'global_conditions'), '', true),
                                        'PRODUCT_CONDITION'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'product_condition'), '', true),
                                        'PRODUCT_DESCRIPTION'		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'product_description'), '', true),
                                        'PROJECT'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'project'), '', true),
                                        'RETICULATION'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'reticulation'), '', true),
                                        'STATUS_DEFS'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'status_defs'), '', true),
                                        'TEST_QUESTIONS'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'test_questions'), '', true),
                                        'VALID_RESPONSES'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'valid_responses'), '', true),
                                        'TURNOVER (TOG)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'tog'), '', true),
                                        'TYPE I (SSN_TYPE)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_type'), '', true),
                                        'TYPE II (GENERIC)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'generic'), '', true),
                                        'TYPE III (SSN_SUB_TYPE)'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_sub_type'), '', true),
                                        'UNIT OF MEASURE (UOM)'		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'uom'), '', true),
                                        'UOM_TYPE'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'uom_type'), '', true),
                                        'WARRANTY'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'warranty'), '', true),
                                        'ZONE'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'zone'), '', true),
                                        'REPLACE MASTER DATA'		=>	$view->url(array('controller' => 'replace', 'action' => 'index', 'module' => 'warehouse'), '', true),
                                        'REPORTS_TYPE'			    =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'reports_type'), '', true)

    ),
    'Orders'				=>	array(
                                        'CHART_OF_ACCOUNTS'                     =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'chart_of_accounts'), '', true),
                                        'ORDER_TYPE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'order_type'), '', true),
                                        'PAYMENT_METHOD'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'payment_methods'), '', true),
                                        'TERMS'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'terms'), '', true),
                                        'PACK_CUSTOMER'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pack_customer'), '', true),
                                        'PICK_ORDER'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_order'), '', true),
                                        'PICK_LOCATION'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_location'), '', true),
                                        'PICK_ITEM'                 =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_item'), '', true),
                                        'PICK_ITEM_ADDRESS'         =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'PICK_ITEM_ADDRESS'), '', true),
                                        'PICK_ITEM_CANCEL'  		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_item_cancel'), '', true),
                                        'PICK_ITEM_DETAIL'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_item_detail'), '', true),
                                        'PICK_MODE'                 =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_mode'), '', true),
                                        'PICK_DESPATCH'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_despatch'), '', true),
                                        'PACK_ID'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pack_id'), '', true),
                                        'PACK_SSCC'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pack_sscc'), '', true),
                                        'PICK_MANIFEST'		        =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'PICK_MANIFEST'), '', true),
                                        'PURCHASE_ORDER'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'purchase_order'), '', true),
                                        'PURCHASE_ORDER_LINE'		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'purchase_order_line'), '', true),
                                        'GRN'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'grn'), '', true),
                                        'GRN_ORDER'			        =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'grn_order'), '', true),
                                        'PICK_INVOICE'              =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_invoice'), '', true),
                                        'PICK_INVOICE_LINE'         =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pick_invoice_line'), '', true),
                                        'TRANSFER_REQUEST'          =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'transfer_request'), '', true),
    ),
    'Product Profiles'		=>	array(
                                        'PRODUCTS (PROD_PROFILE)'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'prod_profile'), '', true),
                                        'PROD_RESERVATION'	        =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'prod_reservation'), '', true),
                                        'KIT'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'kit'), '', true),
                                        'PRODUCT_KIT'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'product_kit'), '', true),
                                        'PROD_EAN'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'prod_ean'), '', true),
                                        'PRODUCT TYPE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'prod_type'), '', true),
                                        'PALLET CONFIGURATION'		=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'pallet_cfg'), '', true),
                                        'SLOTTING PRODUCTS'			=>	$view->url(array('controller' => 'admin', 'action' => 'slotting'), '', true),

    ),
    'Person Profiles'		=>	array(
                                        'PERSON'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'person'), '', true),
                                        'PERSON_ADDRESS'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'person_address'), '', true),
                                        'PERSON_COMPANY'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'person_company'), '', true),
                                        'ACCESS_COMPANY'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'access_company'), '', true),
                                        'ACCESS_USER'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'access_user'), '', true),
                                        'USERS (SYS_USER)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_user'), '', true),
                                        'PERSON_TYPE'               =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'person_type'), '', true),
    ),
    'Employee Profiles'		=>	array(
                                        'EMPLOYEE'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'employee'), '', true),
                                        'EMPLOYEE_IMAGE'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'employee_image'), '', true),
                                        'EMPLOYEE_ISSUE'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'employee_issue'), '', true),
                                        'OCCUPATION'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'occupation'), '', true),
                                        'SKILL'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'skill'), '', true),

    ),
    'System Tables'			=>	array(
                                        'ARCHIVING (ARCHIVE_LAYOUT)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'archive_layout'), '', true),
                                        'CONTROL'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'control'), '', true),
                                        'DATA IDENTIFIERS (PARAM)'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'param'), '', true),
                                        'GLOBAL_CONDITIONS'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'global_conditions'), '', true),
                                        'OPTIONS'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'options'), '', true),
                                        'SSN OTHER TITLES (SSN_GROUP)'			=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_group'), '', true),
                                        'SSN DESCRIPTION (DESCRIPTION_LAYOUT)'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'description_layout'), '', true),
					'REPORTS_SCHEDULE'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'reports_schedule'), '', true),
					'SYS_EMAIL'	=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_email'), '', true),
                                        'SYS_EQUIP'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_equip'), '', true),
                                        'SYS_HH'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_hh'), '', true),
                                        'SYS_MOVES'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_moves'), '', true),
                                        'SYS_LABEL'								=>	$view->url(array('controller' => 'admin', 'action' => 'print-sys'), '', true),
                                        'SYS_LABEL_VAR'							=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_label_var'), '', true),
                                        'PRINT_REQUESTS'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'print_requests'), '', true),
                                        'PRINT_REQUESTS_ARCHIVE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'print_requests_archive'), '', true),
                                        'LOCATION'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'location'), '', true),
                                        'LOCATION_RANGE'						=>	$view->url(array('controller' => 'admin', 'action' => 'location-generate'), '', true),
                                        'WAREHOUSE'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'warehouse'), '', true)
    ),
    'System Transactions'	=>	array(
                                        'v3.9 TRANSACTIONS_ARCHIVE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'transactions_archive'), '', true),
                                        'v4 TRANSACTIONS_ARCHIVE'				=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'transactions4_archive'), '', true),
                                        'SOAP_CLI Status'		 				=>	$view->url(array('controller' => 'admin', 'action' => 'check-soap-cli'), '', true),
                                        'USER_ENV'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'user_env'), '', true),
                                        'SSN_HIST'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_hist'), '', true),
                                        'SSN_TEST'								=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_test'), '', true),
                                        'SSN_TEST_RESULTS'						=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'ssn_test_results'), '', true),
                                        'PRODUCT_COND_STATUS'					=>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'product_cond_status'), '', true),
                                        'TRANSACTION_TYPES'                     =>  $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'transaction_types'), '', true),
                                        'TRANSACTIONS_TEST'                     =>  $view->url(array('module' => 'admin2', 'controller' => 'transactions-test', 'action' => 'index'), '', true),
                                        'SESSION'						        =>	$view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'session'), '', true)
    ),
    'System setup'          =>  array(
                                        'SYS_SCREEN'                            =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen'), '', true),
                                        'SYS_SCREEN_FORM'                       =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_form'), '', true),
                                        'SYS_SCREEN_VAR'                        =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_var'), '', true),
                                        'SYS_SCREEN_TABLE'                      =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_table'), '', true),
                                        'SYS_SCREEN_PROCEDURE'                  =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_procedure'), '', true),
                                        'SYS_SCREEN_ORDER'                      =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_order'), '', true),
                                        'SYS_SCREEN_GROUP'                      =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_group'), '', true),
                                        'SYS_SCREEN_TAB'                        =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_tab'), '', true),
                                        'SYS_SCREEN_ACTION'                     =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_action'), '', true),
                                        'SYS_SCREEN_BUTTON'                     =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_button'), '', true),
                                        'SYS_SCREEN_COLOUR'                     =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_screen_colour'), '', true),
                                        'SYS_MENU'                              =>    $view->url(array('controller' => 'admin', 'action' => 'crud', 'table' => 'sys_menu'), '', true),
                                        'BACKUP / RESTORE (Admin)'              =>    $view->url(array('controller' => 'admin', 'action' => 'sys-backup'), '', true)
    )
);

global $tooltip;
$tooltip	=	array('Audit'				=>	'View/Edit Audit Results from Stocktaking',
                        'AUDIT_CODE'			=>	'Add/Edit Audit Codes and Colours used for displaying Stocktaking Results',
                        'AUDIT PROCESSING'		=>	'Displays Results from STOCKTAKE Table and allow Stock Adjustments',
                        'LEGACY_ADJUSTMENT'		=>	'View LEGACY_ADJUSTMENT table using CRUD format',
                        'STOCKTAKE'				=>	'View STOCKTAKE table using CRUD format ',
                        'AUDIT SSCC'		    =>	'AUDIT SSCC',
                      'Import Data'			 =>	'Import with Copy and Paste, from .CSV files',
                        'IMPORTING DATA'	 =>	'Import Data into Minder Tables - Import from Clipboard using Copy & Paste and import using .CSV files',
                        'CREATE IMPORT MAP'  => '',
                        'IMPORT_RULES'       => 'IMPORT_RULES',
                        'IMPORT_MAP'         => 'IMPORT_MAP',
                      'Master Data'			 =>	'Maintain SSN Descriptions and Conditions',
                          'BRAND'				 =>	'Brand Names and Codes',
                        'CARRIER'			 =>	'Carrier Names and Codes',
                        'CARRIER_SERVICE'	 =>	'Carrier Service options',
                        'CARRIER_DEPOT'	     =>	'Carrier Depot options',
                        'CARRIER_WAREHOUSE'	 =>	'CARRIER_WAREHOUSE',
                        'POSTCODE_DEPOT'	 =>	'POSTCODE_DEPOT',
                         'COST_CENTRE'		 =>	'Cost Centre Descriptions and Codes',
                         'COMPANY'			 =>	'Company and Inventory Owner Names and Codes',
                        'DEPARTMENT'		 =>	'Department Names and Codes',
                        'DIVISION'			 =>	'Division Names and Codes',
                        'GROUP_COPY'		 =>	'Each GROUP_CODE Description and Code- updates up to 12xSSN Master Data Fields as one process',
                        'LABEL_LOCATION'	 =>	'Codes used to indicate location of ISSN Labels',
                        'LOAN_RATE'			 =>	'Loan Hire Costs by Loan Period by SSN_TYPE by Company',
                        'MODEL'				 =>	'Model Numbers and Codes - recommend not using',
                        'GLOBAL_CONDITIONS'  =>	'GLOBAL_CONDITIONS',
                        'PRODUCT_CONDITION'  =>	'Conditions and Codes used for SSN.OTHER1 to 5 Drop down Lists',
                        'PRODUCT_DESCRIPTION'=>	'DESCRIPTION Codes used for SSN_TYPE.FIELD1 to 5 Drop down Lists',
                        'PROJECT'			 => 'Project Names and Codes',
                        'RETICULATION'		 => 'Reticulation Names and Codes',
                        'STATUS_DEFS'		 => 'User defined SSN Status Descriptions and Codes',
                        'TEST_QUESTIONS'	 => 'Lists Test Questions for each SSN_TYPE, used as part of ASSET*MINDER Refurbishment Module',
                        'VALID_RESPONSES'	 => 'VALID_RESPONSES',
                        'TURNOVER (TOG)'	 => 'Inventory Turnover Classifications',
                        'TYPE I (SSN_TYPE)'  => 'Type I (SSN_TYPE) Descriptions and Codes',
                        'TYPE II (GENERIC)'  =>	'Type II (GENERIC) Descriptions and Codes',
                        'TYPE III (SSN_SUB_TYPE)' => 'Type III (SSN_SUB_TYPE) Descriptions and Codes',
                        'UNIT OF MEASURE (UOM)' => 'Units of Measure Descriptions and Codes',
                        'UOM_TYPE'			 => 'Types of Units of Measure Descriptions and Codes',
                        'WARRANTY'			 => 'Sales Order Warranty Descriptions for drop down lists',
                        'ZONE'				 =>	'Picking Zone Descriptions and Codes',
                        'REPLACE MASTER DATA'=> 'Replaces SSN Master Data',
                        'REPORTS_TYPE'       => 'Shows report types',
                      'Orders'				=>	'View/Edit Order Tables',
                        'CHART_OF_ACCOUNTS'             =>  'CHART_OF_ACCOUNTS',
                        'ORDER_TYPE'		 =>	'Order Types includes - Sales, Transfer, Work, Replenish, Purchase, Returns',
                        'PAYMENT_METHOD'	 => 'Sales Order Payment Methods for drop down list',
                        'TERMS'				 =>	'Sales Order Payment Terms for drop down list',
                        'PACK_CUSTOMER'		 =>	'Header Records for Orders',
                        'PICK_ORDER'		 =>	'Header Records for Orders',
                        'PICK_LOCATION'		 =>	'PICK LOCATION',
                        'PICK_ITEM'          => 'Line Records for Orders',
                        'PICK_ITEM_ADDRESS'  => 'PICK_ITEM_ADDRESS',
                        'PICK_ITEM_CANCEL'	 => 'Pick item cancel',
                        'PICK_ITEM_DETAIL'	 =>	"Records for PICK_ITEM's that have been Picked to Despatch",
                        'PICK_MODE'          => 'PICK MODE',
                        'PICK_DESPATCH'		 => 'Records for each Consignment Note',
                        'PACK_ID'			 => 'Records for each Package Despatched on a PICK_DESPATCH',
                        'PACK_SSCC'			 => 'PACK_SSCC',
                        'PICK_MANIFEST'		 =>	'PICK_MANIFEST',
                        'PURCHASE_ORDER'	 => 'Header Records for Purchase Orders',
                        'PURCHASE_ORDER_LINE'=> 'Line Records for Purchase Orders',
                        'GRN'			 	 => 'Delivery Receipting Details - Carrier, Connote, Pallets etc.',
                        'GRN_ORDER'			 => 'GRN_ORDER',
                        'PICK_INVOICE'       => 'PICK_INVOICE',
                        'PICK_INVOICE_LINE'  => 'PICK_INVOICE_LINE',
                        'TRANSFER_REQUEST'   => 'TRANSFER_REQUEST',
                      'Product Profiles'	=>	'"View/Edit Product Details',
                        'PRODUCTS (PROD_PROFILE)' =>	'Lists Product Descriptions and Properties',
                        'PROD_RESERVATION'	      =>	'PROD_RESERVATION',
                        'KIT'					  =>	'Kit Descriptions and Codes',
                        'PRODUCT_KIT'			  =>	'Lists Compositions of each KIT',
                        'PROD_EAN'				  =>	'Lists GS1 EAN13/14 Barcode Numbers and Barcode Extensions for each Product',
                        'PRODUCT TYPE'			  =>	'Lists Types of Products for Drop Down Lists',
                        'PALLET CONFIGURATION'	  =>	'List Pallet stacking details for each product',
                        'SLOTTING PRODUCTS'		  =>	'Used to place (Slot) each Product into Storage Location',
                      'Person Profiles'		=>	'"View/Edit Person Contact Address and Minder Access Details',
                        'PERSON'				 =>		'Add/Edit Contact Details for each Person (Corporations and Individuals) plus add Address Records into PERSON_ADDRESS',
                        'PERSON_ADDRESS'		 =>		'Lists Address Details for PERSON - Office, Mail To, Deliver To',
                        'PERSON_COMPANY'		 =>		'Add/Edit which Companies a PERSON is able to view in MINDER',
                        'ACCESS_COMPANY'		 =>		'Add/Edit which Companies SYS_USER is able to view in MINDER',
                        'ACCESS_USER'			 =>		'Add/Edit which Warehouses SYS_USER is able to view in MINDER',
                        'USERS (SYS_USER)'		 =>		'Add/Edit Minder Users Details - User_ID, Password, SYS_ADMIN, INVENTORY_OPERATOR',
                        'PERSON_TYPE'            =>     'Add/Edit Person Types, used in PERSON drop-down list',
                      'Employee Profiles'	=>	'"View/Edit Employee Details - used by TIME*MINDER Module',
                          'EMPLOYEE'				 =>		'EMPLOYEE details - Contact, Occupation, Union Membership, Induction etc.',
                        'EMPLOYEE_IMAGE'		 =>		'Images of employees. Used for ID Card Printing',
                        'EMPLOYEE_ISSUE'		 =>		'Issued KIT numbers to Employees for Personal Protective Equipment and Tools',
                        'OCCUPATION'			 =>		'Employee OCCUPATION details',
                        'SKILL'					 =>		'Skill Descriptions and Codes plus Training Results for EMPLOYEEs',
                      'System Tables'		=>	'"View/Edit Minder Configuration details',
                          'ARCHIVING (ARCHIVE_LAYOUT)'	=>	'Add/Edit which Tables and the period before Archiving records',
                        'CONTROL'						=>	'Main MINDER Configuration Settings Table',
                        'DATA IDENTIFIERS (PARAM)'		=>	'Details used to identify scanned input - Symbology, Length, Expression types',
                        'GLOBAL_CONDITIONS'				=>	'Defines Drop down Descriptions and Codes for SSN.OTHERx fields',
                        'OPTIONS'						=>	'Lists most Drop down list details plus other Configuration settings not in CONTROL table',
                        'SSN OTHER TITLES (SSN_GROUP)'	=>	'SSN.OTHERx Field Titles and if drop down lists (see GLOBAL_CONDITIONS) or single input',
                        'SSN DESCRIPTION (DESCRIPTION_LAYOUT)'	=>	'Define construction of SSN_DESCRIPTION using SSN and Master Data Tables',
                        'SYS_EQUIP'						=>	'Lists details of each Minder Equipment - DEVICE_ID, IP_ADDRESS etc.',
                        'SYS_HH'						=>	'Used to configure Remote Hand Held FTP details',
                        'SYS_MOVES'						=>	'Used to configure SSN Allowed/Not Allowed Movements and Inventory Status updates',
                        'SYS_LABEL'						=>	'Used to import and edit Native Label Printer Commands with Placeholders, Print Test Labels',
                        'SYS_LABEL_VAR'					=>	'Lists all SYS_LABEL Placeholders, edit Data Expressions, Test Label Default values',
                        'PRINT_REQUESTS'				=>	'Lists each Print Label request. Use for Reprints',
                        'PRINT_REQUESTS_ARCHIVE'		=>	'Lists each archived Print Label request',
                        'LOCATION'						=>	'Lists every Storage Location controlled by Minder System',
                        'LOCATION_RANGE'				=>	'Used to generate one or more LOCATION records each with the same Location Profile',
                        'WAREHOUSE'						=>	'Lists every Warehouse or Repository controlled by Minder System',
                      'System Transactions'	=>	'"View/Edit Minder SOAP Interface, Transactions, SSN History',
                        'v3.9 TRANSACTIONS_ARCHIVE'		=>	'Input and Test v3.9 Transaction - uses TRANSACTIONS and TRANSACTIONS_ARCHIVE Tables',
                        'v4 TRANSACTIONS_ARCHIVE'		=>	'Input and Test v4 Transaction - uses TRANSACTIONS4 and TRANSACTIONS4_ARCHIVE Tables',
                        'SOAP_CLI Status'				=>	'Check Legacy Interface - SOAP-CLI',
                        'USER_ENV'						=>	'User Session details -Use with care this maybe a very large table',
                        'SSN_HIST'						=>	"Lists History of SSN's - Use with care this maybe a very large table",
                        'SSN_TEST'						=>	'Lists details of SSN Test Start and Finish and Test Status',
                        'SSN_TEST_RESULTS'				=>	'Lists details of SSN Test Questions and Responses',
                        'PRODUCT_COND_STATUS'			=>	'Lists details of SSN Conditions - Original & Subsequent',
                        'TRANSACTION_TYPES'             =>  'Lists TRN_TYPE and Barcode Description Menu Data Identifier Details',
                        'TRANSACTIONS_TEST'             =>  'Transaction test screen',
                        'SESSION'				        =>	'SEssion table',
                       'System setup'                   =>  'System setup',
                        'SYS_SCREEN'                    =>  'SYS_SCREEN',
                        'SYS_SCREEN_FORM'               =>  'SYS_SCREEN_FORM',
                        'SYS_SCREEN_VAR'                =>  'SYS_SCREEN_VAR',
                        'SYS_SCREEN_TABLE'              =>  'SYS_SCREEN_TABLE',
                        'SYS_SCREEN_PROCEDURE'          =>  'SYS_SCREEN_PROCEDURE',
                        'SYS_SCREEN_ORDER'              =>  'SYS_SCREEN_ORDER',
                        'SYS_SCREEN_GROUP'              =>  'SYS_SCREEN_GROUP',
                        'SYS_SCREEN_TAB'                =>  'SYS_SCREEN_TAB',
                        'SYS_SCREEN_ACTION'             =>  'SYS_SCREEN_ACTION',
                        'SYS_SCREEN_BUTTON'             =>  'SYS_SCREEN_BUTTON',
                        'SYS_SCREEN_COLOUR'             =>  'SYS_SCREEN_COLOUR',
                        'SYS_MENU'                      =>  'SYS_MENU',
                        'BACKUP / RESTORE (Admin)'      =>  'Backup / Restore System Defaults'
);

$minder = Minder::getInstance();

if (!$minder->isStockAdjust) {
    unset($shortcuts['Audit']['STOCKTAKE']);
}

if ($minder->isRemoteSystem()) {
    unset($shortcuts['Master Data']);
}
