<?php echo $this->render("header.phtml"); ?>
<?php
    $attributes = array();
    $attributesForSelect = array();
?>
<form name="main" id="main" action="<?php echo $this->url(); ?>" method="post" id="main_form">
    <h2><?php echo $this->pageTitle; ?></h2>
    <ul class="toolbar">
        <li>
            <b>SEARCH</b>
        </li>
        <li>
            <table>
                <tr>
                    <th class="right"><label for="person_id_srch">Person ID&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formText("person_id_srch",
                                                 selectFilterValue("person_id_srch", $this->conditions),
                                                 $attributes);
                        ?>
                    </td>
                    <th></th>
                    <td></td>
                </tr>
                <tr>
                    <th class="right"><label for="first_name_srch">Name/First&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formText("first_name_srch",
                                                 selectFilterValue("first_name_srch", $this->conditions),
                                                 $attributes);
                        ?>
                    </td>
                    <th class="right"><label for="last_name_srch">Name/Last&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formText("last_name_srch",
                                                 selectFilterValue("last_name_srch", $this->conditions),
                                                 $attributes);
                        ?>
                    </td>
                </tr>
                <tr>
                    <th class="right"><label for="contact_first_name_srch">Contact First Name&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formSelectStrict("contact_first_name_srch",
                                                   selectFilterValue("contact_first_name_srch", $this->conditions),
                                                   $attributesForSelect,
                                                   $this->contactFirstNameList);
                        ?>
                    </td>
                    <th class="right"><label for="contact_last_name_srch">Contact Last Name&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formSelectStrict("contact_last_name_srch",
                                                   selectFilterValue("contact_last_name_srch",
                                                   $this->conditions),
                                                   $attributesForSelect,
                                                   $this->contactLastNameList);
                        ?>
                    </td>
                </tr>
                <tr>
                    <th class="right"><label for="company_id_srch">Company ID&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formSelect("company_id_srch",
                                                   selectFilterValue("company_id_srch", $this->conditions),
                                                   $attributesForSelect,
                                                   $this->companyIdList);
                        ?>
                    </td>
                    <th class="right"><label for="person_type_srch">Contact Type&nbsp;</label></th>
                    <td>
                        <?php
                            echo $this->formSelectStrict("person_type_srch",
                                                   selectFilterValue("person_type_srch",
                                                   $this->conditions),
                                                   $attributesForSelect,
                                                   $this->contactTypeList);
                        ?>
                    </td>
                </tr>
            </table>
        </li>
    </ul>
    <hr />
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit("action", "SEARCH", array("onclick" => "goSearch();")); ?>
            <?php echo $this->formSubmit("action", "CLEAR", array("onclick" => "return frmClear();")); ?>
        </li>
        <li>
            <?php echo $this->formSubmit("action", "ADD CONTACT", array()); ?>
            <?php echo $this->formSubmit("action", "DELETE CONTACT", array("onclick" => "return goDelete();")); ?>
        </li>
    </ul>
    <hr />
            <div style="text-transform: uppercase; font-weight: bold;">
                <div style="float:left">RESULTS List</div>
                <div id="pages" style="position: relative; left: 10ex; font-weight: none;text-transform: none;">
                    <label for="show_by">View By : </label>
                    <?php echo $this->formSelect("show_by",
                                                 $this->showBy,
                                                 array("onchange" => "frmSubmit()"),
                                                 array(5 => 5,
                                                      10 => 10,
                                                      15 => 15,
                                                      20 => 20,
                                                      30 => 30,
                                                      40 => 40,
                                                      50 => 50,
                                                     100 => 100));
                    ?>
                    <label for="pageselector">Page : </label>
                    <?php echo $this->formSelectStrict("pageselector",
                                                       $this->pageSelector,
                                                       array("onchange" => "frmSubmit()"),
                                                       $this->pages);
                    ?>
                </div>
            </div>
    <hr/>
    <div id="selected_num">
        Selected: 0
    </div>
        <table id="table" class="withborder tablesorter">
            <thead>
            <tr>
            <th>
                <?php echo $this->formCheckbox("select_all",
                                               "any_value",
                                               array("onclick" => "selectAll(this)"));?>
            </th>
<?php
    foreach ($this->headers as $header) {
        echo "<th>". $this->escape($header) . "</th>";
    }
?>
            </tr>
            </thead>
            <tbody>
<?php
    if (count($this->contacts) > 0) {
        for ($i = 0; $i < count($this->contacts); $i++) {
            $line = $this->contacts[$i];
            echo "<tr>";
            echo "<th>";

            echo $this->formCheckbox("person_id[]",
                                     $this->escape($line->id),
                                     array("class" => "person_checkbox",
                                           'checked' => selectFilterValue($this->escape($line->id), $this->conditions),
                                           "id"    => "person_id_" . $this->escape($line->id),
                                           "onclick" => "showSelected(this)" ));
            echo "</th>";
            foreach($this->headers as $propertyName => $v) {
                $val = $line->items[$propertyName];
                $urlEdit = $this->url(array("module"      => "default",
                                            "controller"  => "admin",
                                            "action"      => "contact-addresses",
                                            "start_item"  => $this->startItem,
                                            "show_by"     => $this->showBy,
                                            "edit_person_id" => $line->id),
                                            "",
                                            true);
                echo '<td><a href="'. $urlEdit . '" ' .
                          "onclick='". 'return goShow("' . $line->id . '")' . "' >" .
                          $this->escape($val) . "</a></td>" . "";


            }
            echo "</tr>\n";
        }
    } else {
        // for tablesorter JavaScript plugin (if no row & cols in table - error occurs).
        echo "<tr><th/>";
        foreach($this->headers as $propertyName => $v) {
            echo "<td/>";
        }
        echo "</tr>\n";
    }
?>
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <li id="rec_counter" style="display: inline;">
                <div id="num_rec">Total
                <?php echo $this->numRecords . " records. ";?>
                <?php echo "Show from " . ($this->startItem + 1); ?>
                <?php echo " to " . ($this->startItem + $this->maxno);?>
                </div>
            </li>
        </ul>
    <div id="filter" style="display:none">
        <input type="text" value="<?php echo $this->startItem; ?>" class="flt" id="old_start_item" name="old_start_item" />
        <input type="text" value="<?php echo $this->showBy; ?>" class="flt" id="old_show_by" name="old_show_by" />
        <input type="text" value="" name="edit_person_id" id="edit_person_id" />
    </div>
</form>
<script type="text/javascript">
<!--
var checkOnOff;
var selectedNum = 0;
var fromUrl="";
var cacheValue = 50;
$(document).ready(function(){
    $('#table').tablesorter({headers: {0: {sorter:false}},sortList:[[1,1]], widgets: ['zebra']});

    $('#person_id_srch').autocomplete('<?php echo $this->url(array('module'     => 'default',
                                                                    'controller' => 'admin',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'person_id_srch'}});
    $('#first_name_srch').autocomplete('<?php echo $this->url(array('module'     => 'default',
                                                                    'controller' => 'admin',
                                                                    'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'first_name_srch'}});
    $('#last_name_srch').autocomplete('<?php echo $this->url(array('module'     => 'default',
                                                                   'controller' => 'admin',
                                                                   'action'     => 'lookup')); ?>/',
                                    {matchSubset: 1,
                                     matchContains: 1,
                                     cacheLength: cacheValue,
                                     formatItem: formatItemWithoutDesc,
                                     selectFirst: 1,
                                     extraParams: {field: 'last_name_srch'}});
});

function formatItemWithoutDesc(ele)
{
    return ele[1];
}

function formatItemWithDesc(ele)
{
    return "<b>"+ele[0]+"</b><br/><i>"+ele[1]+"</i>";
}

function selectAll(self) {
    var chk = $("#table input:checkbox");
    var checkOnOff = $("#select_all").get(0).checked;
    for (i=0; i < chk.length; i++) {
        chk[i].checked = checkOnOff;
    }
    if (checkOnOff) {
        selectedNum = i-1;
    } else {
        selectedNum = 0;
    }
    $("#selected_num").get(0).innerHTML = "Selected: " + selectedNum;
}

function frmSubmit()
{
    document.forms.main.submit();
    return true;
}

function goShow(name)
{
    document.getElementById("edit_person_id").value = name;
    frmSubmit();
    return true;
}

function goSearch()
{
    frmSubmit();
    return true;
}

function goDelete()
{
    var res = confirm('You try to delete ' + selectedNum + ' contacts. Are you really?');
    if (res == true) {
        document.forms.main.submit();
        return true;
    } else {
        return false;
    }
}

function showSelected(element)
{
    if (element.checked) {
        selectedNum++;
    } else {
        selectedNum--;
    }
    if (selectedNum == 0) {
        $("#select_all").get(0).checked = false;
    } else if ( selectedNum == ($("#table input:checkbox").length - 1)) {
        $("#select_all").get(0).checked = true;
    }

    $("#selected_num").get(0).innerHTML = "Selected: " + selectedNum;
    return true;
}

function frmClear()
{
    $("form#main input:text").each(function() {
        this.value = "";
        });
    $("form#main select").each(function() {
        if (this.id != "show_by" && this.id != "pageselector") {
            this.selectedIndex = 0;
        }
        });
    return false;
}

//-->
</script>
<?php echo $this->render("footer.phtml");