<?php

class Minder_Db_Adapter_Sysscreen extends Zend_Db_Adapter_Abstract {
    const SR_SCHEMA = 'SR';
    const ER_SCHEMA = 'ER';

    /**
     * Specifies whether the adapter automatically quotes identifiers.
     * If true, most SQL generated by Zend_Db classes applies
     * identifier quoting automatically.
     * If false, developer must quote identifiers themselves
     * by calling quoteIdentifier().
     *
     * @var bool
     */
    protected $_autoQuoteIdentifiers = false;

    public static function schemaIsSysScreenSchema($schema) {
        return ($schema == self::SR_SCHEMA) || ($schema == self::ER_SCHEMA);
    }

    /**
     * @var Minder_Db_Adapter_Sysscreen_TableDescriptionBuilder
     */
    protected $_descriptionBuilder = null;

    protected function _checkRequiredOptions(array $config)
    {
        //no options is required
    }


    /**
     * Creates a connection to the database.
     *
     * @return void
     */
    protected function _connect()
    {
        $this->_getMainAdapter()->getConnection();
    }

    /**
     * Test if a connection is active
     *
     * @return boolean
     */
    public function isConnected()
    {
        return $this->_getMainAdapter()->isConnected();
    }

    /**
     * Begin a transaction.
     */
    protected function _beginTransaction()
    {
        $this->_getMainAdapter()->beginTransaction();
    }

    /**
     * Commit a transaction.
     */
    protected function _commit()
    {
        $this->_getMainAdapter()->commit();
    }

    /**
     * Roll-back a transaction.
     */
    protected function _rollBack()
    {
        $this->_getMainAdapter()->rollBack();
    }

    /**
     * Force the connection to close.
     *
     * @return void
     */
    public function closeConnection()
    {
        $this->_getMainAdapter()->closeConnection();
    }

    /**
     * Retrieve server version in PHP style
     *
     * @return string
     */
    public function getServerVersion()
    {
        return '0.0.1';
    }

    /**
     * Check if the adapter supports real SQL parameters.
     *
     * @param string $type 'positional' or 'named'
     * @return bool
     */
    public function supportsParameters($type)
    {
        switch ($type) {
            case 'positional':
                return true;
            case 'named':
            default:
                return false;
        }
    }

    protected function _getSysScreenMapper() {
        return new Minder_Db_Table_Sysscreen_Mapper_SysScreen();
    }

    /**
     * Returns a list of the tables in the database.
     *
     * @return array
     */
    public function listTables()
    {
        return $this->_getSysScreenMapper()->fetchSsNames();
    }

    /**
     * @return Minder_Db_Adapter_Sysscreen_TableDescriptionBuilder
     */
    protected function _getTableDescriptionBuilder() {
        if (is_null($this->_descriptionBuilder))
            $this->_descriptionBuilder = new Minder_Db_Adapter_Sysscreen_TableDescriptionBuilder();

        return $this->_descriptionBuilder;
    }

    /**
     * Returns the column descriptions for a table.
     *
     * The return value is an associative array keyed by the column name,
     * as returned by the RDBMS.
     *
     * The value of each array element is an associative array
     * with the following keys:
     *
     * SCHEMA_NAME => string; name of database or schema
     * TABLE_NAME  => string;
     * COLUMN_NAME => string; column name
     * COLUMN_POSITION => number; ordinal position of column in table
     * DATA_TYPE   => string; SQL datatype name of column
     * DEFAULT     => string; default expression of column, null if none
     * NULLABLE    => boolean; true if column can have nulls
     * LENGTH      => number; length of CHAR/VARCHAR
     * SCALE       => number; scale of NUMERIC/DECIMAL
     * PRECISION   => number; precision of NUMERIC/DECIMAL
     * UNSIGNED    => boolean; unsigned property of an integer type
     * PRIMARY     => boolean; true if column is part of the primary key
     * PRIMARY_POSITION => integer; position of column in primary key
     *
     * @param string $tableName
     * @param string $schemaName OPTIONAL
     * @return array
     */
    public function describeTable($tableName, $schemaName = null)
    {
        $descriptionBuilder = $this->_getTableDescriptionBuilder();

        return $descriptionBuilder->doBuild($tableName, $schemaName);
    }

    /**
     * Gets the last ID generated automatically by an IDENTITY/AUTOINCREMENT column.
     *
     * As a convention, on RDBMS brands that support sequences
     * (e.g. Oracle, PostgreSQL, DB2), this method forms the name of a sequence
     * from the arguments and returns the last id generated by that sequence.
     * On RDBMS brands that support IDENTITY/AUTOINCREMENT columns, this method
     * returns the last value generated for such a column, and the table name
     * argument is disregarded.
     *
     * @param string $tableName   OPTIONAL Name of table.
     * @param string $primaryKey  OPTIONAL Name of primary key column.
     * @return string
     */
    public function lastInsertId($tableName = null, $primaryKey = null)
    {
        return ''; //todo
    }

    /**
     * @return Zend_Db_Adapter_Abstract
     */
    protected function _getMainAdapter() {
        return Zend_Db_Table::getDefaultAdapter();
    }

    /**
     * Adds an adapter-specific LIMIT clause to the SELECT statement.
     *
     * @param mixed $sql
     * @param integer $count
     * @param integer $offset
     * @return string
     */
    public function limit($sql, $count, $offset = 0)
    {
        return $this->_getMainAdapter()->limit($sql, $count, $offset);
    }

    /**
     * Prepare a statement and return a PDOStatement-like object.
     *
     * @param string|Zend_Db_Select $sql SQL query
     * @return Zend_Db_Statement|PDOStatement
     */
    public function prepare($sql)
    {
        return $this->_getMainAdapter()->prepare($sql);
    }

    /**
     * Set the fetch mode.
     *
     * @param integer $mode
     * @return void
     * @throws Zend_Db_Adapter_Exception
     */
    public function setFetchMode($mode)
    {
        $this->_getMainAdapter()->setFetchMode($mode);
    }

    /**
     * @param $tableName
     * @return array
     */
    public function describeRealTables($tableName) {
        return $this->_getTableDescriptionBuilder()->buildRealTableDescriptions($tableName);
    }

    /**
     * @param $tableName
     * @return array
     */
    public function describeOrderBy($tableName) {
        return $this->_getTableDescriptionBuilder()->buildOrderBy($tableName);
    }

    public function describeStaticConditions($tableName) {
        return $this->_getTableDescriptionBuilder()->buildStaticConditions($tableName);
    }

    /**
     * @param $realFieldTableName
     * @param $realFieldColumnName
     * @return string
     */
    public function formatRealFieldAlias($realFieldTableName, $realFieldColumnName) {
        return $this->_getTableDescriptionBuilder()->formatRealFieldAlias($realFieldTableName, $realFieldColumnName);
    }
}