<?php
/**
 * Minder
 *
 * PHP version 5.2.4
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <sergey.boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @version   SVN: <svn_id>
 * @link      http://www.barcoding.com.au/
 *
 */

/**
 * TransactionSearchBasic map NetSuite datatype
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <sergey.boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @link      http://www.barcoding.com.au/
 */

class NetSuite_TransactionSearchBasic {
    public $account; //NetSuite_SearchMultiSelectField
    public $accountType; //NetSuite_SearchMultiSelectField
    public $altSalesAmount; //NetSuite_SearchDoubleField
    public $altSalesNetAmount; //NetSuite_SearchDoubleField
    public $amount; //NetSuite_SearchDoubleField
    public $amountPaid; //NetSuite_SearchDoubleField
    public $amountRemaining; //NetSuite_SearchDoubleField
    public $anyLineItem; //NetSuite_SearchMultiSelectField
    public $billable; //NetSuite_SearchBooleanField
    public $billAddress; //NetSuite_SearchStringField
    public $billAddressee; //NetSuite_SearchStringField
    public $billAttention; //NetSuite_SearchStringField
    public $billCity; //NetSuite_SearchStringField
    public $billCountry; //NetSuite_SearchEnumMultiSelectField
    public $billCounty; //NetSuite_SearchStringField
    public $billingSchedule; //NetSuite_SearchMultiSelectField
    public $billingStatus; //NetSuite_SearchBooleanField
    public $billPhone; //NetSuite_SearchStringField
    public $billState; //NetSuite_SearchStringField
    public $billZip; //NetSuite_SearchStringField
    public $ccCustomerCode; //NetSuite_SearchStringField
    public $ccExpireDate; //NetSuite_SearchDateField
    public $ccName; //NetSuite_SearchStringField
    public $ccNumber; //NetSuite_SearchStringField
    public $class; //NetSuite_SearchMultiSelectField
    public $cleared; //NetSuite_SearchBooleanField
    public $closeDate; //NetSuite_SearchDateField
    public $commissionEffectiveDate; //NetSuite_SearchDateField
    public $commit; //NetSuite_SearchEnumMultiSelectField
    public $contribution; //NetSuite_SearchLongField
    public $createdFrom; //NetSuite_SearchMultiSelectField
    public $creditAmount; //NetSuite_SearchDoubleField
    public $currencyName; //NetSuite_SearchMultiSelectField
    public $customerSubOf; //NetSuite_SearchMultiSelectField
    public $customForm; //NetSuite_SearchMultiSelectField
    public $custType; //NetSuite_SearchMultiSelectField
    public $dateCreated; //NetSuite_SearchDateField
    public $daysOpen; //NetSuite_SearchLongField
    public $daysOverdue; //NetSuite_SearchLongField
    public $debitAmount; //NetSuite_SearchDoubleField
    public $deferRevRec; //NetSuite_SearchBooleanField
    public $department; //NetSuite_SearchMultiSelectField
    public $dueDate; //NetSuite_SearchDateField
    public $employee; //NetSuite_SearchMultiSelectField
    public $endDate; //NetSuite_SearchDateField
    public $entityStatus; //NetSuite_SearchMultiSelectField
    public $excludeCommission; //NetSuite_SearchBooleanField
    public $expectedCloseDate; //NetSuite_SearchDateField
    public $externalId; //NetSuite_SearchMultiSelectField
    public $finChrg; //NetSuite_SearchBooleanField
    public $forecastType; //NetSuite_SearchMultiSelectField
    public $fxAmount; //NetSuite_SearchDoubleField
    public $giftCertificate; //NetSuite_SearchStringField
    public $grossAmount; //NetSuite_SearchDoubleField
    public $internalId; //NetSuite_SearchMultiSelectField
    public $inVsoeBundle; //NetSuite_SearchBooleanField
    public $isPayPalMeth; //NetSuite_SearchBooleanField
    public $isShipAddress; //NetSuite_SearchBooleanField
    public $item; //NetSuite_SearchMultiSelectField
    public $itemSubOf; //NetSuite_SearchMultiSelectField
    public $lastModifiedDate; //NetSuite_SearchDateField
    public $leadSource; //NetSuite_SearchMultiSelectField
    public $location; //NetSuite_SearchMultiSelectField
    public $mainline; //NetSuite_SearchBooleanField
    public $memo; //NetSuite_SearchStringField
    public $memorized; //NetSuite_SearchBooleanField
    public $merchantAccount; //NetSuite_SearchStringField
    public $name; //NetSuite_SearchMultiSelectField
    public $nameText; //NetSuite_SearchStringField
    public $netAmount; //NetSuite_SearchDoubleField
    public $nextBillDate; //NetSuite_SearchDateField
    public $number; //NetSuite_SearchLongField
    public $otherRefNum; //NetSuite_SearchLongField
    public $parent; //NetSuite_SearchLongField
    public $partner; //NetSuite_SearchMultiSelectField
    public $paymentMethod; //NetSuite_SearchMultiSelectField
    public $payPalPending; //NetSuite_SearchBooleanField
    public $payPalStatus; //NetSuite_SearchStringField
    public $payPalTranId; //NetSuite_SearchStringField
    public $poAsText; //NetSuite_SearchStringField
    public $posting; //NetSuite_SearchBooleanField
    public $postingPeriod; //NetSuite_SearchMultiSelectField
    public $probability; //NetSuite_SearchLongField
    public $promoCode; //NetSuite_SearchMultiSelectField
    public $quantity; //NetSuite_SearchDoubleField
    public $revRecEndDate; //NetSuite_SearchDateField
    public $revRecStartDate; //NetSuite_SearchDateField
    public $revRecTermInMonths; //NetSuite_SearchLongField
    public $salesRep; //NetSuite_SearchMultiSelectField
    public $salesTeamMember; //NetSuite_SearchMultiSelectField
    public $salesTeamRole; //NetSuite_SearchMultiSelectField
    public $serialNumber; //NetSuite_SearchStringField
    public $shipAddress; //NetSuite_SearchStringField
    public $shipAddressee; //NetSuite_SearchStringField
    public $shipAttention; //NetSuite_SearchStringField
    public $shipCity; //NetSuite_SearchStringField
    public $shipComplete; //NetSuite_SearchBooleanField
    public $shipCountry; //NetSuite_SearchEnumMultiSelectField
    public $shipCounty; //NetSuite_SearchStringField
    public $shipDate; //NetSuite_SearchDateField
    public $shipMethod; //NetSuite_SearchMultiSelectField
    public $shipPhone; //NetSuite_SearchStringField
    public $shipRecvStatus; //NetSuite_SearchBooleanField
    public $shipState; //NetSuite_SearchStringField
    public $shipZip; //NetSuite_SearchStringField
    public $startDate; //NetSuite_SearchDateField
    public $status; //NetSuite_SearchEnumMultiSelectField
    public $taxItem; //NetSuite_SearchMultiSelectField
    public $taxRate; //NetSuite_SearchDoubleField
    public $terms; //NetSuite_SearchMultiSelectField
    public $totalAmount; //NetSuite_SearchDoubleField
    public $trackingNumbers; //NetSuite_SearchStringField
    public $tranDate; //NetSuite_SearchDateField
    public $tranId; //NetSuite_SearchStringField
    public $tranIsVsoeBundle; //NetSuite_SearchBooleanField
    public $type; //NetSuite_SearchEnumMultiSelectField
    public $unit; //NetSuite_SearchMultiSelectField
    public $vendType; //NetSuite_SearchMultiSelectField
    public $voided; //NetSuite_SearchBooleanField
    public $vsoeAllocation; //NetSuite_SearchDoubleField
    public $vsoeAmount; //NetSuite_SearchDoubleField
    public $vsoeDeferral; //NetSuite_SearchMultiSelectField
    public $vsoeDelivered; //NetSuite_SearchBooleanField
    public $vsoePermitDiscount; //NetSuite_SearchMultiSelectField
    public $vsoePrice; //NetSuite_SearchDoubleField
    public $customFieldList; //NetSuite_SearchCustomFieldList

    public function __construct(  NetSuite_SearchMultiSelectField $account, NetSuite_SearchMultiSelectField $accountType, NetSuite_SearchDoubleField $altSalesAmount, NetSuite_SearchDoubleField $altSalesNetAmount, NetSuite_SearchDoubleField $amount, NetSuite_SearchDoubleField $amountPaid, NetSuite_SearchDoubleField $amountRemaining, NetSuite_SearchMultiSelectField $anyLineItem, NetSuite_SearchBooleanField $billable, NetSuite_SearchStringField $billAddress, NetSuite_SearchStringField $billAddressee, NetSuite_SearchStringField $billAttention, NetSuite_SearchStringField $billCity, NetSuite_SearchEnumMultiSelectField $billCountry, NetSuite_SearchStringField $billCounty, NetSuite_SearchMultiSelectField $billingSchedule, NetSuite_SearchBooleanField $billingStatus, NetSuite_SearchStringField $billPhone, NetSuite_SearchStringField $billState, NetSuite_SearchStringField $billZip, NetSuite_SearchStringField $ccCustomerCode, NetSuite_SearchDateField $ccExpireDate, NetSuite_SearchStringField $ccName, NetSuite_SearchStringField $ccNumber, NetSuite_SearchMultiSelectField $class, NetSuite_SearchBooleanField $cleared, NetSuite_SearchDateField $closeDate, NetSuite_SearchDateField $commissionEffectiveDate, NetSuite_SearchEnumMultiSelectField $commit, NetSuite_SearchLongField $contribution, NetSuite_SearchMultiSelectField $createdFrom, NetSuite_SearchDoubleField $creditAmount, NetSuite_SearchMultiSelectField $currencyName, NetSuite_SearchMultiSelectField $customerSubOf, NetSuite_SearchMultiSelectField $customForm, NetSuite_SearchMultiSelectField $custType, NetSuite_SearchDateField $dateCreated, NetSuite_SearchLongField $daysOpen, NetSuite_SearchLongField $daysOverdue, NetSuite_SearchDoubleField $debitAmount, NetSuite_SearchBooleanField $deferRevRec, NetSuite_SearchMultiSelectField $department, NetSuite_SearchDateField $dueDate, NetSuite_SearchMultiSelectField $employee, NetSuite_SearchDateField $endDate, NetSuite_SearchMultiSelectField $entityStatus, NetSuite_SearchBooleanField $excludeCommission, NetSuite_SearchDateField $expectedCloseDate, NetSuite_SearchMultiSelectField $externalId, NetSuite_SearchBooleanField $finChrg, NetSuite_SearchMultiSelectField $forecastType, NetSuite_SearchDoubleField $fxAmount, NetSuite_SearchStringField $giftCertificate, NetSuite_SearchDoubleField $grossAmount, NetSuite_SearchMultiSelectField $internalId, NetSuite_SearchBooleanField $inVsoeBundle, NetSuite_SearchBooleanField $isPayPalMeth, NetSuite_SearchBooleanField $isShipAddress, NetSuite_SearchMultiSelectField $item, NetSuite_SearchMultiSelectField $itemSubOf, NetSuite_SearchDateField $lastModifiedDate, NetSuite_SearchMultiSelectField $leadSource, NetSuite_SearchMultiSelectField $location, NetSuite_SearchBooleanField $mainline, NetSuite_SearchStringField $memo, NetSuite_SearchBooleanField $memorized, NetSuite_SearchStringField $merchantAccount, NetSuite_SearchMultiSelectField $name, NetSuite_SearchStringField $nameText, NetSuite_SearchDoubleField $netAmount, NetSuite_SearchDateField $nextBillDate, NetSuite_SearchLongField $number, NetSuite_SearchLongField $otherRefNum, NetSuite_SearchLongField $parent, NetSuite_SearchMultiSelectField $partner, NetSuite_SearchMultiSelectField $paymentMethod, NetSuite_SearchBooleanField $payPalPending, NetSuite_SearchStringField $payPalStatus, NetSuite_SearchStringField $payPalTranId, NetSuite_SearchStringField $poAsText, NetSuite_SearchBooleanField $posting, NetSuite_SearchMultiSelectField $postingPeriod, NetSuite_SearchLongField $probability, NetSuite_SearchMultiSelectField $promoCode, NetSuite_SearchDoubleField $quantity, NetSuite_SearchDateField $revRecEndDate, NetSuite_SearchDateField $revRecStartDate, NetSuite_SearchLongField $revRecTermInMonths, NetSuite_SearchMultiSelectField $salesRep, NetSuite_SearchMultiSelectField $salesTeamMember, NetSuite_SearchMultiSelectField $salesTeamRole, NetSuite_SearchStringField $serialNumber, NetSuite_SearchStringField $shipAddress, NetSuite_SearchStringField $shipAddressee, NetSuite_SearchStringField $shipAttention, NetSuite_SearchStringField $shipCity, NetSuite_SearchBooleanField $shipComplete, NetSuite_SearchEnumMultiSelectField $shipCountry, NetSuite_SearchStringField $shipCounty, NetSuite_SearchDateField $shipDate, NetSuite_SearchMultiSelectField $shipMethod, NetSuite_SearchStringField $shipPhone, NetSuite_SearchBooleanField $shipRecvStatus, NetSuite_SearchStringField $shipState, NetSuite_SearchStringField $shipZip, NetSuite_SearchDateField $startDate, NetSuite_SearchEnumMultiSelectField $status, NetSuite_SearchMultiSelectField $taxItem, NetSuite_SearchDoubleField $taxRate, NetSuite_SearchMultiSelectField $terms, NetSuite_SearchDoubleField $totalAmount, NetSuite_SearchStringField $trackingNumbers, NetSuite_SearchDateField $tranDate, NetSuite_SearchStringField $tranId, NetSuite_SearchBooleanField $tranIsVsoeBundle, NetSuite_SearchEnumMultiSelectField $type, NetSuite_SearchMultiSelectField $unit, NetSuite_SearchMultiSelectField $vendType, NetSuite_SearchBooleanField $voided, NetSuite_SearchDoubleField $vsoeAllocation, NetSuite_SearchDoubleField $vsoeAmount, NetSuite_SearchMultiSelectField $vsoeDeferral, NetSuite_SearchBooleanField $vsoeDelivered, NetSuite_SearchMultiSelectField $vsoePermitDiscount, NetSuite_SearchDoubleField $vsoePrice, NetSuite_SearchCustomFieldList $customFieldList) {
        $this->account = $account;
        $this->accountType = $accountType;
        $this->altSalesAmount = $altSalesAmount;
        $this->altSalesNetAmount = $altSalesNetAmount;
        $this->amount = $amount;
        $this->amountPaid = $amountPaid;
        $this->amountRemaining = $amountRemaining;
        $this->anyLineItem = $anyLineItem;
        $this->billable = $billable;
        $this->billAddress = $billAddress;
        $this->billAddressee = $billAddressee;
        $this->billAttention = $billAttention;
        $this->billCity = $billCity;
        $this->billCountry = $billCountry;
        $this->billCounty = $billCounty;
        $this->billingSchedule = $billingSchedule;
        $this->billingStatus = $billingStatus;
        $this->billPhone = $billPhone;
        $this->billState = $billState;
        $this->billZip = $billZip;
        $this->ccCustomerCode = $ccCustomerCode;
        $this->ccExpireDate = $ccExpireDate;
        $this->ccName = $ccName;
        $this->ccNumber = $ccNumber;
        $this->class = $class;
        $this->cleared = $cleared;
        $this->closeDate = $closeDate;
        $this->commissionEffectiveDate = $commissionEffectiveDate;
        $this->commit = $commit;
        $this->contribution = $contribution;
        $this->createdFrom = $createdFrom;
        $this->creditAmount = $creditAmount;
        $this->currencyName = $currencyName;
        $this->customerSubOf = $customerSubOf;
        $this->customForm = $customForm;
        $this->custType = $custType;
        $this->dateCreated = $dateCreated;
        $this->daysOpen = $daysOpen;
        $this->daysOverdue = $daysOverdue;
        $this->debitAmount = $debitAmount;
        $this->deferRevRec = $deferRevRec;
        $this->department = $department;
        $this->dueDate = $dueDate;
        $this->employee = $employee;
        $this->endDate = $endDate;
        $this->entityStatus = $entityStatus;
        $this->excludeCommission = $excludeCommission;
        $this->expectedCloseDate = $expectedCloseDate;
        $this->externalId = $externalId;
        $this->finChrg = $finChrg;
        $this->forecastType = $forecastType;
        $this->fxAmount = $fxAmount;
        $this->giftCertificate = $giftCertificate;
        $this->grossAmount = $grossAmount;
        $this->internalId = $internalId;
        $this->inVsoeBundle = $inVsoeBundle;
        $this->isPayPalMeth = $isPayPalMeth;
        $this->isShipAddress = $isShipAddress;
        $this->item = $item;
        $this->itemSubOf = $itemSubOf;
        $this->lastModifiedDate = $lastModifiedDate;
        $this->leadSource = $leadSource;
        $this->location = $location;
        $this->mainline = $mainline;
        $this->memo = $memo;
        $this->memorized = $memorized;
        $this->merchantAccount = $merchantAccount;
        $this->name = $name;
        $this->nameText = $nameText;
        $this->netAmount = $netAmount;
        $this->nextBillDate = $nextBillDate;
        $this->number = $number;
        $this->otherRefNum = $otherRefNum;
        $this->parent = $parent;
        $this->partner = $partner;
        $this->paymentMethod = $paymentMethod;
        $this->payPalPending = $payPalPending;
        $this->payPalStatus = $payPalStatus;
        $this->payPalTranId = $payPalTranId;
        $this->poAsText = $poAsText;
        $this->posting = $posting;
        $this->postingPeriod = $postingPeriod;
        $this->probability = $probability;
        $this->promoCode = $promoCode;
        $this->quantity = $quantity;
        $this->revRecEndDate = $revRecEndDate;
        $this->revRecStartDate = $revRecStartDate;
        $this->revRecTermInMonths = $revRecTermInMonths;
        $this->salesRep = $salesRep;
        $this->salesTeamMember = $salesTeamMember;
        $this->salesTeamRole = $salesTeamRole;
        $this->serialNumber = $serialNumber;
        $this->shipAddress = $shipAddress;
        $this->shipAddressee = $shipAddressee;
        $this->shipAttention = $shipAttention;
        $this->shipCity = $shipCity;
        $this->shipComplete = $shipComplete;
        $this->shipCountry = $shipCountry;
        $this->shipCounty = $shipCounty;
        $this->shipDate = $shipDate;
        $this->shipMethod = $shipMethod;
        $this->shipPhone = $shipPhone;
        $this->shipRecvStatus = $shipRecvStatus;
        $this->shipState = $shipState;
        $this->shipZip = $shipZip;
        $this->startDate = $startDate;
        $this->status = $status;
        $this->taxItem = $taxItem;
        $this->taxRate = $taxRate;
        $this->terms = $terms;
        $this->totalAmount = $totalAmount;
        $this->trackingNumbers = $trackingNumbers;
        $this->tranDate = $tranDate;
        $this->tranId = $tranId;
        $this->tranIsVsoeBundle = $tranIsVsoeBundle;
        $this->type = $type;
        $this->unit = $unit;
        $this->vendType = $vendType;
        $this->voided = $voided;
        $this->vsoeAllocation = $vsoeAllocation;
        $this->vsoeAmount = $vsoeAmount;
        $this->vsoeDeferral = $vsoeDeferral;
        $this->vsoeDelivered = $vsoeDelivered;
        $this->vsoePermitDiscount = $vsoePermitDiscount;
        $this->vsoePrice = $vsoePrice;
        $this->customFieldList = $customFieldList;
    }
}?>