<?php echo $this->render('header.phtml'); ?>

<h2 title="<?php echo $this->orderSsName;?>"><?php echo $this->pageTitle; ?></h2>

<?php
echo $this->messenger()->all();
if ($this->hasErrors)
    return;
?>

<div id="search_form_container">
    <?php echo $this->sysScreenSearchForm2($this->searchFormSsName, array('search_fields' => $this->searchFields));?>
</div>

<div id="manifest-container"></div>

<?php echo $this->render('austpost-manifest/carriers-dialog.phtml');?>

<?php
    echo $this->StandardSRTemplate(array('SRDefaultButtons'));
?>

<script type="text/javascript">
/* <![CDATA[ */
    function onDataReady(response) {
        if (response.errors && response.errors.length > 0)
            showErrors(response.errors);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        $('#manifest-container').minderSearchResult(response.sysScreens['<?php echo $this->manifestNamespace;?>']);

        $(document).dequeue();
    }

    function tabContainerOnSelectRow(evt) {
        var paginator = {};
        switch (evt.namespace) {
            case '<?php echo $this->manifestNamespace;?>':
                paginator = $('#manifest-container').minderSearchGetPaginatorState();
                break;
            default:
                throw 'Unknown namespace "' + evt.namespace + '"';
        }

        var dataToSend = {
            'sysScreens' : {}
        };

        dataToSend.sysScreens[evt.namespace]  = {
                    'paginator' : paginator,
                    'rowId'     : evt.rowId,
                    'state'     : evt.rowState
        };

        $(document).queue(function() {
            $('#manifest-container > div').block($('<?php echo $this->SysScreenWaitPrompt('Selecting row. Please wait...');?>'));
            $.post(
                '<?php echo $this->url(array('action' => 'select-row'));?>',
                dataToSend,
                tabContainerOnSelectRowCallback,
                'json'
            );
        }).queue(function() {
            $('#manifest-container > div').unblock();
            $(this).dequeue();
        });
    }

    function tabContainerOnSelectRowCallback(response) {
        if (response.errors && response.errors.length > 0)
            showErrors(response.errors);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        $('.selected-container.' + response.namespace).html(response.selectedRowsTotal);

        var rowsOnPage = $('.data-set.' + response.namespace + ':first tr').length;
        var totalRows  = parseInt($('.total-container.' + response.namespace).html());
        totalRows = isNaN(totalRows) ? 0 : totalRows;

        if (rowsOnPage == response.selectedRowsOnPage) {
            $('.select_all_rows.' + response.namespace).attr('checked', true);
        } else {
            $('.select_all_rows.' + response.namespace).removeAttr('checked');
        }

        if (totalRows == response.selectedRowsTotal) {
            $('.select_complete.' + response.namespace).attr('checked', true);
        } else {
            $('.select_complete.' + response.namespace).removeAttr('checked');
        }

        $('.row_selector.' + response.namespace).each(function(){
            var $_this = $(this);
            var thisRowId = $_this.attr('row_id');

            if (response.selectedRows[thisRowId]) {
                $_this.attr('checked', true);
            } else {
                $_this.removeAttr('checked');
            }
        });

        $(document).dequeue();
    }

    function loadData() {
        var dataToSend = {
            'sysScreens' : {}
        };

        dataToSend.sysScreens['<?php echo $this->manifestNamespace?>'] = {
            'paginator' : $('#manifest-container').minderSearchGetPaginatorState()
        };

        $(document).queue(function() {
            $('#manifest-container > div').block($('<?php echo $this->SysScreenWaitPrompt();?>'));
            $.post(
                '<?php echo $this->url(array('action' => 'get-dataset'));?>',
                dataToSend,
                onDataReady,
                'json'
            );
        }).queue(function() {
            $('#manifest-container > div').unblock();
            $(this).dequeue();
        });
    }

    function tabContainerOnPageChanged(evt) {
        loadData();
    }

    function tabContainerOnShowByChanged(evt) {
        loadData();
    }

    function tabContainerOnPreSort(evt) {

    }

    function tabContainerOnSort(evt) {
        loadData();
    }

    function documentOnDoSearch(evt) {
        var dataToSend = evt.searchParams;
        dataToSend.action = 'search';

        $('#barcode').val('').parent().block();
        $('#search_form_container').block();
        $(document).queue(function() {
            $('#manifest-container > div').block($('<?php echo $this->SysScreenWaitPrompt('Applying filter...');?>'));
            $.post(
                '<?php echo $this->url(array('action' => 'search'));?>',
                dataToSend,
                onDataReady,
                'json'
            );
        }).queue(function() {
            $('#manifest-container > div, #search_form_container').unblock();
            $('#barcode').parent().unblock();
            $(this).dequeue();
        });
    }

    function reRunManifestBuild() {
        $.getJSON(
            '<?php echo $this->url(array('action' => 're-run-manifest-build'));?>',
            {},
            reRunManifestBuildCallback
        );
    }

    function reRunManifestBuildCallback(response) {
        if (response.errors && response.errors.length > 0)
            showErrors(response.errors);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        if (response.generatedPdfId && response.generatedPdfId.length > 0) {
            $.each(response.generatedPdfId, function(index, value){
                showManifestPdf(value);
            });
        }
    }

    function runManifestBuild() {
        $('#carriers_dialog').find('button[name=RUN]').unbind('click.manifest-list').bind('click.manifest-list', function(evt){
            evt.preventDefault();
            $.post(
                '<?php echo $this->url(array('action' => 'run-manifest-build'));?>',
                {
                    'carrierId': $('#carriers_dialog #carrier_id').val()
                },
                runManifestBuildCallback,
                'json'
            );
        });

        $('#carriers_dialog').dialog('open');
    }

    function runManifestBuildCallback(response) {
        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.errors && response.errors.length > 0) {
            showErrors(response.errors);
            return;
        }

        $('#carriers_dialog').dialog('close');
        loadData();

        if (response.generatedPdfId && response.generatedPdfId.length > 0) {
            $.each(response.generatedPdfId, function(index, value){
                showManifestPdf(value);
            });
        }
    }

    function showManifestPdf(pdfId) {
        window.open('<?php echo $this->url(array('action' => 'show-manifest-pdf'))?>/?pdfId=' + encodeURIComponent(pdfId));
    }

    function searchBtnOnClick(evt) {
        evt.preventDefault();
        var searchEvent = $.Event('do-search');
        searchEvent.searchParams = $('#SEARCH_RESULTS_FORM').serializeArray();
        $('#SEARCH_RESULTS_FORM').trigger(searchEvent);
    }

//--------------------- DOM ready -------------------------//
    $(document).ready(function(){
        $('#manifest-container').minderSearchResult(<?php echo json_encode($this->manifestJsSearchResults);?>);
        $('#manifest-container').minderSearchResult({autosorter:true, customSort:true});
        $('#manifest-container').minderSearchResult(<?php echo json_encode($this->manifestJsSearchResultsDataset);?>);

        $('#manifest-container')
            .bind('select-row', tabContainerOnSelectRow)
            .bind('page-changed', tabContainerOnPageChanged)
            .bind('show-by-changed', tabContainerOnShowByChanged)
            .bind('pre-sort', tabContainerOnPreSort)
            .bind('sort', tabContainerOnSort);

        $(document).bind('do-search', documentOnDoSearch);
        $('#search_form_container .SEARCH_RESULTS_FORM_search_btn').bind('click', searchBtnOnClick);
    });


/* ]]> */
</script>


<script type="text/x-jquery-tmpl" id="buttons-tmpl">
    <div style="clear: both; padding-left: 10px;">
        {{if $item.data.buttons.length > 0}}
            <ul class="toolbar">
                {{each $item.data.buttons}}
                    <li><button onclick="return false;" class="green-button SCREEN_BUTTON_{{= $value.RECORD_ID}}" name="{{= $value.SSB_BUTTON_NAME}}">{{= $value.SSB_TITLE}}</button></li>
                {{/each}}
            </ul>
        {{/if}}
    </div>
</script>

<?php echo $this->render('footer.phtml'); ?>
