<?php
/**
 * Transaction_GRNVP
 *
 * PHP version 5.2.3
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <Sergey.Boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @version   SVN: <svn_id>
 * @link      http://www.barcoding.com.au/
 *
 */

/**
 * Include the definition of the Transaction base class
 */
require_once 'Transaction.php';

/**
 * Transaction_GRNVP
 *
 * This class implements the GRNVP transaction that is used to record and
 * Verifies what and how many have been delivered to the warehouse
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <Sergey.Boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @link      http://www.barcoding.com.au/
 */
class Transaction_GRNVP Extends Transaction
{
    /**
     * The Product Code of the delivered Inventory
     *
     * @var string
     */
    public $productId;

    /**
     * The Location ID for the Receipted and Verified Inventory
     *
     * @var string
     */
    public $locationId;

    /**
     * The GRN under which the Inventory was delivered to the
     * Warehouse
     *
     * @var string
     */
    public $grnNo;

    /**
     * The type of delivery. Currently this should be one of:
     *   LD = Load
     *   LP = Load Product
     *   PO = Purchase Order
     *   RA = Return Authorised
     *   TR = Transfer
     *   WO = Work Order
     *
     * @var string
     */
    public $deliveryTypeId;

    /**
     * Entered if known, otherwise generated by Database
     *
     * @var string
     */
    public $orderNo;

    /**
     * Entered if known, otherwise generated by Database
     *
     * @var string
     */
    public $orderLineNo;

    /**
     * Quantity of 1st Labels to be printed and applied to verified
     * Inventory
     *
     * @var string
     */
    public $qtyOfLabels1;

    /**
     * Quantity value printed on each of the 1st set of inventory
     * labels
     *
     * @var string
     */
    public $qtyOnLabels1;

    /**
     * Quantity of 2nd Labels to be printed and applied to verified
     * Inventory
     *
     * @var string
     */
    public $qtyOfLabels2;

    /**
     * Quantity value printed on each of the 2nd set of inventory
     * labels
     *
     * @var string
     */
    public $qtyOnLabels2;

    /**
     * The Device ID of the Printer where Labels will be printed
     *
     * @var string
     */
    public $printerId;

    /**
     * The overall Total Verified Product
     *
     * @var string
     */
    public $totalVerified;

    public $qtyOfLabels3;

    public $qtyOnLabels3;

    public $orderType = '';

    public $orderSubType = '';

    /**
     * Initialise the transaction
     *
     * @return void
     */
    public function __construct()
    {
        $this->transCode      = 'GRNV';
        $this->transClass     = 'P';
        $this->productId      = '';
        $this->locationId     = '';
        $this->grnNo          = '';
        $this->deliveryTypeId = '';
        $this->orderNo        = '';
        $this->orderLineNo    = '';
        $this->qtyOfLabels1   = '';
        $this->qtyOnLabels1   = '';
        $this->qtyOfLabels2   = '';
        $this->qtyOnLabels2   = '';
        $this->qtyOfLabels3   = 0;
        $this->qtyOnLabels3   = 0;
        $this->printerId      = '';
        $this->totalVerified  = '';
    }

    /**
     * Returns the object id for inserting into the database
     *
     * The object id for the GRNVP transaction is productId
     *
     * @return string
     */
    public function getObjectId()
    {
        return $this->productId;
    }

    /**
     * Returns the location for inserting into the database
     *
     * The location for the GRNVP transaction is locationId
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->locationId;
    }

    /**
     * Returns the sublocation for inserting into the database
     *
     * The sublocation is the GRN for the transaction
     *
     * @return string
     */
    public function getSubLocation()
    {
        return $this->grnNo;
    }

    /**
     * Returns the reference for inserting into the database
     *
     * The reference is deliveryType + | + orderNo + | + orderLineNo +| +
     * qtyOfLabels1 + | + qtyOnLabels1 + | + qtyOfLabels2 + | + qtyOnLabels2 +
     * | + printerId + | + qtyOfLabels3 + | + qtyOnLabels3
     *
     * @return string
     */
    public function getReference()
    {
        return $this->deliveryTypeId . '|' .
               $this->orderNo . '|' .
               $this->orderLineNo . '|' .
               $this->qtyOfLabels1 . '|' .
               $this->qtyOnLabels1 . '|' .
               $this->qtyOfLabels2 . '|' .
               $this->qtyOnLabels2 . '|' .
               $this->printerId . '|' .
               $this->qtyOfLabels3 . '|' .
               $this->qtyOnLabels3;
    }

    /**
     * Returns the quantity for inserting into the database
     *
     * must equal sum of the 2 sets of Label Quantities
     * [qtyOfLabels1 * qtyOnLabels1] + [qtyOfLabels2 * qtyOnLabels2] =
     * totalVerified
     *
     * @return string
     */
    public function getQuantity()
    {
        return $this->totalVerified;
    }

    /**
     * @param string $transactionResponse
     * @return Transaction_Response_GRNVP
     */
    public function parseResponse($transactionResponse) {
        return new Transaction_Response_GRNVP($transactionResponse);
    }

    public function getProdId()
    {
        return $this->productId;
    }

    public function getOrderNo()
    {
        return $this->orderNo;
    }

    public function getOrderType()
    {
        return $this->orderType;
    }

    public function getOrderSubType()
    {
        return $this->orderSubType;
    }

}
