<?php
/**
 * Transaction_GRNVH
 *
 * PHP version 5.2.3
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <Sergey.Boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @version   SVN: <svn_id>
 * @link      http://www.barcoding.com.au/
 *
 */

/**
 * Include the definition of the Transaction base class
 */
require_once 'Transaction.php';

/**
 * Transaction_GRNVH
 *
 * This class implements the GRNVH transaction that is used to record a comment
 * about goods delivered to the warehouse.
 *
 * @category  Minder
 * @package   Minder
 * @author    Sergey Boroday <Sergey.Boroday@binary-studio.com>
 * @copyright 2007 Barcoding & Data Collection Systems
 * @license   http://www.barcoding.com.au/licence.html B&DCS Licence
 * @link      http://www.barcoding.com.au/
 */
class Transaction_GRNVH Extends Transaction
{
    /**
     * The Supplier ID of the delivered Inventory
     *
     * @var string
     */
    public $supplierId;

    /**
     * The Owner ID of the delivered Inventory
     *
     * @var string
     */
    public $ownerId;

    /**
     * The Location ID of the delivered Inventory. (Includes Repository ID)
     *
     * @var string
     */
    public $locationId;

    /**
     * The GRN under which the inventory was delivered to the warehouse
     *
     * @var string
     */
    public $grnNo;

    /**
     * The type of delivery. Currently this should be one of:
     *   LD = Load
     *   LP = Load Product
     *   PO = Purchase Order
     *   RA = Return Authorised
     *   TR = Transfer
     *   WO = Work Order
     *
     * @var string
     */
    public $deliveryTypeId;

    /**
     * Entered if known, otherwise generated by Database
     *
     * @var string
     */
    public $orderNo;

    /**
     * Entered if known, otherwise generated by Database
     *
     * @var string
     */
    public $orderLineNo;

    /**
     * Quantity of 1st Labels to be printed and applied to verified
     * Inventory
     *
     * @var string
     */
    public $qtyOfLabels1;

    /**
     * Quantity value printed on each of the 1st set of inventory
     * labels
     *
     * @var string
     */
    public $qtyOnLabels1;

    /**
     * Gross Weight of each received unit of verified Inventory
     *
     * @var string
     */
    public $unitWeight;

    /**
     * WeightUnit of Measure
     *
     * @var string
     */
    public $wtUom;

    /**
     * The Device ID of the Printer where Labels will be printed
     *
     * @var string
     */
    public $printerId;

    /**
     * The overall Total Verified Product
     *
     * @var string
     */
    public $totalVerified;

    /**
     * Initialise the transaction
     *
     * @return void
     */
    public function __construct()
    {
        $this->transCode      = 'GRNV';
        $this->transClass     = 'H';
        $this->supplierId     = '';
        $this->ownerId        = '';
        $this->locationId     = '';
        $this->grnNo          = '';
        $this->deliveryTypeId = '';
        $this->orderNo        = '';
        $this->orderLineNo    = '';
        $this->qtyOfLabels1   = '';
        $this->qtyOnLabels1   = '';
        $this->unitWeight     = '';
        $this->wtUom          = '';
        $this->printerId      = '';
        $this->totalVerified  = '';
    }

    /**
     * Returns the object id for inserting into the database
     *
     * The object id for the GRNVH transaction is the Supplier ID of the
     * delivered Inventory + Owner ID of the delivered Inventory
     * supplierId must be 10 bytes
     * ownerId (has max 20 bytes).
     *
     * @return string
     */
    public function getObjectId()
    {
        return substr(str_pad($this->supplierId, 10, ' ', STR_PAD_RIGHT), 0, 10)
               . substr($this->ownerId, 0, 20);
    }

    /**
     * Returns the location for inserting into the database
     *
     * The location for the GRNVH transaction is Location ID of the delivered
     * Inventory. (Includes Repository ID)
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->locationId;
    }

    /**
     * Returns the sublocation for inserting into the database
     *
     * The sublocation is the GRN under which the Inventory was delivered
     * to the Warehouse
     *
     * @return string
     */
    public function getSubLocation()
    {
        return $this->grnNo;
    }

    /**
     * Returns the reference for inserting into the database
     *
     * The reference is deliveryType + | + orderNo + | + orderLineNo +| +
     * qtyOfLabels1 + | + qtyOnLabels1 + | + unitWeight + | + wtUom + | +
     * printerId
     *
     * @return string
     */
    public function getReference()
    {
        return $this->deliveryTypeId . '|' .
               $this->orderNo . '|' .
               $this->orderLineNo . '|' .
               $this->qtyOfLabels1 . '|' .
               $this->qtyOnLabels1 . '|' .
               $this->unitWeight . '|' .
               $this->wtUom . '|' .
               $this->printerId;
    }

    /**
     * Returns the quantity for inserting into the database
     *
     * The quantity is overall Total Verified Product
     *
     * @return string
     */
    public function getQuantity()
    {
        return $this->totalVerified;
    }
}
