<?php echo $this->render('header.phtml'); ?>
<script type="text/javascript">
    $('body').addClass('otc-page-body');
</script>

<script src="<?php echo $this->baseUrl; ?>scripts/underscore.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>scripts/backbone.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/ToolTransactionAwareMixin.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/OtcMessageBus.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/ProcessState.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/IssuesFormView.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/ReturnsFormView.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/AuditFormView.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Otc/OtcView.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Mdr/Mdr.Components.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>scripts/Mdr/Mdr.Components.ImageCapture.js"></script>


<?php if (empty($this->defaultReturnLocation)) {?>
    <ul class="restore-warnings returns hidden">
        <li>Default return location is not defined.</li>
    </ul>
<?php }?>
<span id="top-message">
<?php if (empty($this->defaultCostCenter)) {?>
    <ul id="restore-warnings issues" class="restore-warnings issues">
        <li id="restore-id">Default cost center is not defined.</li>
    </ul>
<?php }?>
</span>


<style>
<!--

input[data-item-saved] {
    background-color: greenyellow;
}


input.big, td.big{
    font-size: 18pt;
    font-weight: bold;
    vertical-align: middle;
}

.dialog_th{
    background-color: #EEEEFF;
    padding: 2px 5px 5px 2px;
    text-align: right;
    width: 20% !important;     
}
-->
</style>

<input type="hidden" id="barcode_issues" name="barcode_issues" value="<?php echo $this->barcode_issues; ?>">
<input type="hidden" id="barcode_returns" name="barcode_returns" value="<?php echo $this->barcode_returns; ?>">
<input type="hidden" id="barcode_save" name="barcode_save" value="<?php echo $this->barcode_save; ?>">
<input type="hidden" id="barcode_cancel" name="barcode_cancel" value="<?php echo $this->barcode_cancel; ?>">


<div id="issues_tab" style="background-color: lightgreen;">
    <table width="100%" cellspacing="0">
        <tr>
            <td>
                <input data-barcode="ISSUES" type="button" value="Issues" class="issues-switch" >&nbsp;
                <input data-barcode="RETURNS" type="button" value="Returns" class="returns-switch" >&nbsp;
                <input data-barcode="AUDIT" type="button" value="Audit" class="audit-switch" >
            </td>
            <td style="text-align:right;">
                <input type="button" value="?" class="green small" onclick="return Otc.Dlg.Query.open();">
                <input data-barcode="ADDP" type="button" value="Add Product" class="green large">
                <input data-barcode="ADDT" type="button" value="Add Tool" class="green large">
                <input data-barcode="ADDB" type="button" value="Add Borrower" class="green large" />
            <input data-barcode="ADDL" type="button" value="Add Location" class="green large add-new-location-button" />
                <input data-barcode="ADDC" type="button" value="<?php echo $this->options()->getCostCenterCaption(); ?>" class="green large add-cost-center-button" />

                

            </td>
        </tr>
    </table>
        <div class="fields">
            <div>
                <div class="big label">Charge To:</div>
                <input value="<?php echo $this->issuesStatus->_costCenter->id;?>" type="text" name="cost_centre" id="field1_issues" class="big infield" >
                <input value="<?php echo $this->issuesStatus->_costCenter->description;?>" class="big comment" type="text" id="field1_tip_issues" name="cost_centre_tip" disabled="disabled">
            </div>
            <div>
                <div class="big label">Issue To:</div>
                <input value="<?php echo $this->issuesStatus->_borrower->displayedId;?>" type="text" name="badge_code" id="field2_issues" class="big infield" >
                <input value="<?php echo $this->issuesStatus->_borrower->description;?>" class="big comment" type="text" id="field2_tip_issues"  name="badge_code_tip" disabled="disabled">
            </div>
            <div>
                <div class="big label">Product/Tool:</div>
                <input value="<?php echo $this->issuesStatus->_item->id;?>" type="text" name="barcode" id="field3_issues" class="big infield" >
                <input value="<?php echo $this->issuesStatus->_item->description;?>" class="big comment" type="text" id="field3_tip_issues"  name="barcode_tip" disabled="disabled">
                <input class="big tool_transaction_message" type="text" readonly>
            </div>
            <div>
                <div class="inline-field-set">
                    <div>
                        <div class="big label">Issue Qty:</div>
                        <input value="<?php echo $this->issuesStatus->issueQty;?>" type="text" name="qty" id="field4_issues" class="big short" >
                        <input value="<?php echo $this->issuesStatus->issueQtyDescription;?>" class="big short" type="text" id="field4_tip_issues"  name="qty_tip" disabled="disabled">
                    </div>
                    <div>
                        <div class="big label">Loaned Total:</div>
                        <input value="<?php echo $this->issuesStatus->_borrower->loanedTotal;?>" type="text" name="loaned" id="field5_issues" class="big short" disabled="disabled">
                        <input value="<?php echo $this->issuesStatus->_borrower->loanedTotalDescription;?>" class="big short" type="text" id="field5_tip_issues" name="loaned_tip" disabled="disabled">
                    </div>
                </div>
                <div id="issues_image_container" class="inline-field-set"></div>
                <div class="inline-field-set safety-indicator expired hidden">
                    <div>Safety Test</div>
                    <div class="expired-caption">Expired</div>
                    <div class="expire-caption">Expire</div>
                    <div class="expired-date">&nbsp;</div>
                </div>
                <div class="inline-field-set calibration-indicator expired hidden">
                    <div>Calibration</div>
                    <div class="expired-caption">Expired</div>
                    <div class="expire-caption">Expire</div>
                    <div class="expired-date">&nbsp;</div>
                </div>
                <div class="inline-field-set inspection-indicator expired hidden">
                    <div>Inspection</div>
                    <div class="expired-caption">Expired</div>
                    <div class="expire-caption">Expire</div>
                    <div class="expired-date">&nbsp;</div>
                </div>
            </div>

        </div>
        <br>
    <table width="100%">
        <tr>
            <td>
                <input data-barcode="SAVE" type="button" value="SAVE" class="green" >&nbsp;
                <input data-barcode="CANCEL" type="button" value="CANCEL" class="green" >
                <input data-barcode="LISTL" type="button" value="List Loans" class="green large list-loans">
                <input data-barcode="HISTORY" type="button" value="Tool History" class="green large">
                <input data-barcode="DISPOSE" type="button" value="Dispose Tool" class="green large">
                <input data-barcode="PRINTT" type="button" value="Print Tool" class="green large">
                <input data-barcode="PRINTB" type="button" value="Print Borrower" class="green large">
                <input data-barcode="PRINTP" type="button" value="Print Product" class="green large">
                <input type="button" value="Capture Image" class="green large">
            </td>
        </tr>
    </table>
    <?php echo $this->printerSelect('otc_printer_select'); ?>
    <br /><br />
    <form method="get" id="main_form_issues" action="/minder/otc/" target="_blank">    
        <div style="position: relative; left:10px;">
            <b>Issues &nbsp; &nbsp; &nbsp; &nbsp; Selected: &nbsp; &nbsp;</b> <span  id="selected_num_history_issues" style="font-weight: bold;"><?php echo $this->totalSelect; ?></span>
            <label for="results_per_page">View By:</label>
            <?php echo $this->formSelect('show_by_issues',
                                        $this->navigation_issues['show_by'],
                                        array('onchange' => 'loadLines()'),
                                        array(5  => 5,
                                              10 => 10,
                                              15 => 15,
                                              20 => 20,
                                              30 => 30,
                                              40 => 40,
                                              50 => 50,
                                              100 => 100)) ?>
            <label for="page">Page:</label>
            <?php echo $this->formSelectStrict('pageselector_issues',
                                               $this->navigation_issues['pageselector'],
                                               array('onchange' => 'loadLines_isses()'),
                                               $this->pages); ?>
        </div>
        <table id="lines_issues" class="withborder tablesorter">
            <thead>
            <tr>
                <th>
                    <?php echo $this->formCheckbox('select_all_lines_issues', null , array('checked' => $this->upperChekbox, 'onclick' => 'selectAllLines_issues(this)')); ?>
                </th>
    <?php
        foreach ($this->headers1 as $header) {
            echo '<th>'. $this->escape($header) . '</th>';
        }
    ?>
            </tr>
            </thead>
            <tbody>
            
    <?php   foreach ($this->data as $history) {  ?>
                <tr>
                    <th><?php  
                                if(in_array($history['RECORD_ID'], $this->conditions)) {
                                    echo $this->formCheckbox($history['RECORD_ID'], $history['RECORD_ID'], array('checked' => 'true', 'onclick' => 'selectOneLine(this)')) . '</th>';
                                } else {
                                    echo $this->formCheckbox($history['RECORD_ID'], $history['RECORD_ID'], array('onclick' => 'selectOneLine(this)')) . '</th>';
                                } 
                        
                               $tooltip = 'No description'; 
                               foreach ($this->headers as $key => $val) { ?>
                               
                                    <td><?php echo $this->escape($history[$key]) ?></td>
                                    
                         <?php } ?>
            
                </tr>
            <?php } ?>
                <tr class="even" style="display: none;"><td><input type="checkbox" name =""></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>                
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
                <li id='rec_counter_issues' style="display: inline;">
                    <div id='num_rec_issues'>Total records. Show from 0 to <span id="issues_count" class="float: right;">0</span>                   
                    </div>
                </li>
        </ul>
    </form>

    <form method="post" id="issues_reporting" action="<?php echo $this->url(array('action' => 'issues-report'));?>" target="_blank">
        <b>Reporting</b><br>
        From: <input id="from_date" type="text" tabindex="19" autocomplete="off" value="<?php echo $this->from_date; ?>" name="from_date"/> &nbsp;&nbsp;&nbsp;
        <label for="warehouse">Warehouse:</label> <?php echo $this->warehouseSelect('wh_id', 'XB');?> <br>

        To: &nbsp;&nbsp;&nbsp;&nbsp;<input id="to_date" type="text" tabindex="19" autocomplete="off" value="<?php echo $this->to_date; ?>" name="to_date"/>
        <br><br>
        <ul class="toolbar" style="margin-top: 0; border-top: solid 1px #999;" id="edit_field_buttons">
            <li>
                <input type="button" class="order-button" name="report" id="report_issues"
                    value="REPORT:TOOLS: CSV" onclick="report_i ('REPORT:TOOLS: CSV');"/>
            </li>
            <li>
                <input type="button" class="order-button" name="report" id="report_issues"
                     value="ISSUES TODAY: CSV" onclick="report_i ('ISSUES TODAY: CSV');"/>
            </li>
            <li>
                <input type="button" class="order-button" name="report" id="report_issues"
                     value="REPORT: XLS" onclick="report_i ('REPORT: XLS');"/>
            </li>
                <input type="button" class="order-button" name="report" id="report_issues"
                     value="REPORT:CONSUMABLES: CSV" onclick="report_i ('REPORT:CONSUMABLES: CSV');"/>
            <li>

            </li>
        </ul>
        <input id="report_type_i" type="hidden" name="report_type" value="" />      
    </form>
    
    <?php echo $this->render('otc/dialogs/query.phtml');?>
    <?php echo $this->render('otc/dialogs/add-borrower.phtml');?>
    <?php echo $this->render('otc/dialogs/add-cost-centre.phtml');?>
    <?php echo $this->render('otc/dialogs/add-tool.phtml');?>
    <?php echo $this->render('otc/dialogs/add-product.phtml');?>
    <?php echo $this->render('otc/dialogs/confirm-expirations.phtml');?>
    <?php echo $this->render('otc/dialogs/list-loans.phtml');?>
    <?php echo $this->render('otc/dialogs/confirm-tool-transfer.phtml');?>
    <?php echo $this->render('otc/dialogs/import-audit.phtml');?>
    <?php echo $this->render('otc/dialogs/image-capture.phtml');?>
    <?php echo $this->render('otc/dialogs/add-new-location.phtml');?>


    <div id="history_dialog" class="flora otc-history_dialog" title="History" style="display: none;">&nbsp;</div>
    <div id="dispose_tool_dialog" class="flora otc-dispose_tool_dialog" title="Dispose Tool" style="display: none;">&nbsp;</div>
    
    <script type="text/javascript">
    <!--
    
    $(document).ready(function(){
        // added sort

        $("#lines_issues").tablesorter({headers: {0: {sorter:false}},sortList:[[1,0]], widgets: ['zebra']});
        $('#from_date').datepicker({dateFormat: 'yy-mm-dd'});
        $('#to_date').datepicker({dateFormat: 'yy-mm-dd'});

        var $historyDialog = $('#history_dialog'),
            historyDialogWidth = $historyDialog.css('width'),
            historyDialogHeight = $historyDialog.css('height');

        $historyDialog.css('width', 'auto');
        $historyDialog.css('height', 'auto');
        $historyDialog.dialog({
            buttons:        {CLOSE: function() {$('#history_dialog').dialog('close')}},
            width: historyDialogWidth,
            height: historyDialogHeight,
            autoOpen:       false,
            position:       [0, 65],
            buttonStyle:    'otc-dialog-button'
        }).bind('dialogopen', function(event, ui) {
            $(this).show();
            $('#barcode').focus();
            $('#history_dialog').attr('active', true);
        }).bind('dialogclose', function(event, ui) {
            $('#barcode').focus();
            $('#history_dialog').removeAttr('active');
        }).parents('.ui-resizable').bind('resizestop', function(){
            resizeDialogContent($('#history_dialog'));
        });

        $('#dispose_tool_dialog').dialog({
            buttons:        {CLOSE: function() {$('#dispose_tool_dialog').dialog('close')}},
            width:          '800px',
            height:         '480px',
            autoOpen:       false,
            position:       [0, 65],
            buttonStyle:    'otc-dialog-button'
        }).bind('dialogopen', function(event, ui) {
            $(this).show();
            $('#barcode').focus();
            $('#dispose_tool_dialog').attr('active', true);
        }).bind('dialogclose', function(event, ui) {
            $('#barcode').focus();
            $('#dispose_tool_dialog').removeAttr('active');
        });

        $('.list-loans').click(function(){
            setLoansSource(
                '<?php echo $this->url(array('action' => 'list-loans'))?>',
                '<?php echo $this->url(array('action' => 'export-loans'))?>',
                '<?php echo $this->url(array('action' => 'mark-loans'))?>'
            );
            listLoans();
        });
    });
    
    function report_i (target) {
        $('#report_type_i')[0].value=target;
        $('#issues_reporting')[0].submit();
        $('#barcode')[0].focus();
    }

    function frmSubmitLines_issues(input) {
        oldForm = $("#main_form_issues");
        lowerVal = input.value.toLowerCase();
        $("#main_form_issues").prepend('<input type="hidden" id="toDelete_issues" name="report" value="' + lowerVal + '" />')[0].submit();
        $('#toDelete_issues').remove();
        $("#main_form_issues").action = oldForm;
        return false;
    };
    
    //-->
    </script>
    
    
</div>
<div id="returns_tab" style="background-color: lightyellow; display: none;">
    <table width="100%" cellspacing="0">
        <tr>
            <td>
                <input data-barcode="ISSUES" type="button" value="Issues" class="issues-switch" >&nbsp;
                <input data-barcode="RETURNS" type="button" value="Returns" class="returns-switch" >&nbsp;
                <input data-barcode="AUDIT" type="button" value="Audit" class="audit-switch" >
            </td>
            <td style="text-align:right;">
                <input type="button" value="?" class="green small" onclick="return Otc.Dlg.Query.open();">
                <input data-barcode="HOME" type="button" value="Record Home" class="green large" disabled>
            </td>
        </tr>
    </table>
    <div class="fields">
        <div>
            <div class="big label">Return To:</div>
            <input value="<?php echo $this->returnsStatus->_location->location;?>" type="text" name="cost_centre" id="field1_returns" class="big infield" ">
            <input value="<?php echo $this->returnsStatus->_location->description;?>" class="big comment" type="text" id="field1_tip_returns" name="cost_centre_tip" disabled="disabled">
        </div>
        <div>
            <div class="big label">Return From:</div>
            <input value="<?php echo $this->returnsStatus->_borrower->id;?>" type="text" name="badge_code" id="field2_returns" class="big infield" ">
            <input value="<?php echo $this->returnsStatus->_borrower->description;?>" class="big comment" type="text" id="field2_tip_returns"  name="badge_code_tip" disabled="disabled">
        </div>
        <div>
            <div class="big label">Tool:</div>
            <input value="<?php echo $this->returnsStatus->_item->id;?>" type="text" name="barcode" id="field3_returns" class="big infield" ">
            <input value="<?php echo $this->returnsStatus->_item->description;?>" class="big comment" type="text" id="field3_tip_returns"  name="barcode_tip" disabled="disabled">
            
        </div>

	<div>
            <div class="big label">Home Locn:</div>
            <input value="<?php echo $this->returnsStatus->_item->homeLocation;?>" type="text" name="home_locn" id="field6_returns" class="big infield" ">
            <input value="<?php echo $this->returnsStatus->_item->locnName;?>" class="big comment" type="text" id="field6_tip_returns"  name="home_locn_name">
            <input class="big tool_transaction_message" type="text" readonly>
        </div>

	<div>
            <div class="inline-field-set">
                <div>
                    <div class="big label">Return Qty:</div>
                    <input value="<?php echo $this->returnsStatus->issueQty;?>" type="text" name="qty" id="field4_returns" class="big short" ">
                    <input value="<?php echo $this->returnsStatus->issueQtyDescription;?>" class="big short" type="text" id="field4_tip_returns"  name="qty_tip" disabled="disabled">
                </div>
                <div>
                    <div class="big label">Loaned Total:</div>
                    <input value="<?php echo $this->returnsStatus->loanedTotal;?>" type="text" name="loaned" id="field5_returns" class="big short" disabled="disabled">
                    <input value="<?php echo $this->returnsStatus->loanedTotalDescription;?>" class="big short" type="text" id="field5_tip_returns" name="loaned_tip" disabled="disabled">
                </div>
            </div>
            <div id="returns_image_container" class="inline-field-set"></div>
            <div class="inline-field-set safety-indicator expired hidden">
                <div>Safety Test</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
            <div class="inline-field-set calibration-indicator expired hidden">
                <div>Calibrate</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
            <div class="inline-field-set inspection-indicator expired hidden">
                <div>Inspection</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
        </div>
    </div>
    <br>
    <input data-barcode="SAVE" type="button" value="SAVE" class="green" >&nbsp;
    <input data-barcode="CANCEL" type="button" value="CANCEL" class="green" >&nbsp;
    <input data-barcode="IR" type="button" value="Issues/Returns" class="green large list-issues-returns">&nbsp;
    <input data-barcode="RL" type="button" value="On Loan List" class="green large list-returns">
    <input type="button" value="Capture Image" class="green large">

    <br /><br /><br />

    <form method="post" id="main_form_returns" action="/minder/otc/index">    
       <div style="position: relative; left:10px;">
            <b>Selected:</b> <span  id="selected_num_history_returns" style="font-weight: bold;"><?php echo $this->totalSelect; ?></span>
            <label for="results_per_page">View By:</label>
            <?php echo $this->formSelect('show_by_returns',
                                        $this->navigation_returns['show_by'],
                                        array('onchange' => 'loadLines_returns()'),
                                        array(5  => 5,
                                              10 => 10,
                                              15 => 15,
                                              20 => 20,
                                              30 => 30,
                                              40 => 40,
                                              50 => 50,
                                              100 => 100)) ?>
            <label for="page">Page:</label>
            <?php echo $this->formSelectStrict('pageselector_returns',
                                               $this->navigation_returns['pageselector'],
                                               array('onchange' => 'loadLines()'),
                                               $this->pages); ?>
        </div>
        <table id="lines_returns" class="withborder tablesorter">
            <thead>
            <tr>
                <th>
                    <?php echo $this->formCheckbox('select_all_lines_returns', null , array('checked' => $this->upperChekbox, 'onclick' => 'selectAllLines_issues(this)')); ?>
                </th>
    <?php
        foreach ($this->headers2 as $header) {
            echo '<th>'. $this->escape($header) . '</th>';
        }
    ?>
            </tr>
            </thead>
            <tbody>
            
    <?php   foreach ($this->data as $history) {  ?>
                <tr>
                    <th><?php  
                                if(in_array($history['RECORD_ID'], $this->conditions)) {
                                    echo $this->formCheckbox($history['RECORD_ID'], $history['RECORD_ID'], array('checked' => 'true', 'onclick' => 'selectOneLine(this)')) . '</th>';
                                } else {
                                    echo $this->formCheckbox($history['RECORD_ID'], $history['RECORD_ID'], array('onclick' => 'selectOneLine(this)')) . '</th>';
                                } 
                        
                               $tooltip = 'No description'; 
                               foreach ($this->headers as $key => $val) { ?>
                               
                                    <td><?php echo $this->escape($history[$key]) ?></td>
                                    
                         <?php } ?>

                </tr>
            <?php } ?>
                <tr class="even" style="display: none;"><td><input type="checkbox" name =""></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>        
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
                <li id='rec_counter_returns' style="display: inline;">
                    <div id='num_rec_returns'>Total records. Show from 0 to <span id="returns_count" class="float: right;">0</span>                 
                    </div>
                </li>
        </ul>
        <ul class="toolbar" style="margin-top: 0; border-top: solid 1px #999;" id="edit_field_buttons">
            <li>
                <input type="submit" class="order-button" name="report" id="report_returns"
                    value="REPORT: CSV" onclick="report_r('REPORT: CSV');" />
            </li>
            <!-- 
            <li>
                <input type="submit" class="order-button" name="report" id="report_returns"
                    value="ISSUES TODAY: CSV" onclick="report_r('ISSUES TODAY: CSV');" />
            </li>
             -->
            <li>
                <input type="submit" class="order-button" name="report" id="report_returns"
                    value="REPORT: XLS" onclick="report_r('REPORT: XLS');" />
            </li>            
        </ul>
        
        <input id="report_type_r" type="hidden" name="report_type" value="" />
    </form>
    <script type="text/javascript">
    <!--
    
    $(document).ready(function(){
        // added sort
        $("#lines_returns").tablesorter({headers: {0: {sorter:false}},sortList:[[1,0]], widgets: ['zebra']});

    $('#issues_tab input[type=button]').click(function(){
        removeMessages();
        removeErrors();   
        removeWarnings();
       $('.restore-errors').remove();

    });


    $('#returns_tab input[type=button]').click(function(){
        removeMessages();
        removeErrors();   
        removeWarnings();
        $('.restore-errors').remove();

    });


        $('#audit_tab input[type=button]').click(function(){
        removeMessages();
        removeErrors();   
        removeWarnings();
        $('.restore-errors').remove();

    });


    });
    
    function report_r (target) {
        $('#report_type_r')[0].value=target;
        $('#main_form_returns')[0].submit();
        $('#barcode')[0].focus();
    }

    //-->
    </script>

</div>

<div id="audit_tab" style="background-color: lightblue; display: none;">
    <table width="100%" cellspacing="0">
        <tr>
            <td>
                <input data-barcode="ISSUES" type="button" value="Issues" class="issues-switch" >&nbsp;
                <input data-barcode="RETURNS" type="button" value="Returns" class="returns-switch" >&nbsp;
                <input data-barcode="AUDIT" type="button" value="Audit" class="audit-switch" >
            </td>
            <td style="text-align:right;">
                <input type="button" value="?" class="green small" onclick="return Otc.Dlg.Query.open();">
                <input type="button" value="Import Audit" class="green large">
            </td>
        </tr>
    </table>
    <div class="fields">
        <div>
            <div class="big label">Location:</div>
            <input type="text" name="location" class="big infield" ">
            <input class="big comment" type="text" name="location_tip" disabled="disabled">
        </div>
        <div>&nbsp;
        </div>
        <div>
            <div class="big label">Tool:</div>
            <input type="text" name="tool" class="big infield" ">
            <input class="big comment" type="text" name="tool_tip" disabled="disabled">
            <input class="big tool_transaction_message" type="text" readonly>
        </div>
        <div>
            <div class="inline-field-set">
                <div>
                    <div class="big label">Scanned Total:</div>
                    <input type="text" name="scanned_total" class="big short" disabled="disabled">
                </div>
                <div>
                    <div class="big label">Loc. Total:</div>
                    <input type="text" name="location_total" class="big short" disabled="disabled">
                </div>
            </div>
            <div id="returns_image_container" class="inline-field-set"></div>
            <div class="inline-field-set safety-indicator expired hidden">
                <div>Safety Test</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
            <div class="inline-field-set calibration-indicator expired hidden">
                <div>Calibrate</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
            <div class="inline-field-set inspection-indicator expired hidden">
                <div>Inspection</div>
                <div class="expired-caption">Expired</div>
                <div class="expire-caption">Expire</div>
                <div class="expired-date">&nbsp;</div>
            </div>
        </div>
    </div>
    <br>
    <input data-barcode="END" type="button" value="END AUDIT" class="green large" >&nbsp;
    <input type="button" value="Capture Image" class="green large">

    <br /><br />

    <form method="post" id="main_form_audit">
       <div style="position: relative; left:10px;">
            <b>Selected:</b> <span  class="selected-amount" style="font-weight: bold;"><?php echo $this->totalSelect; ?></span>
            <label for="results_per_page">View By:</label>
            <?php echo $this->formSelect('show_by_returns',
                                        $this->navigation_returns['show_by'],
                                        array('onchange' => 'loadLines_returns()'),
                                        array(5  => 5,
                                              10 => 10,
                                              15 => 15,
                                              20 => 20,
                                              30 => 30,
                                              40 => 40,
                                              50 => 50,
                                              100 => 100)) ?>
            <label for="page">Page:</label>
            <?php echo $this->formSelectStrict('pageselector_returns',
                                               $this->navigation_returns['pageselector'],
                                               array('onchange' => 'loadLines()'),
                                               $this->pages); ?>
        </div>
        <table class="withborder tablesorter audit-history-lines">
            <thead>
            <tr>
                <th>
                    <?php echo $this->formCheckbox('select_all_lines_audit', null , array('checked' => $this->upperChekbox, 'onclick' => 'selectAllLines_issues(this)')); ?>
                </th>
                <th>Date Scanned</th>
                <th>Tool ID (ISSN)</th>
                <th>Tool Description</th>
                <th>Tool Location</th>
            </tr>
            </thead>
            <tbody>
                <tr class="even" style="display: none;">
                    <td><input type="checkbox" name =""></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
                <li id='rec_counter_returns' style="display: inline;">
                    <div id='num_rec_returns'>Total records. Show from 0 to <span id="returns_count" class="float: right;">0</span>
                    </div>
                </li>
        </ul>
        <ul class="toolbar" style="margin-top: 0; border-top: solid 1px #999;" id="edit_field_buttons">
            <li>
                <input type="submit" class="order-button" name="report" id="report_returns"
                    value="REPORT: CSV" onclick="report_r('REPORT: CSV');" />
            </li>
            <li>
                <input type="submit" class="order-button" name="report" id="report_returns"
                    value="REPORT: XLS" onclick="report_r('REPORT: XLS');" />
            </li>
        </ul>

        <input id="report_type_r" type="hidden" name="report_type" value="" />
    </form>
</div>

<script type="text/javascript">

// prepearing for input. seting handlers
$(document).ready(function() {
    $('#barcode')[0].focus();
    showHideLeft('<?php echo $this->url(array('controller' => 'user', 'action' => 'ajax-left-pannel-state'), '', true); ?>');

    otcView = new OtcView({
        el: 'body',
        serviceUrlList: {
            logServiceUrl: '<?php echo $this->baseUrl()?>/service/otc_log.php',
            setCostCenter: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-cost-center'))?>',
            setBorrower: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-borrower'))?>',
            setLocation: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-location'))?>',
            setTool: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-tool'))?>',
            setToolAltBarcode: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-tool-alt-barcode'))?>',
            setConsumable: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-consumable'))?>',
            setIssueQty: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'set-issue-qty'))?>',
            confirmExpiration: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'confirm-expirations'))?>',
            confirmTransfer: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'confirm-tool-transfer'))?>',
            endAudit: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'end-audit'))?>',
            reloadTool: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'reload-tool'))?>',
            executeToolTransaction: '<?php echo $this->url(array('controller' => 'otc-service', 'action' => 'execute-tool-transaction'))?>'
        },
        defaultCostCenter: '<?php echo $this->defaultCostCenter?>',
        defaultReturnLocation: '<?php echo $this->defaultReturnLocation?>',
        issuesState: <?php echo json_encode($this->issuesStatus, JSON_FORCE_OBJECT);?>,
        returnsState: <?php echo json_encode($this->returnsStatus, JSON_FORCE_OBJECT);?>,
        auditState: <?php echo json_encode($this->auditStatus, JSON_FORCE_OBJECT);?>,
        locationFormatMap: <?php echo json_encode($this->options()->getLocationFormatMap(), JSON_FORCE_OBJECT); ?>,
        currentWhId: '<?php echo $this->environment()->getCurrentWarehouseId(); ?>'
    });

});

// dialog section

function showHistory() {
    var $historyDialog = $("#history_dialog");
    $historyDialog.load(
        '<?php echo $this->url(array('action' => 'view-history'))?>',
        {},
        function(){
            updateHistorySelectAllRowsCheckbox();
        }
    );
    $historyDialog.dialog("open");

    return false;
}

function closeHistoryDialog() {
    $("#history_dialog").dialog('close');
}

function isHistoryDialogActive() {
    return !!$("#history_dialog").attr('active');
}

function disposeTool() {
    var toolNo      = $('#field3_issues').val();

    var $disposeToolDialog = $("#dispose_tool_dialog");
    $disposeToolDialog.load('<?php echo $this->url(array('action' => 'dispose-tool'))?>', { toolNo: toolNo });
    $disposeToolDialog.dialog("open");

    return false;
}

function closeDisposeToolDialog() {
    $("#dispose_tool_dialog").dialog('close');
}

function isDisposeToolDialogActive() {
    return !!$("#dispose_tool_dialog").attr('active');
}

function printProduct() {
    $.getJSON("/minder/otc/print-product-ajax",{},
        function (response)
        {
            if (response.errors && response.errors.length > 0)
                showErrors(response.errors);

            if (response.warnings && response.warnings.length > 0)
                showWarnings(response.warnings);

            if (response.messages && response.messages.length > 0)
                showMessage(response.messages);
        }
    );
}

function printTool() {
    $.getJSON("/minder/otc/print-tool-ajax",{},
        function (response)
        {
            if (response.errors && response.errors.length > 0)
                showErrors(response.errors);

            if (response.warnings && response.warnings.length > 0)
                showWarnings(response.warnings);

            if (response.messages && response.messages.length > 0)
                showMessage(response.messages);
        }
    );
}

function printBorrower() {
    $.getJSON("/minder/otc/print-borrower-ajax",{},
        function (response)
        {
            if (response.errors && response.errors.length > 0)
                showErrors(response.errors);

            if (response.warnings && response.warnings.length > 0)
                showWarnings(response.warnings);

            if (response.messages && response.messages.length > 0)
                showMessage(response.messages);
        }
    );
}

$(function() {
    var
        $barcode = $('#barcode');

    $barcode.minderBarcodeInput();
    <?php foreach ($this->giParams as $paramDescription) {?>
        $barcode.minderBarcodeInputAddDescriptors([<?php echo $paramDescription;?>]);
    <?php }?>

    <?php if ($this->minder->isAdmin) {?>
    function updateButtonTitles() {
        var
            buttonPrefixes = $('#barcode').minderBarcodeInputGetPrefixes('SCREEN_BUTTON');

        $('input[type="button"][data-barcode], button[data-barcode]').each(function() {
            var
                $this = $(this),
                command = $this.attr('data-barcode'),
                barcode = buttonPrefixes.map(function(prefix){return prefix + command}).join(', ');

            if (barcode) {
                $this.attr('title', 'Button Barcode: ' + barcode);
            }
        });
    }

    updateButtonTitles();
    <?php }?>

    $('#otc_printer_select').change(onOtcPrinterSelectChange);

    Otc.Dlg.Query.setCloseListener(function(){
        $barcode.focus();
    }, 'otc-main');

    otcLog('OTC Page Loaded');
});

function onOtcPrinterSelectChange(evt) {
    $.post(
        '<?php echo $this->url(array(), 'setLimit');?>',
        {
            'printer': $(this).val()
        },
        null,
        'json'
    );
}

function otcLog(message) {
    $.post(
        '<?php echo $this->baseUrl()?>/service/otc_log.php',
        {'message': message, 'timestamp' : (new Date()).toISOString()}
    );
}

function resizeDialogContent($dialog) {
    var $container = $dialog.parents('.ui-resizable'),
        footerHeight = Math.ceil(parseFloat($dialog.find('.mdr-dialog-footer').css('height')) || 0),
        headerHeight = Math.ceil(parseFloat($dialog.find('.mdr-dialog-header').css('height')) || 0),
        dialogHeight = Math.ceil(parseFloat($container.css('height')) || 0),
        buttonsHeight = Math.ceil(parseFloat($container.find('.ui-dialog-buttonpane').css('height')) || 0);

    $dialog.find('.mdr-dialog-content').css('height', dialogHeight - footerHeight - headerHeight - buttonsHeight - 60 + 'px');
}

//disable default globalSearch() method
function globalSearch(e) {

removeMessages();
removeErrors();   
removeWarnings();
$('.restore-errors').remove();



}


</script>

<?php echo $this->render('footer.phtml'); ?>
