<?php

/**
 * Make Excel structure.
 */
// Create format for title, header and footer.
$format = $this->xls->addFormat();
$format->setBold();

$this->worksheet = $this->xls->addWorksheet('test');

// Append title.
$this->worksheet->setMerge(0, 0, 0, count($this->headers));

// Append header.
$column = 0;
foreach ($this->headers as $key => $value) {
    $this->worksheet->write(1, $column, $key, $format);
    $column++;
}

$this->currentRow = 2;
