<script type="text/javascript">
<!--//
function showWait()
{
    //document.getElementById('wait').style.display = 'block';
}
function hideWait()
{
    //document.getElementById('wait').style.display = 'none';
}
//-->
</script>
<!--
            <div id="wait_submit" style="position:absolute;z-index: 90;top:50%;left:50%;align:center;valign:middle;width:100px;height:60px;float:left;display:none;">
                <div style="top:-50px;left:-30px;border:2px groove">
                    <table border="3" width="100%" height="100%" style="background:#B1DB87">
                        <tr valign="middle">
                            <td>
                                <center><h2>Loading...</h2></center>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
-->
                <div id="wait" style="background:#B1DB87;display:none">
                    <center><h2>Loading...</h2></center>
                </div>
                </div>
            </div>
        </div>
        <div id="footer">
            <p>&copy; <?php echo date('Y'); ?> <a href="http://www.barcoding.com.au/">Barcoding &amp; Data Collection Systems Pty Limited</a>. All Rights Reserved.</p>
        </div>
    </body>
</html>
