<?php echo $this->render('header.phtml'); ?>

<?php echo $this->messenger()->all();?>

<h2 title="<?php echo $this->ssnSysScreenName;?>">Search <?php echo $this->escape($this->pageTitle);?></h2>

<div id="search_form_container">
    <?php echo $this->sysScreenSearchForm2($this->ssnSysScreenName, array('search_fields' => $this->searchFields, 'extra_buttons' => array('ADD_SSN' => 'ADD OBJECT', 'CREATE_SSN' => 'CREATE OBJECT')));?>
</div>

<script type="text/javascript">
    $("#ssn_search_form").find('input, select').change(function(evt){
        var $target = $(evt.target);
        $("#ssn_search_form").find('[name="' + $target.attr('name') + '"]').val($target.val());
    });

    $('#SEARCH_RESULTS_FORM .ADD_SSN').click(function(evt){
        evt.preventDefault();
        location.href = '<?php echo $this->url(array('module' => 'warehouse', 'controller' => 'ssn', 'action' => 'add'), null, true)?>';
    });

    $('#SEARCH_RESULTS_FORM .CREATE_SSN').click(function(evt){
        evt.preventDefault();
        location.href = '<?php echo $this->url(array('module' => 'warehouse', 'controller' => 'ssn', 'action' => 'create-ssn'), null, true)?>';
    });

</script>

<?php
    $resultsForm = $this->getHelper('SysScreenSearchResult');
    $resultsForm->setTabs($this->tabs)->setFields($this->fields)->setActions($this->actions);
?>

<div id="SSN_LIST_CONTAINER">
<form name="ssn_result_form" id="ssn_result_form" action="<?php echo $this->url(); ?>" method="post">
    <!-- tabs container start -->
    <div id="ssn_tabs" class="ui-tabs-container">
        <?php echo $resultsForm->renderTabsList(array()); ?>

        <div  class="ui-tabs-panel-header">
            <div class="sys-screen-title" title="<?php echo $this->ssnSysScreenName;?>">SSN List<span class="modification_flag <?php echo $this->rowSelectionNamespace;?>"></span></div>
            <div class="paginator-container">
                <?php echo $this->formLabel('select_complete_label', 'Select All Rows on all pages', array('disableFor' => true));?>
                <?php echo $this->formCheckbox('select_complete', 0, array('checked' => ($this->totalSsns == $this->selectedSsnsCount), 'row_id' => 'select_complete', 'class' => 'select_complete ' . $this->rowSelectionNamespace));?>
                <label for="results_per_page">View By:</label>
                <?php echo $this->formSelect('show_by', 
                                                $this->navigation['show_by'],
                                                array('class' => 'show_by'),
                                                array(5  => 5,
                                                      10 => 10,
                                                      15 => 15,
                                                      20 => 20,
                                                      30 => 30,
                                                      40 => 40,
                                                      50 => 50,
                                                      100 => 100)) ?>
                <label for="page">Page:</label>
                <?php echo $this->formSelectStrict('pageselector',
                                                    $this->navigation['pageselector'],
                                                    array('class' => 'pageselector'),
                                                    $this->pages); ?>
            </div>
             
            <ul class="black-top-border" style="clear: both;">
                <li style="display: inline;">Selected: <span class="selected_count <?php echo $this->rowSelectionNamespace;?>"><?php echo $this->selectedSsnsCount;?></span></li>
            </ul>
        </div>

        <?php foreach ($resultsForm->getTabs() as $tabId => $tabCaption) {?>
            <?php echo $resultsForm->renderTab($tabId, array(), false);?>
                <?php echo $resultsForm->renderTabContent(
                                        $tabId, 
                                        array(
                                            'select_all_checked'    => (count($this->ssns) == count($this->selectedSsns)), 
                                            'selection_namespace'   => $this->rowSelectionNamespace, 
                                            'switch_selection_mode' => $this->selectMode,
                                            'tab_content_class'     => 'withborder tablesorter ssn_details'
                                        ), 
                                        $this->ssns, 
                                        $this->selectedSsns
                );?>

                <!-- totals info start -->
                <table class="withborder" width="100%">
                    <tr>
                        <td>Total <span class="total_count <?php echo $this->rowSelectionNamespace;?>"><?php echo $this->numRecords;?></span> records.<?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno); ?></td>
                    </tr>
                </table>
                <!-- totals info end -->
           </div>    
        <?php }?>

        <div style="clear: both; padding-left: 10px; padding-top: 10px;">
            <ul class="toolbar">
                <li><input type="submit" name="report_format" id="report_csv_btn" value="REPORT: CSV" onclick="return false;" /></li>
                <li><input type="submit" name="report_format" id="report_xls_btn" value="REPORT: XLS" onclick="return false;" /></li>
            </ul>
        </div>
    </div>
    <!-- tabs container end -->
</form>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#SSN_LIST_CONTAINER #ssn_tabs > ul').tabs();

        $('.ssn_details').tablesorter({headers:{0:{sorter:false}}, widgets: ['zebra']});
        
        $('#SSN_LIST_CONTAINER .row_selector.<?php echo $this->rowSelectionNamespace;?>, #SSN_LIST_CONTAINER .select_all_rows.<?php echo $this->rowSelectionNamespace;?>, #SSN_LIST_CONTAINER .select_complete.<?php echo $this->rowSelectionNamespace;?>').minderRowSelector(
            '<?php echo $this->url(array('module' => $this->rowSelectionModule, 'controller' => $this->rowSelectionController, 'action' => $this->rowSelectionAction), null, true);?>',
            {
                'scopeSelector'       : '#SSN_LIST_CONTAINER',
                'selectionNamespace'  : '<?php echo $this->rowSelectionNamespace?>',
                'selectionAction'     : '<?php echo $this->rowSelectionAction;?>',
                'selectionController' : '<?php echo $this->rowSelectionController;?>'
            }
        );        

        $('#SSN_LIST_CONTAINER .pageselector, #SSN_LIST_CONTAINER .show_by').change(function(){
            $('#ssn_result_form').submit();
        });
        
        $('#report_csv_btn, #report_xls_btn').click(function(evt){
            evt.preventDefault();
            location.href = '<?php echo $this->url(
                array(
                    'module' => $this->reportModule, 
                    'controller' => $this->reportController, 
                    'action' => $this->reportAction, 
                    'selection_namespace' => $this->rowSelectionNamespace,
                    'selection_action' => $this->rowSelectionAction,
                    'selection_controller' => $this->rowSelectionController
                ),
                null, 
                true
            );?>' + '/report_format/' + escape($(this).val());
        });

        $('#SSN_LIST_CONTAINER .ssn_details .data_set label').each(function(){
            
            //replece all labels with hyperlink to show page

            var $this = $(this);
            var ssnId      = $this.parents('#SSN_LIST_CONTAINER .ssn_details .data_set tr').find('.SSN_ID').html();
            var tmpClasses = $this.attr('class');

//            var rowId = $(this).attr('row-id');
            var newHyperlink = $('<a href="<?php echo $this->url(array('module' => 'warehouse', 'controller' => 'ssn', 'action' => 'edit'), null, true);?>/edit_ssn_ssn_id/' + ssnId + '"></a>');
            newHyperlink.attr('class', tmpClasses);

            if ($this.attr('data-number-format') !== undefined)
                newHyperlink.attr('data-number-format', $this.attr('data-number-format'));

            $this.after(newHyperlink);
            newHyperlink.append($this.html());
            $this.remove();
        });

        $('[data-number-format]').minderNumberFormat();
    });

</script>
<?php echo $this->render('footer.phtml'); 
