<?php echo $this->render('header.phtml'); ?>

<h2><?php echo $this->escape($this->pageTitle)?></h2>

<?php
echo $this->messenger()->all();
if ($this->hasErrors) {
    echo $this->render('footer.phtml');
    return;
}
?>

<h3 title="<?php echo  $this->linesModel; ?>">Items List:</h3>

<?php echo $this->sysScreenSearchForm2($this->linesModel, array('title' => $this->linesModel, 'id' => 'lines-search-form', 'search_fields' => $this->searchFields)); ?>

<div id="lines-container"></div>

<script type="text/javascript">
    function onDataReady(response) {
        if (response.errors && response.errors.length > 0)
            showErrors(response.errors);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        for (var namespace in response.sysScreens) {
            if (response.sysScreens.hasOwnProperty(namespace))
                $('#' + getContainerId(namespace)).minderSearchResult(response.sysScreens[namespace]);
        }

        $(document).dequeue();
    }

    function loadData(namespace) {
        var dataToSend = {
            'sysScreens' : {}
        };

        var containerId = getContainerId(namespace);

        dataToSend.sysScreens[namespace] = {
            'paginator' : $('#' + containerId).minderSearchGetPaginatorState()
        };

        $(document).queue(function() {
            $('#' + containerId + ' > div').block($('<?php echo $this->SysScreenWaitPrompt();?>'));
            $.post(
                '<?php echo $this->url(array('action' => 'get-dataset'));?>',
                dataToSend,
                onDataReady,
                'json'
            );
        }).queue(function() {
                $('#' + containerId + ' > div').unblock();
                $(this).dequeue();
            });
    }

    function getContainerId(namespace) {
        switch (namespace) {
            case '<?php echo $this->linesNamespace;?>':
                return 'lines-container';
            default:
                throw 'Unknown namespace "' + namespace + '"';
        }
    }

    function getSearchFormId(namespace) {
        switch (namespace) {
            case '<?php echo $this->linesNamespace;?>':
                return 'lines-search-form';
            default:
                throw 'Unknown namespace "' + namespace + '"';
        }
    }

    function getNamespace(sysScreen) {
        switch (sysScreen) {
            case '<?php echo $this->linesModel;?>':
                return '<?php echo $this->linesNamespace;?>';
            default:
                throw 'Unknown SYS_SCREEN "' + sysScreen + '"';
        }
    }

    function getRowsOnPage(namespace) {
        return $('#' + getContainerId(namespace) + ' .data-set:first tr').length;
    }

    function setSelection(namespace, sysScreen) {
        $('.selected-container.' + namespace).html(sysScreen.selectedRowsTotal);

        var rowsOnPage = getRowsOnPage(namespace);

        var totalRows  = parseInt($('.total-container.' + namespace).html());
        totalRows = isNaN(totalRows) ? 0 : totalRows;

        if (rowsOnPage == sysScreen.selectedRowsOnPage) {
            $('.select_all_rows.' + namespace).attr('checked', true);
        } else {
            $('.select_all_rows.' + namespace).removeAttr('checked');
        }

        if (totalRows == sysScreen.selectedRowsTotal) {
            $('.select_complete.' + namespace).attr('checked', true);
        } else {
            $('.select_complete.' + namespace).removeAttr('checked');
        }

        $('.row_selector.' + namespace).each(function(){
            var $_this = $(this);
            var thisRowId = $_this.attr('row_id');

            if (sysScreen.selectedRows[thisRowId]) {
                $_this.attr('checked', true);
            } else {
                $_this.removeAttr('checked');
            }
        });

    }

    function tabContainerOnSelectRowCallback(response) {
        if (response.errors && response.errors.length > 0)
            showErrors(response.errors);

        if (response.warnings && response.warnings.length > 0)
            showWarnings(response.warnings);

        if (response.messages && response.messages.length > 0)
            showMessage(response.messages);

        $.each(response.sysScreens, setSelection);

        $(document).dequeue();
    }

    function tabContainerOnSelectRow(evt) {
        var containerId = getContainerId(evt.namespace);

        var dataToSend = {
            'sysScreens' : {}
        };

        dataToSend.sysScreens[evt.namespace]  = {
            'paginator' : $('#' + containerId).minderSearchGetPaginatorState(),
            'rowId'     : evt.rowId,
            'state'     : evt.rowState
        };

        $(document).queue(function() {
            $('#' + containerId + ' > div').block($('<?php echo $this->SysScreenWaitPrompt('Selecting row. Please wait...');?>'));
            $.post(
                '<?php echo $this->url(array('action' => 'select-row'));?>',
                dataToSend,
                tabContainerOnSelectRowCallback,
                'json'
            );
        }).queue(function() {
                $('#' + containerId + ' > div').unblock();
                $(this).dequeue();
            });
    }

    function linesContainerOnPageChanged() {
        loadData('<?php echo $this->linesNamespace?>');
    }

    function linesContainerOnShowByChanged() {
        loadData('<?php echo $this->linesNamespace?>');
    }

    function linesContainerOnPreSort() {

    }

    function linesContainerOnSort() {
        loadData('<?php echo $this->linesNamespace?>');
    }

    function doSearch(searchParams, namespace) {
        var dataToSend = searchParams;
        dataToSend.push({
            'name': 'namespace',
            'value': namespace
        });

        dataToSend.push({
            'name': 'sysScreens[' + namespace + ']',
            'value': []
        });

        $('#barcode').val('').parent().block();
        $('#' + getSearchFormId(namespace)).block();
        $(document).queue(function() {
            $('#' + getContainerId(namespace) + ' > div').block($('<?php echo $this->SysScreenWaitPrompt('Applying filter...');?>'));

            $.post(
                '<?php echo $this->url(array('action' => 'search'));?>',
                dataToSend,
                onDataReady,
                'json'
            );
        }).queue(function() {
                $('#' + getContainerId(namespace) + ' > div, #' + getSearchFormId(namespace)).unblock();
                $('#barcode').parent().unblock();
                $(this).dequeue();
            });
    }

    function lineSearchFormOnDoSearch(evt) {
        doSearch(evt.searchParams, '<?php echo $this->linesNamespace?>');
    }

    function lineSearchBtnOnClick(evt) {
        evt.preventDefault();
        var searchEvent = $.Event('do-search');
        searchEvent.searchParams = $('#lines-search-form').serializeArray();
        $('#lines-search-form').trigger(searchEvent);
    }

    function makeReport(format, sysScreen) {
        location.href = '<?php echo $this->url(array('action' => 'report'));?>/report_format/' + escape(format) + '/namespace/' + escape(getNamespace(sysScreen));
    }

    function getSelectedRowsAmount(namespace) {
        var result = parseInt($('.selected-container.' + namespace + ':first').text());
        return isNaN(result) ? 0 : result;
    }

    function amendPickedItems() {
        var
            namespace = '<?php echo $this->linesNamespace?>',
            containerId = getContainerId(namespace),
            dataToSend = {
                sysScreens: {}
            },
            selectedItems = getSelectedRowsAmount(namespace);

        dataToSend.sysScreens[namespace] = {
            'paginator' : $('#' + containerId).minderSearchGetPaginatorState()
        };

        if (selectedItems < 1) {
            showWarnings(['No rows selected. Please select one.']);
            return;
        }

        $('#barcode').val('').parent().block();
        $('#' + getSearchFormId(namespace)).block();
        $(document).queue(function() {
            $('#' + getContainerId(namespace) + ' > div').block($('<?php echo $this->SysScreenWaitPrompt('Amending...');?>'));

            $.post(
                '<?php echo $this->url(array('action' => 'amend-items'));?>',
                dataToSend,
                onDataReady,
                'json'
            );
        }).queue(function() {
            $('#' + getContainerId(namespace) + ' > div, #' + getSearchFormId(namespace)).unblock();
            $('#' + getSearchFormId(namespace)).unblock();
            $('#barcode').parent().unblock();
            $(this).dequeue();
        });

    }

    $(document).ready(function(){
        var $_linesContainer = $('#lines-container');
        if ($_linesContainer.length > 0) {
            $_linesContainer.minderSearchResult(<?php echo json_encode($this->linesJsSearchResults);?>);
            $_linesContainer.minderSearchResult({autosorter: true, customSort: true});
            $_linesContainer.minderSearchResult(<?php echo json_encode($this->linesJsSearchResultsDataset);?>);

            $_linesContainer
                .bind('select-row', tabContainerOnSelectRow)
                .bind('page-changed', linesContainerOnPageChanged)
                .bind('show-by-changed', linesContainerOnShowByChanged)
                .bind('pre-sort', linesContainerOnPreSort)
                .bind('sort', linesContainerOnSort);

            $('#lines-search-form').bind('do-search', lineSearchFormOnDoSearch);
            $('#lines-search-form .lines-search-form_search_btn').bind('click', lineSearchBtnOnClick);
        }
    });

</script>


<script type="text/x-jquery-tmpl" id="buttons-tmpl">
    <div style="clear: both; padding-left: 10px;">
        {{if $item.data.buttons.length > 0}}
        <ul class="toolbar">
            {{each $item.data.buttons}}
                {{if $item.data.namespace != '<?php echo $this->linesNamespace?>' || $value.SSB_BUTTON_NAME != 'UPDATE_PENDING_ACTION'}}
                    {{if $value.SSB_TITLE.toUpperCase() == '_GROUP_SEPARATOR'}}
                        </ul><ul class="toolbar">
                    {{else}}
                        <li><button onclick="return false;" title="{{= $value.SSB_BUTTON_NAME}}" class="green-button SCREEN_BUTTON_{{= $value.RECORD_ID}}" name="{{= $value.SSB_BUTTON_NAME}}">{{= $value.SSB_TITLE}}</button></li>
                    {{/if}}
                {{/if}}
            {{/each}}
        </ul>
        {{/if}}
    </div>
</script>

<?php echo $this->StandardSRTemplate(array('SRDefaultButtons'));?>

<?php echo $this->render('footer.phtml');

