<?php echo $this->render('header.phtml'); ?>
<form name="main" action="" method="post">
<?php
    if (!isset($this->action)) {
        echo $this->render('/ssn/issnlist.phtml');
?>
    <h2>EDIT : <?php echo $this->escape($this->ssnObj->id); ?></h2>
<?php
    } else {
?>
     <h2><?php echo $this->pageTitle; ?></h2>
<?php
    }
    echo $this->messenger()->all();
?>
    <ul class="toolbar">
        <li><?php echo $this->formSubmit('action', 'SAVE & RETURN', array('onclick' => 'return goDelete();')); ?></li>
        <li><?php echo $this->formSubmit('action', 'CANCEL CHANGES'); ?></li>
    </ul>

    <?php
    switch ($this->formStyle) {
        case 'simplified':
            echo $this->render('/ssn/create-ssn/simplified.phtml');
            break;
        default:
            echo $this->render('/ssn/create-ssn/default.phtml');
    }
    ?>

    <ul class="toolbar">
        <li><?php echo $this->formSubmit('action', 'SAVE & RETURN', array('onclick' => 'return goDelete();')); ?></li>
        <li><?php echo $this->formSubmit('action', 'CANCEL CHANGES'); ?></li>
    </ul>
</form>
<?php echo $this->render('footer.phtml');