<?php echo $this->render('header.phtml'); ?>
<?php
    echo $this->messenger()->all();
 
    $attributes = array('autocomplete' => 'off', 'onkeyup' => 'checkKeys(event)');
    //$attributesForSelect = array('onchange'=>'seek_changed(this.name)');
    $attributesForSelect = array();
?>

<form name="main" id="main" action="<?php echo $this->url(array('module' => 'warehouse', 'controller' => 'ssn', 'action' => 'index', 'from' => $this->from), null, true); ?>" method="post">
<input type="hidden" name="from" value="<?php echo $this->from; ?>" id="from" />
<h2><?php echo $this->pageTitle; ?></h2>
            <ul class="toolbar">
                <li><?php echo $this->formSubmit('tabs', 'Basic',       array('onclick' => 'return showBasic()')); ?></li>
                <li><?php echo $this->formSubmit('tabs', 'Other',       array('onclick' => 'return showOther()')) ?></li>
                <li><?php echo $this->formSubmit('tabs', 'Condition',   array('onclick' => 'return showCondition()')) ?></li>
            </ul>
    <div id="search_tabs" style="width:99%;">

        <div id="basic_tab">
            <table width="100%">
                <tr>
                    <th class="rightalign" width="16%"><b>SSN #:</b></th>
                    <td width="16%"><?php echo $this->formText('ssn_id', selectFilterValue('ssn_id', $this->conditions), $attributes); ?></td>
                    <th class="rightalign" width="16%">Company ID:</th>
                    <td width="16%"><?php echo $this->formSelectStrict('company_id', selectFilterValue('company_id', $this->conditions), '', $this->companyIdList); ?></td>
                    <th class="rightalign" width="16%">Supplier ID:</th>
                    <td width="20%"><?php echo $this->formSelectStrict('supplier_id', selectFilterValue('supplier_id', $this->conditions), '', $this->supplierIdList); ?></td>
                </tr>
                <tr>
                    <th class="rightalign">GRN #:</th>
                    <td><?php echo $this->formText('grn', selectFilterValue('grn', $this->conditions), $attributes); ?></td>
                    <th class="rightalign">Purchase Order:</th>
                    <td><?php echo $this->formText('po_order', selectFilterValue('po_order', $this->conditions), $attributes); ?></td>
                    <th class="rightalign">&nbsp;</th>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <th class="rightalign">Description:</th> 
                    <td colspan="6">
                        <?php echo $this->formText('ssn_description', selectFilterValue('ssn_description', $this->conditions), array('style' => 'width:528px;')); ?>    
                    </td>
                </tr>
                <tr>
                    <th class="rightalign"><?php echo $this->minder->getLabelName('SSN', 'SSN_TYPE'); ?>:</th>
                    <td><?php echo $this->formSelectStrict('ssn_type',
                                                           selectFilterValue('ssn_type', $this->conditions),
                                                           array('onchange' => 'updateSsnTypeII()'),
                                                           $this->ssnTypeList); ?></td>
                    <th class="rightalign"><?php echo $this->minder->getLabelName('SSN', 'GENERIC'); ?>:</th>
                    <td><?php echo $this->formSelectStrict('generic',
                                                           selectFilterValue('generic', $this->conditions),
                                                           array('onchange' => 'updateSsnTypeIII()'),
                                                           $this->varietyList); ?></td>
                    <th class="rightalign"><?php echo $this->minder->getLabelName('SSN', 'SUB_TYPE'); ?>:</th>
                    <td><?php echo $this->formSelectStrict('ssn_sub_type',
                                                           selectFilterValue('ssn_sub_type', $this->conditions),
                                                           array(),
                                                           $this->ssnSubTypeList); ?></td>
                </tr>
                <tr>
                    <th class="rightalign"><?php echo $this->minder->getLabelName('SSN', 'BRAND'); ?>:</th>
                    <td><?php echo $this->formText('brand', selectFilterValue('brand', $this->conditions), $attributes); ?></td>
                    <th class="rightalign"><?php echo $this->minder->getLabelName('SSN', 'MODEL'); ?>:</th>
                    <td><?php echo $this->formText('model', selectFilterValue('model', $this->conditions), $attributes); ?></td>
                    <th class="rightalign">Serial Number #:</th>
                    <td><?php echo $this->formText('serial_number', selectFilterValue('serial_number', $this->conditions), $attributes); ?></td>
                </tr>
                <tr>
                    <th class="rightalign">Created Date From:</th>
                    <td><?php echo $this->formText('created_date_from', selectFilterValue('created_date_from', $this->conditions), $attributes); ?></td>
                    <th class="rightalign">Created Date To:</th>
                    <td><?php echo $this->formText('created_date_to', selectFilterValue('created_date_to', $this->conditions), $attributes); ?></td>
                    <th class="rightalign">Legacy ID:</th>
                    <td><?php echo $this->formText('legacy_id', selectFilterValue('legacy_id', $this->conditions), $attributes); ?></td>
                </tr>
            </table>
        </div>
        <div id="other_tab" style="display:none;">
            <hr/>
            <b>SSN OTHER Details:</b>
            <hr/>
            <table width="100%">
                <tr>
                    <?php if (array_key_exists(6, $this->otherNames)) { ?>
                        <td width="16%" class="rightalign"><?php echo $this->formNote('other6', $this->otherNames[6]);?>:</td>
                        <td width="16%"><?php
                                if ($this->otherType[6]) {
                                    echo $this->formSelectStrict('other6', selectFilterValue('other6', $this->conditions), array(), $this->otherDetails[6]);
                                } else {
                                    echo $this->formText('other6', selectFilterValue('other6', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="16%">&nbsp;</td>
                    <?php } ?>
                    <?php if (array_key_exists(7, $this->otherNames)) { ?>
                        <td class="rightalign" width="16%"><?php echo $this->formNote('other7', $this->otherNames[7]);?>:</td>
                        <td width="16%"><?php
                                if ($this->otherType[7]) {
                                    echo $this->formSelectStrict('other7', selectFilterValue('other7', $this->conditions), array(), $this->otherDetails[7]);
                                } else {
                                    echo $this->formText('other7', selectFilterValue('other7', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="16%">&nbsp;</td>
                    <?php } ?>
                    <?php if (array_key_exists(8, $this->otherNames)) { ?>
                        <td class="rightalign" width="16%"><?php echo $this->formNote('other8', $this->otherNames[8]);?>:</td>
                        <td width="20%"><?php
                                if ($this->otherType[8]) {
                                    echo $this->formSelectStrict('other8', selectFilterValue('other8', $this->conditions), array(), $this->otherDetails[8]);
                                } else {
                                    echo $this->formText('other8', selectFilterValue('other8', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="20%">&nbsp;</td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(9, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other9', $this->otherNames[9]);?>:</td>
                        <td><?php
                                if ($this->otherType[9]) {
                                    echo $this->formSelectStrict('other9', selectFilterValue('other9', $this->conditions), array(), $this->otherDetails[9]);
                                } else {
                                    echo $this->formText('other9', selectFilterValue('other9', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(10, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other10', $this->otherNames[10]);?>:</td>
                        <td><?php
                                if ($this->otherType[10]) {
                                    echo $this->formSelectStrict('other10', selectFilterValue('other10', $this->conditions), array(), $this->otherDetails[10]);
                                } else {
                                    echo $this->formText('other10', selectFilterValue('other10', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(11, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other11', $this->otherNames[11]);?>:</td>
                        <td><?php
                                if ($this->otherType[11]) {
                                    echo $this->formSelectStrict('other11', selectFilterValue('other11', $this->conditions), array(), $this->otherDetails[11]);
                                } else {
                                    echo $this->formText('other11', selectFilterValue('other11', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(12, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other12', $this->otherNames[12]);?>:</td>
                        <td><?php
                                if ($this->otherType[12]) {
                                    echo $this->formSelectStrict('other12', selectFilterValue('other12', $this->conditions), array(), $this->otherDetails[12]);
                                } else {
                                    echo $this->formText('other12', selectFilterValue('other12', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(13, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other13', $this->otherNames[13]);?>:</td>
                        <td><?php
                                if ($this->otherType[13]) {
                                    echo $this->formSelectStrict('other13', selectFilterValue('other13', $this->conditions), array(), $this->otherDetails[13]);
                                } else {
                                    echo $this->formText('other13', selectFilterValue('other13', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(14, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other14', $this->otherNames[14]);?>:</td>
                        <td><?php
                                if ($this->otherType[14]) {
                                    echo $this->formSelectStrict('other14', selectFilterValue('other14', $this->conditions), array(), $this->otherDetails[14]);
                                } else {
                                    echo $this->formText('other14', selectFilterValue('other14', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(15, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other15_date', $this->otherNames[15]);?>:</td>
                        <td><?php
                                if ($this->otherType[15]) {
                                    echo $this->formSelectStrict('other15_date', selectFilterValue('other15_date', $this->conditions), array(), $this->otherDetails[15]);
                                } else {
                                    echo $this->formText('other15_date', selectFilterValue('other15_date', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                        <td></td>
                        <td></td>
                    <?php if (array_key_exists(16, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other16_date', $this->otherNames[16]);?>:</td>
                        <td><?php
                                if ($this->otherType[16]) {
                                    echo $this->formSelectStrict('other16_date', selectFilterValue('other16_date', $this->conditions), array(), $this->otherDetails[16]);
                                } else {
                                    echo $this->formText('other16_date', selectFilterValue('other16_date', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(17, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other17_qty', $this->otherNames[17]);?>:</td>
                        <td><?php
                                if ($this->otherType[17]) {
                                    echo $this->formSelectStrict('other17_qty', selectFilterValue('other17_qty', $this->conditions), array(), $this->otherDetails[17]);
                                } else {
                                    echo $this->formText('other17_qty', selectFilterValue('other17_qty', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                        <td></td>
                        <td></td>
                    <?php if (array_key_exists(18, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other18_qty', $this->otherNames[18]);?>:</td>
                        <td><?php
                                if ($this->otherType[18]) {
                                    echo $this->formSelectStrict('other18_qty', selectFilterValue('other18_qty', $this->conditions), array(), $this->otherDetails[18]);
                                } else {
                                    echo $this->formText('other18_qty', selectFilterValue('other18_qty', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(19, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other19', $this->otherNames[19]);?>:</td>
                        <td><?php
                                if ($this->otherType[19]) {
                                    echo $this->formSelectStrict('other19', selectFilterValue('other19', $this->conditions), array(), $this->otherDetails[19]);
                                } else {
                                    echo $this->formText('other19', selectFilterValue('other19', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(20, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other20', $this->otherNames[20]);?>:</td>
                        <td><?php
                                if ($this->otherType[20]) {
                                    echo $this->formSelectStrict('other20', selectFilterValue('other20', $this->conditions), array(), $this->otherDetails[20]);
                                } else {
                                    echo $this->formText('other20', selectFilterValue('other20', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                        <td></td>
                        <td></td>
                </tr>
            </table>
        </div>
        <div id="condition_tab" style="display:none;">
            <hr/>
            <b>SSN Condition Details:</b>
            <hr/>
            <table width="100%">
                <tr>
                    <?php if (array_key_exists(1, $this->otherNames)) { ?>
                        <td width="16%" class="rightalign"><?php echo $this->formNote('other1', $this->otherNames[1]);?>:</td>
                        <td width="16%"><?php
                                if ($this->otherType[1]) {
                                    echo $this->formSelectStrict('other1', selectFilterValue('other1', $this->conditions), array(), $this->otherDetails[1]);
                                } else {
                                    echo $this->formText('other1', selectFilterValue('other1', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="16%">&nbsp;</td>
                    <?php } ?>
                    <?php if (array_key_exists(2, $this->otherNames)) { ?>
                        <td class="rightalign" width="16%"><?php echo $this->formNote('other2', $this->otherNames[2]);?>:</td>
                        <td width="16%"><?php
                                if ($this->otherType[2]) {
                                    echo $this->formSelectStrict('other2', selectFilterValue('other2', $this->conditions), array(), $this->otherDetails[2]);
                                } else {
                                    echo $this->formText('other2', selectFilterValue('other2', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="16%">&nbsp;</td>
                    <?php } ?>
                    <?php if (array_key_exists(3, $this->otherNames)) { ?>
                        <td class="rightalign" width="16%"><?php echo $this->formNote('other3', $this->otherNames[3]);?>:</td>
                        <td width="20%"><?php
                                if ($this->otherType[3]) {
                                    echo $this->formSelectStrict('other3', selectFilterValue('other3', $this->conditions), array(), $this->otherDetails[3]);
                                } else {
                                    echo $this->formText('other3', selectFilterValue('other3', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td width="16%">&nbsp;</td>
                        <td width="20%">&nbsp;</td>
                    <?php } ?>
                </tr>
                <tr>
                    <?php if (array_key_exists(4, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other4', $this->otherNames[4]);?>:</td>
                        <td><?php
                                if ($this->otherType[4]) {
                                    echo $this->formSelectStrict('other4', selectFilterValue('other4', $this->conditions), array(), $this->otherDetails[4]);
                                } else {
                                    echo $this->formText('other4', selectFilterValue('other4', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                    <?php if (array_key_exists(5, $this->otherNames)) { ?>
                        <td class="rightalign"><?php echo $this->formNote('other5', $this->otherNames[5]);?>:</td>
                        <td><?php
                                if ($this->otherType[5]) {
                                    echo $this->formSelectStrict('other5', selectFilterValue('other5', $this->conditions), array(), $this->otherDetails[5]);
                                } else {
                                    echo $this->formText('other5', selectFilterValue('other5', $this->conditions), $attributes);
                                }
                            ?>
                        </td>
                    <?php } else { ?>
                        <td></td>
                        <td></td>
                    <?php } ?>
                </tr>
                <tr>
                    <td colspan="6">
                        <fieldset >
                            <legend>Last Safety Check</legend>
                            <table width="100%">
                                <tr>
                                    <th class="rightalign" width="14%">Date From:</th>
                                    <td width="16%"><?php echo $this->formText('last_calibrate_check_date_from', selectFilterValue('last_calibrate_check_date_from', $this->conditions), $attributes); ?></td>
                                    <th class="rightalign" width="15%">Date To:</th>
                                    <td width="16%"><?php echo $this->formText('last_calibrate_check_date_to', selectFilterValue('last_calibrate_check_date_to', $this->conditions), $attributes); ?></td>
                                    <th width="16%">&nbsp;</th>
                                    <td width="23%">&nbsp;</td>
                                </tr>
                            </table>
                        </fieldset>
                    </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <fieldset>
                            <legend>Last Calibration Check</legend>
                            <table width="100%">
                                <tr>
                                    <th class="rightalign" width="14%">Date From:</th>
                                    <td width="16%"><?php echo $this->formText('last_safety_check_date_from', selectFilterValue('last_safety_check_date_from', $this->conditions), $attributes); ?></td>
                                    <th class="rightalign" width="15%">Date To:</th>
                                    <td width="16%"><?php echo $this->formText('last_safety_check_date_to', selectFilterValue('last_safety_check_date_to', $this->conditions), $attributes); ?></td>
                                    <th width="16%">&nbsp;</th>
                                    <td width="23%">&nbsp;</td>                            
                                </tr>
                            </table>
                        </fieldset>
                    </td>
                </tr>
            </table>
            </div>
        </div>
    <ul class="toolbar">
        <li><?php echo $this->formSubmit('action', 'SEARCH', array('onclick' => 'frmSubmit()')); ?></li>
        <li><?php echo $this->formSubmit('action', 'CLEAR', array('onclick' => 'return frmClear()')) ?></li>
<?php if ($this->from != 'pick-order' && $this->from != 'fso' && $this->from != 'transfer-order') : ?>
        <li><?php echo $this->formSubmit('action', 'ADD SSN', array('onclick' => 'frmSubmit()')); ?></li>
        <li><?php echo $this->formSubmit('action', 'CREATE SSN', array('onclick' => 'frmSubmit()')); ?></li>
<?php endif ?>
    </ul>
<?php if($this->tabShow) { ?>
    <div id="table-wrapper">
        <div style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <table style="width:99%">
                <tr>
                    <td>
                        <div style="float:left; font-weight: bold;">
                            Selected: <span  id="selected_num">0</span>
                        </div>
                    </td>
                    <?php if ($this->from == 'transfer-order' || $this->from == 'fso' || $this->from == 'pick-order2') : ?>
                    <td>
                        <div>
                            <b>
                                Total Selected Qty =
                                <?php echo $this->formText('total_qty', $this->qtyNonProducts, array('readonly' => true, 'style' => 'width:8ex;text-align:right;')); ?>
                            </b>
                        </div>
                    </td>
                    <td>
                        <div>
                            <b>
                                Required Qty for Order:
                                <?php echo $this->formText('required_qty', selectFilterValue('required_qty', $this->conditions), array('style' => 'width:8ex;text-align:right;')); ?>
                            </b>
                        </div>
                    </td>
                <?php endif ?>
                </tr>
            </table>
        </div>
        <div style="display:inline">
            Select All Rows on all pages
            <?php echo $this->formCheckbox('select_complete', null, null); ?>
            <label for='show_by'>View By : </label>
            <?php echo $this->formSelect('show_by',
                                         $this->navigation['show_by'],
                                         array('onchange' => 'frmSubmit()'),
                                         array(  5 => 5,
                                                10 => 10,
                                                15 => 15,
                                                20 => 20,
                                                30 => 30,
                                                40 => 40,
                                                50 => 50,
                                               100 => 100));?>
            <label for='page'>Page : </label>
            <?php echo $this->formSelectStrict('pageselector',
                                               $this->navigation['pageselector'],
                                               array('onchange' => 'frmSubmit()'),
                                               $this->pages); ?>
        </div>
        <table id="<?php echo $this->escape($this->tableId) ?>" class="withborder tablesorter">
            <thead>
            <tr>
            <th>
            <?php echo $this->formCheckbox('select_all',
                                           '',
                                           array('onclick' => 'selectAll(this)', 'checked' => $this->allSelected)) ;?>
            </th>
<?php
    foreach ($this->headers as $key => $header) {
        echo '<th abbr="' . $this->escape($key) . '">' . $this->escape($header) . '</th>';
    }
?>
            </tr>
            </thead>
            <tbody>
<?php
    if (count($this->ssns) > 0) {
        for ($i = 0; $i < count($this->ssns); $i++) {
            $ssnLine = $this->ssns[$i];
            echo '<tr>';
            echo '<th>';
            echo $this->formCheckbox($this->escape($ssnLine->id),
                                     $this->escape($ssnLine->id),
                                     array('class' => 'line_selector',
                                           'checked' => selectFilterValue($this->escape($ssnLine->id), $this->conditions),
                                           'onclick' => 'showSelected(this, \'auto\')'));
            echo '</th>';
            foreach($this->headers as $propertyName => $v) {
                    $val = $ssnLine->items[$propertyName];
                    $urlEdit = $this->url(array('module'      => 'warehouse',
                                                'controller'  => 'ssn',
                                                'action'      => 'edit'),
                                                '',
                                                true);
                          
                    if(isset($this->from)){
                        echo '<td><a href="'. $urlEdit .'/edit_ssn_ssn_id/'.$ssnLine->id.'/from/' . $this->from . '">'. $this->escape($val) . '</a></td>'."";
                    } else {
                        echo '<td><a href="'. $urlEdit .'/edit_ssn_ssn_id/'.$ssnLine->id.'">'. $this->escape($val) . '</a></td>'."";
                    }
            }
            echo "</tr>";
        }
    } else {
        // for tablesorter JavaScript plugin (if no row & cols in table - error occurs).
        echo "<tr><th/>";
        foreach($this->headers as $propertyName => $v) {
            echo "<td/>";
        }
        echo "</tr>\n";
    }
?>
            </tbody>
        </table>
        <div id="num_rec" style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">Total
            <?php echo $this->numRecords . " records. ";?>
            <?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); ?>
            <?php echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno);?>
        </div>
    </div>
<?php if ($this->from == 'fso' || $this->from == 'pick-order2' || $this->from == 'transfer-order') : ?>
    <ul class="toolbar" style="clear: both;">
        <li>
            <?php echo $this->formSubmit('action', 'ADD', array('onclick' => 'return frmSubmit();', 'class' => 'action_button'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'ADD & CONTINUE', array('onclick' => 'return frmSubmit();', 'class' => 'action_button'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'CANCEL ADD')?>
        </li>
    </ul>
<?php else : ?>
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: TXT', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: CSV', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XML', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XLS', array('onclick' => 'return frmSubmit();'))?>
        </li>
    </ul>
<?php endif ?>
<?php } ?> 
</form>

<script type="text/javascript">
<!--
var acc_closed = false;
var selectedNum = 0;
var cacheValue = 50;
$(document).ready( function (){
        $.ajaxSetup({async: false,
                     complete: onAjaxSuccess,
                     error: onAjaxError,
                     beforeSend: onAjaxBeforeSend});
        $("#table").tablesorter({headers: {0: {sorter:false}},sortList: false, widgets: ['zebra']});
        $('#table').dragCols({
            'drop': savePosition,
            'params': ['<?php echo $this->url(array('module'    => 'warehouse',
                                                   'controller' => 'settings',
                                                   'action'     => 'save-position')) ?>', 'ssn', 'index']
        });
        $("#search_tabs > ul").tabs();
        
        $("#create_date").datepicker({dateFormat: 'yy/mm/dd'});
        $("#created_date_from").datepicker({dateFormat: 'yy/mm/dd'});
        $("#created_date_to").datepicker({dateFormat: 'yy/mm/dd'});
        
        $("#other15_date").datepicker({dateFormat: 'yy/mm/dd'});
        $("#other16_date").datepicker({dateFormat: 'yy/mm/dd'});
        
        $("#last_calibrate_check_date_from").datepicker({dateFormat: 'yy/mm/dd'});
        $("#last_calibrate_check_date_to").datepicker({dateFormat: 'yy/mm/dd'});
        $("#last_safety_check_date_from").datepicker({dateFormat: 'yy/mm/dd'});
        $("#last_safety_check_date_to").datepicker({dateFormat: 'yy/mm/dd'});
        
        $("#select_complete").bind("click", selectWholeTable);

        showSelected($('#select_all').get(0), "init");
        
        $("#required_qty").bind("keyup", checkRequired);
<?php
foreach ($this->searchFields as $key => $val) {
$url = $this->url(array('module'     => 'warehouse',
                        'controller' => 'ssn',
                        'action'     => 'lookup'));
echo <<<JSCRIPT
        $('#$key').autocomplete('$url/',
                   {matchSubset: 1,
                    matchContains: 1,
                    cacheLength: cacheValue,
                    formatItem: formatItemWithoutDesc,
                    selectFirst: 1,
                    extraParams: {field: '$key'}});
\n
JSCRIPT;
}
?>
});

function limitChanged()
{
    frmSubmit();
    return true;
}

function formatItemWithoutDesc(ele)
{
    return ele[1];
}
function formatItemWithDesc(ele)
{
    return '<b>'+ele[0]+'</b><br/><i>'+ele[1]+'</i>';
}

function selectWholeTable()
{
    var chk = $('table input:checkbox', '#' + $(this).parent().parent()[0].id);
    var checkOnOff = this.checked;
    for (i=0; i < chk.length; i++) {
        chk[i].checked = checkOnOff;
    }
    calcOther(this, $($(this).parent().parent()[0]));
    return true;
}

function checkKeys(e)
{
    if (e.keyCode == 13) {
        frmSubmit();
    }
    return true;
}
function frmClear()
{
    $("#search_tabs input:text").each(function() {
        this.value = "";
    });
    
    $("#search_tabs select").each(function() {
        if (this.id != "show_by" && this.id != "pageselector") {
            this.selectedIndex = 0;
        }
    });
    
    return false;
}

function showBasic()
{
    //$("#basic_tab").show();
    $("#other_tab").hide();
    $("#condition_tab").hide();
    return false;
}
function showOther()
{
    $("#condition_tab").hide();
    $("#other_tab").show();
    return false;
}

function showCondition(){
    
    $("#condition_tab").show();
    return false;    
}

function calcOther(element, method)
{
    var countEl = 0;
    var from    = $('#from').val();
    if ('auto' == method) {
        var container_id = '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = element.checked;
    } else if ('init' == method) {
        var container_id =  '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = 'init';
    } else {
        var container_id = '#' + $(method)[0].id;
        var method = element.checked;
    }
    $.getJSON('<?php echo $this->url(array('action' => 'calc', 'controller' => 'ssn', 'module' => 'warehouse')); ?>',
             { field:       'QTY',
               inAction:    '<?php echo 'index'; ?>',
               activeTab:   container_id,
               method:      method,
               id:          element.id,
               value:       element.value,
               from:        from
             }, function(json) {
                   var answer = eval(json);
                   $("#selected_num", container_id).text(answer.selected_num);
                   $('#total_qty').val(answer.total_qty);
                   
                   checkRequired();
               });
}

<?php
$url = $this->url(array('module'     => 'warehouse',
                        'controller' => 'ssn',
                        'action'     => 'seek'));
?>
function updateSsnTypeII()
{
    $.ajax(
           {
            type: "GET",
            url: "<?php echo $url; ?>",
            cache: false,
            data: {
                   field:     "generic",
                   ssn_type: $("#ssn_type").get(0).value
            },
            success: function (data) {
                $("#generic").get(0).length = 0;
                var options = eval('(' + data + ')');
                var i = 0;
                $("#generic").get(0).options[i] = new Option('', '');
                for (var key in options) {
                    i++;
                    var newOpt = new Option(options[key], key);
                    $("#generic").get(0).options[i] = newOpt;
                }
            },
            error: function () {
                alert("Try again");
            }
           }
          );
}

function updateSsnTypeIII()
{
$.ajax(
       {
        type: "GET",
        url: "<?php echo $url; ?>",
        cache: false,
        data: {
            field:     "ssn_sub_type",
            ssn_type: $("#ssn_type").get(0).value,
            generic:  $("#generic").get(0).value
        },
        success: function (data) {
            $("#ssn_sub_type").get(0).length = 0;
            var options = eval('(' + data + ')');
            var i = 0;
            $("#ssn_sub_type").get(0).options[i] = new Option('', '');
            for (var key in options) {
                i++;
                var newOpt = new Option(options[key], key);
                $("#ssn_sub_type").get(0).options[i] = newOpt;
            }
        },
        error: function () {
            alert("Try again");
        }
       }
      );
}

function checkRequired(){
    
    var totalQty    =   parseInt($('#total_qty').val());
    var requiredQty =   parseInt($('#required_qty').val());
    
    if(totalQty >= requiredQty){
        $('#total_qty').css("background-color", "#00FF00");
        $('.action_button').removeAttr('disabled').removeClass('disabled');
    } else {
        $('#total_qty').css("background-color", "#FF0000");
        $('.action_button').attr('disabled', 'disabled').addClass('disabled');
    }
}
//-->
</script>
<?php echo $this->render('footer.phtml');
