<?php echo $this->render('header.phtml'); ?>
<?php
    $attributes = array('autocomplete' => 'off');
    $attributesForMassUpdate = array('autocomplete' => 'off', 'style' => 'width: 5em;');
    $attributesForSelect = array();
?>
<form name="main" id="main" action="<?php echo $this->url(); ?>" method="post">
<h2><?php echo $this->pageTitle; ?></h2>
                <table>
                    <tr>
                        <td>
                            Location ID:
                        </td>
                        <td>
                            <?php echo $this->formText('locn_id', selectFilterValue('locn_id', $this->conditions), $attributes); ?>
                        </td>
                        <td>
                            Location Name:
                        </td>
                        <td>
                            <?php echo $this->formText('locn_name', selectFilterValue('locn_name', $this->conditions), $attributes); ?>
                        </td>
                        <td>
                            Moveable Locn.:
                        </td>
                        <td>
                            <?php echo $this->formCheckbox('moveable_locn',
                                                           'T',
                                                           array('checked' => selectFilterValue('moveable_locn', $this->conditions))); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WH ID:
                        </td>
                        <td>
                            <?php echo $this->formText('wh_id', selectFilterValue('wh_id', $this->conditions), $attributes); ?>
                        </td>
                        <td>
                            Current Product:
                        </td>
                        <td>
                            <?php echo $this->formSelect('prod_id', selectFilterValue('prod_id', $this->conditions), $attributes, $this->productIdList); ?>
                        </td>
                        <td>
                            Current Empty Locns.:
                        </td>
                        <td>
                            <?php echo $this->formCheckbox('current_empty_locn',
                                                           'T',
                                                           array('checked' => selectFilterValue('current_empty_locn', $this->conditions))); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Transfer Status:
                        </td>
                        <td>
                            <?php echo $this->formSelect('move_stat', selectFilterValue('move_stat', $this->conditions), $attributes, $this->moveStatList); ?>
                        </td>
                        <td>
                            Location Status:
                        </td>
                        <td>
                            <?php echo $this->formSelect('locn_stat', selectFilterValue('locn_stat', $this->conditions), $attributes, $this->locnStatList); ?>
                        </td>
                        <td>
                            Replenishment Locn.:
                        </td>
                        <td>
                            <?php echo $this->formCheckbox('replenish',
                                                           'T',
                                                           array('checked' => selectFilterValue('replenish', $this->conditions))); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Storage Unit:
                        </td>
                        <td>
                            <?php echo $this->formSelect('locn_type', selectFilterValue('locn_type', $this->conditions), $attributes, $this->locnTypeList); ?>
                        </td>
                        <td>
                            Storage Type:
                        </td>
                        <td>
                            <?php echo $this->formSelect('store_type', selectFilterValue('store_type', $this->conditions), $attributes, $this->storeTypeList); ?>
                        </td>
                        <td>
                            Permission Level.:
                        </td>
                        <td>
                            <?php echo $this->formCheckbox('perm_level',
                                                           'T',
                                                           array('checked' => selectFilterValue('perm_level', $this->conditions))); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Inventory Area:
                        </td>
                        <td>
                            <?php echo $this->formSelect('store_area', selectFilterValue('store_area', $this->conditions), $attributes, $this->storeAreaList); ?>
                        </td>
                        <td>
                            Handling Method:
                        </td>
                        <td>
                            <?php echo $this->formSelect('store_meth', selectFilterValue('store_meth', $this->conditions), $attributes, $this->storeMethList); ?>
                        </td>
                        <td>
                            Temperature Zone:
                        </td>
                        <td>
                            <?php echo $this->formSelect('temperature_zone', selectFilterValue('temperature_zone', $this->conditions), $attributes, $this->temperatureZoneList); ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <fieldset>
                                <legend>Last Audited:</legend>
                                <ul class="toolbar">
                                    <li>
                                        From Date:
                                    </li>
                                    <li>
                                        <?php echo $this->formText('from_last_audited_date', selectFilterValue('from_last_audited_date', $this->conditions), $attributes); ?>
                                    </li>
                                    <li>
                                        Last Audited To Date:
                                    </li>
                                    <li>
                                        <?php echo $this->formText('to_last_audited_date', selectFilterValue('to_last_audited_date', $this->conditions), $attributes); ?>
                                    </li>
                                </ul>
                            </fieldset>
                        </td>
                    </tr>
                </table>
<?php if ($this->minder->isAdmin) { ?>
        <table>
        <tr>
            <td style="height:100%;">
                <table style="height:100%;">
                    <tr>
                        <td style="vertical-align:middle;">
                            <?php echo $this->formSubmit('action', 'SEARCH', array('onclick' => 'frmSubmit()')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align:middle">
                            <?php echo $this->formSubmit('action', 'CLEAR', array('onclick' => 'return frmClear()')) ?>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
            <fieldset>
                <table>
                    <tr>
                        <th rowspan="2">
                            <?php echo $this->formSubmit('action', 'MASS UPDATE', array("style" => "height:4em;", 'onclick' => 'frmSubmit()')); ?>
                        </th>
                        <td style="padding: 0.2em;">
                            Transfer Status:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('move_stat_upd', selectFilterValue('move_stat_upd', $this->conditions), $attributesForMassUpdate, $this->moveStatList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Unit Type:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('unit_type_upd', selectFilterValue('unit_type_upd', $this->conditions), $attributesForMassUpdate, $this->locnTypeList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Storage Type:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('store_type_upd', selectFilterValue('store_type_upd', $this->conditions), $attributesForMassUpdate, $this->storeTypeList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Permission Level:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formText('perm_level_upd', selectFilterValue('perm_level_upd', $this->conditions), $attributesForMassUpdate); ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 0.2em;">
                            Location Status:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('locn_stat_upd', selectFilterValue('move_stat_upd', $this->conditions), $attributesForMassUpdate, $this->locnStatList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Inventory Area:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('store_area_upd', selectFilterValue('store_area_upd', $this->conditions), $attributesForMassUpdate, $this->storeAreaList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Handling Method:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('store_meth_upd', selectFilterValue('store_meth_upd', $this->conditions), $attributesForMassUpdate, $this->storeMethList); ?>
                        </td>
                        <td style="padding: 0.2em;">
                            Temperature Zone:
                        </td>
                        <td style="padding: 0.2em;">
                            <?php echo $this->formSelect('temperature_zone_upd', selectFilterValue('temperature_zone_upd', $this->conditions), $attributesForMassUpdate, $this->temperatureZoneList); ?>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </td>
        </tr>
    </table>
<?php } else { ?>
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit('action', 'SEARCH', array('onclick' => 'frmSubmit()')); ?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'CLEAR', array('onclick' => 'return frmClear()')) ?>
        </li>
    </ul>
<?php } ?>
    <div id="tabs">
        <div style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <table style="width:99%">
                <tr>
                    <td>
                        <b>
                            <div style="float:left;">
                                Selected: <span  id="selected_num">0</span>
                            </div>
                        </b>
                    </td>
                </tr>
            </table>
        </div>
        <div style="display:inline">
            Select All Rows on all pages
            <?php echo $this->formCheckbox('select_complete', '', array()); ?>
            <label for='show_by'>View By : </label>
            <?php echo $this->formSelect('show_by',
                                         $this->navigation['show_by'],
                                         array('onchange' => 'frmSubmit()'),
                                         array(  5 => 5,
                                                10 => 10,
                                                15 => 15,
                                                20 => 20,
                                                30 => 30,
                                                40 => 40,
                                                50 => 50,
                                               100 => 100));?>
            <label for='page'>Page : </label>
            <?php echo $this->formSelectStrict('pageselector',
                                               $this->navigation['pageselector'],
                                               array('onchange' => 'frmSubmit()'),
                                               $this->pages); ?>
        </div>
        <table id="<?php echo $this->escape($this->tableId) ?>" class="withborder tablesorter" style="width:99%">
            <thead>
            <tr>
                <th>
                <?php echo $this->formCheckbox('select_all',
                                               '',
                                               array('onclick' => 'selectAll(this)'));?>
                </th>
<?php
    foreach ($this->headers as $key => $header) {
        echo '<th abbr="' . $this->escape($key) . '">'. $this->escape($header) . '</th>';
    }
?>
            </tr>
            </thead>
            <tbody>
<?php
    
    if (count($this->lines) > 0) {
        $urlEdit = $this->url(array('module'      => 'warehouse',
                                    'controller'  => 'location',
                                    'action'      => 'show'),
                              '',
                              true);
        
        for ($i = 0; $i < count($this->lines); $i++) {
            $line = $this->lines[$i];
            echo '<tr>';
            echo '<th class="line">';
            echo $this->formCheckbox($this->escape($line->id),
                                     $this->escape($line->id),

                                    array("class" => 'line_selector',
                                          'checked' => selectFilterValue($this->escape($line->id), $this->conditions),
                                          "onclick" => "showSelected(this, 'auto')"
                                    )); 
            echo '</th>';
            foreach($this->headers as $propertyName => $v) {
                    $val = $line->items[$propertyName];
                    echo '<td><a href="' . $urlEdit . '/locn_id/' . $line->items['LOCN_ID'] . '/wh_id/' . $line->items['WH_ID'] . '" >'. $this->escape($val) . '</a></td>';
                    //echo '<td>' . $this->escape($val) . '</td>'."";
            }
            echo "</tr>";
        }
    } else {
        // for tablesorter JavaScript plugin (if no row & cols in table - error occurs).
        echo "<tr><th/>";
        foreach($this->headers as $propertyName => $v) {
            echo "<td/>";
        }
        echo "</tr>\n";
    }
?>
            </tbody>
        </table>
        <div id="num_rec" style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">Total
            <?php echo $this->numRecords . " records. ";?>
            <?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); ?>
            <?php echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno);?>
        </div>
    </div>
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: TXT', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: CSV', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XML', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XLS', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
           <?php echo $this->formSubmit('action', 'PRINT LABEL', array('onclick' => 'frmSubmit();')); ?>
        </li>
    </ul>
</form>
<script type="text/javascript">
<!--
var cacheValue = 50;
$(document).ready( function () {
        $.ajaxSetup({async: false,
                     complete: onAjaxSuccess,
                     error: onAjaxError,
                     beforeSend: onAjaxBeforeSend});
        $("#table").tablesorter({headers: {0: {sorter:false}},sortList:[[1,0]], widgets: ['zebra']});
        $('#table').dragCols({
            'drop': savePosition,
            'params': ['<?php echo $this->url(array('module'    => 'warehouse',
                                                   'controller' => 'settings',
                                                   'action'     => 'save-position')) ?>', 'location', 'index']
        });
        $("#tabs #select_complete").bind("click", selectWholeTable);
        $('#from_last_audited_date').datepicker({dateFormat: 'yy/mm/dd'});
        $('#to_last_audited_date').datepicker({dateFormat: 'yy/mm/dd'});

        showSelected($("#table #select_all").get(0), "init");
<?php

foreach ($this->searchFields as $key => $val) {
$url = $this->url(array('module'     => 'warehouse',
                        'controller' => 'location',
                        'action'     => 'lookup'));
echo <<<JSCRIPT
        $('#$key').autocomplete('$url/',
                   {matchSubset: 1,
                    matchContains: 1,
                    cacheLength: cacheValue,
                    formatItem: formatItemWithDesc,
                    selectFirst: 1,
                    extraParams: {field: '$key'}});
\n
JSCRIPT;
}
?>
});

function limitChanged()
{
    frmSubmit();
    return true;
}

function formatItemWithoutDesc(ele)
{
    return ele[1];
}
function formatItemWithDesc(ele)
{
    return '<b>'+ele[0]+'</b><br/><i>'+ele[1]+'</i>';
}

function selectWholeTable()
{
    var chk = $('table input:checkbox', '#' + $(this).parent().parent()[0].id);
    var checkOnOff = this.checked;
    for (i=0; i < chk.length; i++) {
        chk[i].checked = checkOnOff;
    }
    calcOther(this, $($(this).parent().parent()[0]));
    return true;
}

function frmClear()
{
    $("form#main input:text").each(function() {
        this.value = "";
        });
    $("form#main select").each(function() {
        if (this.id != "show_by" && this.id != "pageselector") {
            this.selectedIndex = 0;
        }
        });
    return false;
}

function calcOther(element, method)
{
    var countEl = 0;
    if ('auto' == method) {
        var container_id = '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = element.checked;
    } else if ('init' == method) {
        var container_id =  '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = 'init';
    } else {
        var container_id = '#' + $(method)[0].id;
        var method = element.checked;
    }
    $.getJSON('<?php echo $this->url(array('action' => 'calc', 'controller' => 'location', 'module' => 'warehouse')); ?>',
             { field: 'QTY',
               inAction: '<?php echo 'index'; ?>',
               activeTab: container_id,
               method: method,
               id: element.id,
               value: element.value }, function(json) {
                   var answer = eval(json);
                   $("#selected_num", container_id).text(answer.selected_num);
               });
}

function show(n)
{
    frmSubmit();
    return true;
}

function frmSubmit()
{
    //$("#active_tab").val($("#tabs > ul").tabsSelected());
    document.main.submit();
    return true;
}
function printLocation()
{
    $.getJSON('<?php echo $this->url(array('action' => 'location-print', 'controller' => 'printer', 'module' => 'default')); ?>/',
           {
               cnt: 'location',
               act: 'index',
               prn: $('#limit_printer')[0].value},
               function (result)
               {
                   var answer = eval(result);
                   alert(answer.message);
               });
    return false;
}
//-->
</script>
<?php echo $this->render('footer.phtml');
