<?php

class Minder_SysScreen_PartBuilder_Table extends Minder_SysScreen_PartBuilder {
    protected $_partName                      = 'TABLE';
    protected $_tableName                     = 'SYS_SCREEN_TABLE';
    protected $_orderByFieldName              = 'SST_SEQUENCE';

    protected $_staticLimitsUserExpression    = 'SST_USER_TYPE';
    protected $_staticLimitsDeviceExpression  = 'SST_DEVICE_TYPE';

    protected function _isExpandable()
    {
        return !$this->_getInheritanceSettings()->CUSTOM_TABLES;
    }

    protected function _getPartFilters()
    {
        return array(
            'SS_NAME = ?' => array($this->_ssRealName),
            'SST_TABLE_STATUS = ?'  => array('OK')
        );
    }

    protected function _prepareDbRow($row)
    {
        //if no alias for table defined - use SST_NAME as SST_ALIAS
        if (empty($row['SST_ALIAS']))
            $row['SST_ALIAS'] = $row['SST_TABLE'];

        //if SST_ALIAS still empty - raise error, as this is incorrect
        if (empty($row['SST_ALIAS']))
            throw new Minder_SysScreen_Builder_Exception("Sys Screen Table #" . $row['RECORD_ID'] . " has no SST_TABLE and no SST_ALIAS.");

        $row['TABLE_PARAMS'] = array();

        return parent::_prepareDbRow($row);
    }

    protected function _doBuild()
    {
        return parent::_doBuild(); // TODO: Change the autogenerated stub
    }


}