<?php
/**
 * @var Zend_View $this
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle('Minder', 'PREPEND')->setSeparator(' | ');?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/style/themes/minder-ng.css');?>
    <?php echo $this->headMeta();?>
    <?php echo $this->headScript();?>
    <?php echo $this->headStyle();?>
</head>
<body>
    <script type="text/javascript" src="<?php echo $this->baseUrl('scripts/MinderNG/tmp/libs/browser-polyfill.js');?>"></script>
    <script type="text/javascript" data-main="<?php echo $this->baseUrl('scripts/MinderNG/tmp/config.js');?>" src="<?php echo $this->baseUrl('scripts/MinderNG/tmp/libs/require.js');?>"></script>

    <?php
        echo $this->layout()->content;
//        echo $this->render('page-footer.phtml');
    ?>
</body>
</html>