<?php

namespace MinderNG\PageMicrocode\Component;

use MinderNG\Collection\Model;

/**
 * Class User
 * @package MinderNG\PageMicrocode\Component
 *
 * @property string USER_ID
 * @property string COMPANY_ID
 *
 */
class User extends Model {
    public static function getIdAttribute()
    {
        return 'USER_ID';
    }

    /**
     * @param $attributes
     * @return array
     */
    public function parse($attributes)
    {
        if (isset($attributes['PASS_WORD'])) {
            unset($attributes['PASS_WORD']);
        }

        if (isset($attributes['PASS_WORD_DATE'])) {
            unset($attributes['PASS_WORD_DATE']);
        }

        if (isset($attributes['PW_EXPIRY_DATE'])) {
            unset($attributes['PW_EXPIRY_DATE']);
        }

        return parent::parse($attributes); // TODO: Change the autogenerated stub
    }


}