<?php echo $this->render('header.phtml'); ?>
<?php
    $attributes = array('autocomplete' => 'off', 'onkeyup' => 'checkKeys(event)');
    //$attributesForSelect = array('onchange'=>'seek_changed(this.name)');
    $attributesForSelect = array();
?>

<h2>Search Object-Location</h2>

<?php 
	echo $this->messenger()->all();
?>
<br>
<form name="main" id="main"
    action="<?php echo $this->url(array('module' => 'default', 'controller' => 'object', 'action' => 'location'), null, true); ?>"
    method="post">
<br>
<table width="100%">
	<tr>
        <td><strong>Barcode #:</strong> </td>
		<td><?php echo $this->formText('ssn_id', selectFilterValue('ssn_id', $this->conditions)); ?></td>
		<td>Legacy #:</td>
		<td><?php echo $this->formText('legacy_id', selectFilterValue('legacy_id', $this->conditions)); ?></td>
		<td>Owner ID: </td>
		<td><?php  echo $this->formSelectStrict('company_id', selectFilterValue('company_id', $this->conditions), $attributesForSelect, $this->companyIdList); ?>	</td>
	</tr>
	<tr>
        <td>Object Number </td>
		<td><?php echo $this->formText('object_number', selectFilterValue('object_number', $this->conditions)); ?></td>
		<td>Inventory Status</td>
		<td><?php  echo $this->formSelectStrict('issn_status', selectFilterValue('issn_status', $this->conditions), $attributesForSelect, $this->issnStatusIdList); ?>    </td>
		<td>Home Location:</td>
		<td><?php  echo $this->formText('home_locn_id', selectFilterValue('home_locn_id', $this->conditions), $attributesForSelect); ?>    </td>
	</tr>	
	<tr>
		<td>Location ID:</td>
		<td><?php  echo $this->formText('locn_id', selectFilterValue('locn_id', $this->conditions), $attributesForSelect); ?>    </td>
		<td>Prev. Location ID: </td>
		<td><?php  echo $this->formText('prev_locn_id', selectFilterValue('prev_locn_id', $this->conditions), $attributesForSelect); ?>    </td>
		<td>Prev. Prev. Loc:</td>
		<td><?php  echo $this->formText('prev_prev_locn_id', selectFilterValue('prev_prev_locn_id', $this->conditions), $attributesForSelect); ?>    </td>
	</tr>	
	<tr>
		<td>Audit Status</td>
		<td><?php  echo $this->formSelectStrict('audited', selectFilterValue('audited', $this->conditions), $attributesForSelect, $this->auditedIdList); ?></td>
		<td>Audited From:</td>
		<td><?php echo $this->formText('audit_date', selectFilterValue('audit_date', $this->conditions)); ?></td>
		<td>Audited To:</td>
		<td><?php echo $this->formText('max_audit_date', selectFilterValue('max_audit_date', $this->conditions)); ?></td>
	</tr>	
	<tr>
		<td><?php echo $this->other1Name; ?>:</td>
		<td><?php echo $this->formText('other1', selectFilterValue('other1', $this->conditions)); ?></td>
		<td><?php echo $this->other2Name; ?>:</td>
		<td><?php echo $this->formText('other2', selectFilterValue('other2', $this->conditions)); ?></td>
		<td>Transfer Order #:</td>
		<td><?php echo $this->formText('pick_order', selectFilterValue('pick_order', $this->conditions)); ?></td>
	</tr>	
		
</table><br>
<?php echo $this->formSubmit('action', 'SEARCH', array('onclick' => 'goSearch()')); ?>&nbsp;&nbsp;
<?php echo $this->formSubmit('action', 'CLEAR', array('onclick' => 'return frmClear()')) ?>&nbsp;&nbsp;

        <hr />
    <div id="tabs">
        <div style="border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <table style="width:99%">
                <tr>
                    <td>
                        <div style="float:left;">
                            <b>
                                Selected: <span  id="selected_num">0</span>
                            </b>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div style="display:inline">
            <label for='show_by'>View By : </label>
            <?php echo $this->formSelect('show_by',
                                         $this->navigation['show_by'],
                                         array('onchange' => 'frmSubmit()'),
                                         array(  5 => 5,
                                                10 => 10,
                                                15 => 15,
                                                20 => 20,
                                                30 => 30,
                                                40 => 40,
                                                50 => 50,
                                               100 => 100));?>
            <label for='page'>Page : </label>
            <?php echo $this->formSelectStrict('pageselector',
                                               $this->navigation['pageselector'],
                                               array('onchange' => 'frmSubmit()'),
                                               $this->pages); ?>
        </div>
        <hr />
        <table id="location_lines" class="withborder tablesorter" style="width:99%">
            <thead>
            <tr>
            <th>
            <?php echo $this->formCheckbox('select_all',
                                           'any_value',
                                           array('onclick' => 'selectAll(this)'));?>
            </th>
<?php
    foreach ($this->headers as $key => $header) {
        echo '<th abbr="' . $this->escape($key) . '">' . $this->escape($header) . '</th>';
    }
?>
            </tr>
            </thead>
            <tbody>
<?php
    if (count($this->issns) > 0) {
        for ($i = 0; $i < count($this->issns); $i++) {
            $line = $this->issns[$i];
            echo '<tr>';
            echo '<th>';
            echo $this->formCheckbox($this->escape($line->id),
                                     $this->escape($line->id),
                                     array('class' => 'issn_checkbox',
                                           'id' => $this->escape($line->id),
                                           'checked' => selectFilterValue($this->escape($line->id), $this->conditions),
                                           "onclick" => "showSelected(this)"));
            echo '</th>';
            foreach($this->headers as $propertyName => $v) {
                    $val = $line->items[$propertyName];
                    $urlEdit = $this->url(array('module'      => 'warehouse',
                                                'controller'  => 'issn',
                                                'action'      => 'edit'),
                                                '',
                                                true);
                    echo '<td><a href="'. $urlEdit .'/edit_issn_ssn_id/'.$line->id.'" >'. $this->escape($val) . '</a></td>'."\n";
            }
            echo "</tr>\n";
        }
    } else {
        // for tablesorter JavaScript plugin (if no row & cols in table - error occurs).
        echo "<tr><th/>";
        foreach($this->headers as $propertyName => $v) {
            echo '<td/>';
        }
        echo "</tr>\n";
    }
?>
            </tbody>
        </table>
        <ul style="list-style-type: none; border: 0; margin: 0; padding: 0; border-top: 1px solid #999999; border-bottom: 1px solid #999999;">
            <li id='rec_counter' style="display: inline;">
                <div id='num_rec'>Total
                    <?php echo $this->numRecords . " records. "; ?>
                    <?php echo "Show from " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + 1); ?>
                    <?php echo " to " . ($this->navigation['show_by'] * $this->navigation['pageselector'] + $this->maxno); ?>
                </div>
            </li>
        </ul>
    </div>
    <ul class="toolbar">
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: TXT', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: CSV', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XML', array('onclick' => 'return frmSubmit();'))?>
        </li>
        <li>
            <?php echo $this->formSubmit('action', 'REPORT: XLS', array('onclick' => 'return frmSubmit();'))?>
        </li>
    </ul>
    <div id="filter" style="display:none">
        <input type="checkbox" name="mass_action" id="mass_action">
        <input type="checkbox" name="search_action" id="search_action">
        <input type="text" value="" name="edit_issn_ssn_id" id="edit_issn_ssn_id">
    </div>
    <div id="filter" style="display:none">
        <input type="checkbox" name="search_action" id="search_action">
    </div>    
</form>

<script type="text/javascript">

$(document).ready(function () {
    
    var cacheValue      = 1; 
    
        $.ajaxSetup({async:false,
                     complete: onAjaxSuccess,
                     error: onAjaxError,
                     beforeSend: onAjaxBeforeSend});
    $('#location_lines').tablesorter({headers: {0: {sorter:false}},sortList:[[1,1]], widgets: ['zebra']});
  
    $("#tabs #select_complete").bind("click", selectWholeTable);
    showSelected($("#table #select_all").get(0), "init");
    
    $('#audit_date').datepicker({dateFormat: 'yy-mm-dd'});
    $('#max_audit_date').datepicker({dateFormat: 'yy-mm-dd'});
    
    $('#home_locn_id').autocomplete('<?php echo $this->url(array('controller' => 'object', 'action' => 'lookup')); ?>/',
                                {
                                 matchSubset: 1,
                                 matchContains: 1,
                                 cacheLength: cacheValue,
                                 selectFirst: 1,
                                 extraParams: {field: 'home_locn_id'}
                                }
                          );
    $('#locn_id').autocomplete('<?php echo $this->url(array('controller' => 'object', 'action' => 'lookup')); ?>/',
                                {
                                 matchSubset: 1,
                                 matchContains: 1,
                                 cacheLength: cacheValue,
                                 selectFirst: 1,
                                 extraParams: {field: 'home_locn_id'}
                                }
                          );
    $('#prev_locn_id').autocomplete('<?php echo $this->url(array('controller' => 'object', 'action' => 'lookup')); ?>/',
                                {
                                 matchSubset: 1,
                                 matchContains: 1,
                                 cacheLength: cacheValue,
                                 selectFirst: 1,
                                 extraParams: {field: 'home_locn_id'}
                                }
                          );
    $('#prev_locn_id').autocomplete('<?php echo $this->url(array('controller' => 'object', 'action' => 'lookup')); ?>/',
                                {
                                 matchSubset: 1,
                                 matchContains: 1,
                                 cacheLength: cacheValue,
                                 selectFirst: 1,
                                 extraParams: {field: 'home_locn_id'}
                                }
                          );                          
});

function goSearch()
{
    document.getElementById('search_action').checked = true;
    frmSubmit();
    return true;
}

function frmClear()
{           
    $('input:text').each(function() {
        this.value = '';
        });
    $('form select').each(function() {
        if (this.id != 'show_by' && this.id != 'pageselector') {
            this.selectedIndex = 0;
        }
        });
    return false;
}

function selectWholeTable()
{
    var chk = $('table input:checkbox', '#' + $(this).parent().parent()[0].id);
    var checkOnOff = this.checked;
    for (i=0; i < chk.length; i++) {
        chk[i].checked = checkOnOff;
    }
    calcOther(this, $($(this).parent().parent()[0]));
    return true;
}

function calcOther(element, method)
{
    var countEl = 0;
    if ('auto' == method) {
        var container_id = '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = element.checked;
    } else if ('init' == method) {
        var container_id =  '#' + $(element).parent().parent().parent().parent().parent().get(0).id;
        var method = 'init';
    } else {
        var container_id = '#' + $(method)[0].id;
        var method = element.checked;
    }
    $.getJSON('<?php echo $this->url(array('action' => 'marklines', 'controller' => 'object', 'module' => 'default')); ?>',
             { field: 'QTY',
               inAction: '<?php echo 'location'; ?>',
               activeTab: container_id,
               method: method,
               id: element.id,
               value: element.value }, function(json) {
                   var answer = eval(json);
                   $("#selected_num", container_id).text(answer.selected_num);
               });
}

</script>


<?php echo $this->render('footer.phtml'); ?>
