<b>IMPORTS</b> <?php echo $this->desc2; ?>


<table id="import_table" class="withborder tablesorter">
	<thead>
		<tr>
		    <th>
		    	<input type="checkbox" id="select_all_imports">
		    </th>
		    <th>Order #</th>
		    <th>Label #</th>
		    <th>Line #</th>
		    <th>Product ID #</th>
		    <th>Description</th>
		    <th>Before</th>
		    <th>Revised</th>
		    <th>Difference</th>
		</tr>
	</thead>
	<tbody>
<?php
	$i=1;
	foreach ($this->rows as $row) {
?>
	  <tr>
	    <td width="10"><input id="<?php echo $row[0]; ?>" type="checkbox" class="importrows" id="mark" onclick="selectRow(this);"
     <?php
		
     
     	if (array_search($row['0'], $this->revisions_rows_selected)!==false) { ?>
       checked="checked" 
     <?php } ?>	    
	    ></td>
	    <td><?php echo $row['PICK_ORDER']; ?></td>
	    <td><?php echo $row['PICK_LABEL_NO']; ?></td>
	    <td><?php echo $i; ?></td>
	    <td><?php echo $row['PROD_ID']; ?></td>
	    <td><?php echo $row['SHORT_DESC']; ?></td>
	    <td><?php echo $row['PICK_ORDER_QTY']; ?></td>
	    <td><?php echo $row['PICK_ORDER_QTY_01']; ?></td>
	    <td><?php echo $row['PICK_QTY_DIFFERENCE']; ?></td>
	  </tr>
<?php
	$i++;
	} 
?>
	</tbody>
</table>

<form id="revisions_form" action="/minder/trolley">
<table>
  <tr style="height: 25px;">
    <td><input type="button" id="refresh" name="do" value="REFRESH" style="width: 120px; background-color: lightgreen;"></td>
    <td><input type="button" id="report" name="do" value="REPORT: XLS" style="width: 120px; background-color: lightgreen;"></td>
    <td><input type="button" id="adjust" name="do" value="ADJUST" style="width: 120px; background-color: lightgreen;"></td>
    <td><input type="button" id="close" name="do" value="CLOSE" style="width: 120px; background-color: lightgreen;"></td>
  </tr>
</table>
</form>


<?php



?>

<script type="text/javascript">
<!--

$(document).ready(function(){

	$('#import_table').tablesorter({headers:{0:{sorter:false}}, widgets: ['zebra']});
	
});

	$('#refresh').click(function(){
		$("#revisions").load("/trolley/view-revisions");
	});
	
	$('#close').click(function(){
		$("#revisions").hide();
	});
	
	$('#report').click(function(){
		$('#revisions_form')[0].submit();
	});
	
	

	$('#select_all_imports').click(function(){
		$.getJSON('/minder/trolley/mark-imports',
		{prod_id: 'all'},
		function (data) {
			$('#rows_selected').text(data.selected);
		})
		
		if($('#select_all_imports')[0].checked==true) {
			$('input.importrows[type=checkbox]').attr('checked', 'true');
		} else {
			$('input.importrows[type=checkbox]').removeAttr('checked');
		}
		
		return;
	});
	
	 function  selectRow(node){
		id = $(node).attr('id');
		$.getJSON('/minder/trolley/mark-imports',
		{id: id},
		function (data) {
			$('#rows_selected').text(data.selected);
		});
		return;
	}

-->
</script>
